from pathlib import Path

def rep(path, old, new, count=1):
    p=Path(path); s=p.read_text(encoding='utf-8')
    actual=s.count(old)
    if actual!=count:
        raise SystemExit(f'{path}: anchor count {actual} != {count}: {old[:120]}')
    p.write_text(s.replace(old,new,count),encoding='utf-8')

rep('storymigration.js','const VERSION=5;','const VERSION=6;\n const STORY_REFERENCE_RECOVERY_VERSION=1;')
rep('storymigration.js',
'''  const pending=typeof p.pendingStory==="string"&&p.pendingStory?p.pendingStory:null;\n  if(p.pendingStory!==pending){p.pendingStory=pending;changed=true;}\n\n  const completed=uniqueStrings(p.completedStories);\n  if(JSON.stringify(completed)!==JSON.stringify(p.completedStories)){p.completedStories=completed;changed=true;}''',
'''  const stories=options?.stories&&typeof options.stories==="object"?options.stories:{},knownIds=Object.keys(stories),canValidateReferences=knownIds.length>0;\n  const pendingRaw=typeof p.pendingStory==="string"&&p.pendingStory?p.pendingStory:null;\n  const pending=pendingRaw&&(!canValidateReferences||Object.prototype.hasOwnProperty.call(stories,pendingRaw))?pendingRaw:null;\n  if(p.pendingStory!==pending){p.pendingStory=pending;changed=true;}\n\n  let completed=uniqueStrings(p.completedStories);\n  if(canValidateReferences)completed=completed.filter(id=>Object.prototype.hasOwnProperty.call(stories,id));\n  if(JSON.stringify(completed)!==JSON.stringify(p.completedStories)){p.completedStories=completed;changed=true;}''')
rep('storymigration.js','  version:VERSION,\n  legacyFields:LEGACY_FIELDS.slice(),','  version:VERSION,\n  referenceRecoveryVersion:STORY_REFERENCE_RECOVERY_VERSION,\n  legacyFields:LEGACY_FIELDS.slice(),')
rep('storymigration.js',' window.STORY_MIGRATION_VERSION=VERSION;',' window.STORY_MIGRATION_VERSION=VERSION;\n window.STORY_REFERENCE_RECOVERY_VERSION=STORY_REFERENCE_RECOVERY_VERSION;')

rep('thirdworldphase.js',' const VERSION=6;',' const VERSION=7;')
rep('thirdworldphase.js',' const THIRD_WORLD_CORE_PROGRESS_NORMALIZATION_VERSION=2;',' const THIRD_WORLD_CORE_PROGRESS_NORMALIZATION_VERSION=2;\n const THIRD_WORLD_STORY_RECONCILIATION_VERSION=1;\n const THIRD_WORLD_STORY_DEVELOPMENT_RESET_VERSION=1;')
rep('thirdworldphase.js',
' function normalizeStory(value){const source=isObject(value)?value:{};return {introSeen:source.introSeen===true,unlockedStage:clamp(finiteWhole(source.unlockedStage,0),0,THIRD_WORLD_STORY_MAX_STAGE),finalSeen:source.finalSeen===true};}\n',
''' function normalizeStory(value){const source=isObject(value)?value:{};return {introSeen:source.introSeen===true,unlockedStage:clamp(finiteWhole(source.unlockedStage,0),0,THIRD_WORLD_STORY_MAX_STAGE),finalSeen:source.finalSeen===true};}\n function thirdWorldStoryDescriptorReady(kind){\n  const rows=typeof window.thirdWorldStoryTriggerDescriptors==="function"?Array.from(window.thirdWorldStoryTriggerDescriptors()):[];\n  return rows.some(row=>row?.kind===kind&&row?.contentReady===true);\n }\n function canonicalThirdWorldStoryStage(target){\n  if(typeof window.thirdWorldTitleTier!=="function")return null;\n  return clamp(finiteWhole(window.thirdWorldTitleTier(target),0),0,THIRD_WORLD_STORY_MAX_STAGE);\n }\n function reconcileThirdWorldStoryState(target){\n  if(!isObject(target)||!isObject(target.thirdWorld)||target.thirdWorld.entered!==true)return {applied:false,reason:"not-entered"};\n  const third=target.thirdWorld;if(!isObject(third.story))third.story=normalizeStory(null);\n  const story=third.story,before={introSeen:story.introSeen===true,unlockedStage:clamp(finiteWhole(story.unlockedStage,0),0,THIRD_WORLD_STORY_MAX_STAGE),finalSeen:story.finalSeen===true,completed:third.completed===true};\n  const canonicalStage=canonicalThirdWorldStoryStage(target),bossesDefeated=thirdWorldBossesAllDefeated(target),introReady=thirdWorldStoryDescriptorReady("intro"),finalReady=thirdWorldStoryDescriptorReady("final");\n  if(canonicalStage!=null)story.unlockedStage=canonicalStage;\n  if(!introReady)story.introSeen=false;\n  if(!finalReady||!bossesDefeated){story.finalSeen=false;third.completed=false;}\n  const after={introSeen:story.introSeen===true,unlockedStage:clamp(finiteWhole(story.unlockedStage,0),0,THIRD_WORLD_STORY_MAX_STAGE),finalSeen:story.finalSeen===true,completed:third.completed===true};\n  const applied=JSON.stringify(before)!==JSON.stringify(after),report={applied,version:THIRD_WORLD_STORY_RECONCILIATION_VERSION,developmentResetVersion:THIRD_WORLD_STORY_DEVELOPMENT_RESET_VERSION,canonicalStage,bossesDefeated,introContentReady:introReady,finalContentReady:finalReady,before,after};\n  window.LAST_THIRD_WORLD_STORY_RECONCILIATION_REPORT=report;return report;\n }\n''')
rep('thirdworldphase.js',
'  if(entered){if(!isObject(target.secondWorld))target.secondWorld=typeof window.createBlankSecondWorldState==="function"?window.createBlankSecondWorldState():{entered:true};target.secondWorld.entered=true;reconcileThirdWorldEntryState(target);}\n  return target;',
'  if(entered){if(!isObject(target.secondWorld))target.secondWorld=typeof window.createBlankSecondWorldState==="function"?window.createBlankSecondWorldState():{entered:true};target.secondWorld.entered=true;reconcileThirdWorldEntryState(target);reconcileThirdWorldStoryState(target);}\n  return target;')
rep('thirdworldphase.js',' window.THIRD_WORLD_CORE_PROGRESS_NORMALIZATION_VERSION=THIRD_WORLD_CORE_PROGRESS_NORMALIZATION_VERSION;',' window.THIRD_WORLD_CORE_PROGRESS_NORMALIZATION_VERSION=THIRD_WORLD_CORE_PROGRESS_NORMALIZATION_VERSION;\n window.THIRD_WORLD_STORY_RECONCILIATION_VERSION=THIRD_WORLD_STORY_RECONCILIATION_VERSION;\n window.THIRD_WORLD_STORY_DEVELOPMENT_RESET_VERSION=THIRD_WORLD_STORY_DEVELOPMENT_RESET_VERSION;')
rep('thirdworldphase.js',' window.reconcileThirdWorldCoreProgressionState=reconcileThirdWorldCoreProgressionState;',' window.reconcileThirdWorldCoreProgressionState=reconcileThirdWorldCoreProgressionState;\n window.reconcileThirdWorldStoryState=reconcileThirdWorldStoryState;\n window.canonicalThirdWorldStoryStage=canonicalThirdWorldStoryStage;')

rep('thirdworldmigrationregression.js',' const VERSION=4;',' const VERSION=5;')
rep('thirdworldmigrationregression.js',' const LEGACY_CORE_POLICY_REGRESSION_VERSION=1;',' const LEGACY_CORE_POLICY_REGRESSION_VERSION=1;\n const STORY_RECONCILIATION_REGRESSION_VERSION=1;')
rep('thirdworldmigrationregression.js','if(typeof window.migrateSave!=="function"||typeof window.normalizeThirdWorldCoreInvestment!=="function"||typeof window.reconcileThirdWorldCoreProgressionState!=="function"||!Number.isInteger(max)||max<=0||count!==10)','if(typeof window.migrateSave!=="function"||typeof window.normalizeThirdWorldCoreInvestment!=="function"||typeof window.reconcileThirdWorldCoreProgressionState!=="function"||typeof window.reconcileThirdWorldStoryState!=="function"||!Number.isInteger(max)||max<=0||count!==10)')
rep('thirdworldmigrationregression.js',
'    const missingProgress=baseSave(distinct);missingProgress.thirdWorld.coreLevel=4;missingProgress.thirdWorld.dimensionalStrings=2000000000;',
'''    const fullBosses=Array.from({length:count},()=>({currentHp:max})),oneDead=[{currentHp:0},...Array.from({length:count-1},()=>({currentHp:max}))],fiveDead=[...Array.from({length:5},()=>({currentHp:0})),...Array.from({length:5},()=>({currentHp:max}))],allDead=Array.from({length:count},()=>({currentHp:0}));\n    const storyLag=baseSave(oneDead);storyLag.thirdWorld.story={introSeen:false,unlockedStage:0,finalSeen:false};\n    runCase("SCHEMA16_STORY_STAGE_LAG_RECONCILED",storyLag,m=>Number(m?.thirdWorld?.story?.unlockedStage)===1);\n    const storyAhead=baseSave(fullBosses);storyAhead.thirdWorld.story={introSeen:false,unlockedStage:9,finalSeen:false};\n    runCase("SCHEMA16_STORY_STAGE_AHEAD_RECONCILED",storyAhead,m=>Number(m?.thirdWorld?.story?.unlockedStage)===0);\n    const storyMissing=baseSave(fiveDead);storyMissing.thirdWorld.story={};\n    runCase("SCHEMA16_STORY_STAGE_MISSING_REBUILT",storyMissing,m=>Number(m?.thirdWorld?.story?.unlockedStage)===5);\n    const storyDead=baseSave(allDead);storyDead.thirdWorld.story={introSeen:false,unlockedStage:0,finalSeen:false};\n    runCase("SCHEMA16_STORY_STAGE_ALL_DEAD_REBUILT",storyDead,m=>Number(m?.thirdWorld?.story?.unlockedStage)===10);\n    const devFlags=baseSave(allDead);devFlags.thirdWorld.completed=true;devFlags.thirdWorld.story={introSeen:true,unlockedStage:10,finalSeen:true};\n    runCase("SCHEMA16_PRE_CONTENT_STORY_FLAGS_RESET",devFlags,m=>m?.thirdWorld?.story?.introSeen===false&&m?.thirdWorld?.story?.finalSeen===false&&m?.thirdWorld?.completed===false&&Number(m?.thirdWorld?.story?.unlockedStage)===10);\n    const impossibleCompleted=baseSave(fullBosses);impossibleCompleted.thirdWorld.completed=true;impossibleCompleted.thirdWorld.story={introSeen:true,unlockedStage:10,finalSeen:true};\n    runCase("SCHEMA16_IMPOSSIBLE_COMPLETION_RESET",impossibleCompleted,m=>m?.thirdWorld?.completed===false&&m?.thirdWorld?.story?.finalSeen===false&&Number(m?.thirdWorld?.story?.unlockedStage)===0);\n\n    const missingProgress=baseSave(distinct);missingProgress.thirdWorld.coreLevel=4;missingProgress.thirdWorld.dimensionalStrings=2000000000;''')
rep('thirdworldmigrationregression.js','legacyCorePolicyRegressionVersion:LEGACY_CORE_POLICY_REGRESSION_VERSION,preSchema16Policy:','legacyCorePolicyRegressionVersion:LEGACY_CORE_POLICY_REGRESSION_VERSION,storyReconciliationRegressionVersion:STORY_RECONCILIATION_REGRESSION_VERSION,preSchema16Policy:')
rep('thirdworldmigrationregression.js',' window.THIRD_WORLD_LEGACY_CORE_POLICY_REGRESSION_VERSION=LEGACY_CORE_POLICY_REGRESSION_VERSION;',' window.THIRD_WORLD_LEGACY_CORE_POLICY_REGRESSION_VERSION=LEGACY_CORE_POLICY_REGRESSION_VERSION;\n window.THIRD_WORLD_STORY_RECONCILIATION_REGRESSION_VERSION=STORY_RECONCILIATION_REGRESSION_VERSION;')

rep('storyruntimeintegrity.js',' const VERSION=15;',' const VERSION=16;\n const LEGACY_REFERENCE_RECOVERY_VERSION=1;')
anchor='  if(typeof window.openStory!=="function"||typeof window.isStoryOpen!=="function"||typeof window.waitForStoryClosed!=="function"||Number(window.STORY_UI_VERSION)!==9||Number(window.STORY_UI_LIFECYCLE_WAIT_VERSION)!==1)fail("STORY_RUNTIME_UI_MISSING","共用正式劇情視窗／lifecycle wait owner 未完整載入");'
block='''  if(Number(window.STORY_MIGRATION_VERSION)!==6||Number(window.STORY_REFERENCE_RECOVERY_VERSION)!==1)fail("STORY_RUNTIME_REFERENCE_RECOVERY_OWNER","Story migration reference recovery owner 未就緒");\n  try{\n   const migration=window.civilizationStoryMigration,stories=window.CIVILIZATION_STORIES||{},universeId=window.universeStoryIdForBossIndex?.(0),options={introStoryId:"earth-prologue",stories,regions:[],skipBackfill:true};\n   const probe=(pending,completed)=>({introSeen:true,storyProgress:{pendingStory:pending,completedStories:completed,introCompleted:true,starterGearReceived:true}});\n   const galaxy=probe("earth-prologue",["earth-prologue"]);migration?.migrate?.(galaxy,options);if(galaxy.storyProgress.pendingStory!=="earth-prologue")fail("STORY_RUNTIME_VALID_GALAXY_PENDING_REMOVED","合法銀河 pendingStory 不得被清除",galaxy.storyProgress);\n   if(universeId&&stories[universeId]){const universe=probe(universeId,["earth-prologue",universeId]);migration?.migrate?.(universe,options);if(universe.storyProgress.pendingStory!==universeId||!universe.storyProgress.completedStories.includes(universeId))fail("STORY_RUNTIME_VALID_UNIVERSE_REFERENCE_REMOVED","合法宇宙 Story reference 不得被清除",universe.storyProgress);}\n   const stale=probe("retired-story-probe",["earth-prologue","retired-story-probe","higher-dimensional-intro"]);migration?.migrate?.(stale,options);if(stale.storyProgress.pendingStory!==null||stale.storyProgress.completedStories.includes("retired-story-probe")||stale.storyProgress.completedStories.includes("higher-dimensional-intro"))fail("STORY_RUNTIME_STALE_REFERENCE_NOT_CLEANED","退休／placeholder Story reference 應於正式 catalog 可用時清除",stale.storyProgress);\n   const placeholder=probe("higher-dimensional-intro",["earth-prologue"]);migration?.migrate?.(placeholder,options);if(placeholder.storyProgress.pendingStory!==null)fail("STORY_RUNTIME_PLACEHOLDER_PENDING_NOT_CLEANED","尚未有正式資料的 W3 placeholder pendingStory 必須清除",placeholder.storyProgress);\n  }catch(error){fail("STORY_RUNTIME_REFERENCE_RECOVERY_FAILED","Story reference recovery regression 發生錯誤",String(error?.message||error));}\n\n'''+anchor
rep('storyruntimeintegrity.js',anchor,block)
rep('storyruntimeintegrity.js',' window.STORY_RUNTIME_INTEGRITY_VERSION=VERSION;',' window.STORY_RUNTIME_INTEGRITY_VERSION=VERSION;\n window.STORY_RUNTIME_LEGACY_REFERENCE_RECOVERY_VERSION=LEGACY_REFERENCE_RECOVERY_VERSION;')

rep('thirdworldintegritycontract.js',' const VERSION=35;',' const VERSION=36;')
rep('thirdworldintegritycontract.js','THIRD_WORLD_PHASE_VERSION:6,THIRD_WORLD_PERSISTENCE_POLICY_VERSION:2,','THIRD_WORLD_PHASE_VERSION:7,THIRD_WORLD_PERSISTENCE_POLICY_VERSION:2,')
rep('thirdworldintegritycontract.js','THIRD_WORLD_CORE_RECONCILIATION_VERSION:1,THIRD_WORLD_CORE_PROGRESS_NORMALIZATION_VERSION:2,','THIRD_WORLD_CORE_RECONCILIATION_VERSION:1,THIRD_WORLD_CORE_PROGRESS_NORMALIZATION_VERSION:2,THIRD_WORLD_STORY_RECONCILIATION_VERSION:1,THIRD_WORLD_STORY_DEVELOPMENT_RESET_VERSION:1,')
rep('thirdworldintegritycontract.js','SAVE_THIRD_WORLD_BOSS_MIGRATION_REGRESSION_VERSION:4,THIRD_WORLD_PRE_SCHEMA16_POLICY_REGRESSION_VERSION:1,','SAVE_THIRD_WORLD_BOSS_MIGRATION_REGRESSION_VERSION:5,THIRD_WORLD_PRE_SCHEMA16_POLICY_REGRESSION_VERSION:1,')
rep('thirdworldintegritycontract.js','THIRD_WORLD_LEGACY_CORE_POLICY_REGRESSION_VERSION:1,','THIRD_WORLD_LEGACY_CORE_POLICY_REGRESSION_VERSION:1,THIRD_WORLD_STORY_RECONCILIATION_REGRESSION_VERSION:1,')
rep('thirdworldintegritycontract.js','"normalizeThirdWorldCoreInvestment","reconcileThirdWorldCoreProgressionState",','"normalizeThirdWorldCoreInvestment","reconcileThirdWorldCoreProgressionState","reconcileThirdWorldStoryState","canonicalThirdWorldStoryStage",')
rep('thirdworldintegritycontract.js','Number(migration?.legacyCorePolicyRegressionVersion)!==1','Number(migration?.legacyCorePolicyRegressionVersion)!==1||Number(migration?.storyReconciliationRegressionVersion)!==1')

rep('tests/story/flow.js','// Batch 12-4 exact-head：Run Summary → shared Story drain → Title Notice、modal hold 與 reload recovery 必須同時通過 Story／Runtime Integrity。','// Batch 12-4 exact-head：Run Summary → shared Story drain → Title Notice、modal hold 與 reload recovery 必須同時通過 Story／Runtime Integrity。\n// Batch 12-O1：舊 W3 Story flags／Stage reconciliation 與 stale Story reference recovery 必須 fail-closed。')
rep('tests/story/flow.js','const runtime=fs.readFileSync(\'storyruntimeintegrity.js\',\'utf8\');','const runtime=fs.readFileSync(\'storyruntimeintegrity.js\',\'utf8\');\nconst migration=fs.readFileSync(\'storymigration.js\',\'utf8\');')
rep('tests/story/flow.js','/STORY_RUNTIME_INTEGRITY_VERSION=VERSION/.test(runtime)&&/const VERSION=15;/.test(runtime)','/STORY_RUNTIME_INTEGRITY_VERSION=VERSION/.test(runtime)&&/const VERSION=16;/.test(runtime)')
rep('tests/story/flow.js','Story Runtime Integrity 應為 V15','Story Runtime Integrity 應為 V16')
rep('tests/story/flow.js','assert(/STORY_RUNTIME_THIRD_WORLD_PLACEHOLDER_QUEUED/.test(runtime)&&/STORY_RUNTIME_THIRD_WORLD_SEQUENTIAL_RECOVERY/.test(runtime),\'Runtime Integrity 未驗證 placeholder zero-queue／順序補播\');','assert(/STORY_RUNTIME_THIRD_WORLD_PLACEHOLDER_QUEUED/.test(runtime)&&/STORY_RUNTIME_THIRD_WORLD_SEQUENTIAL_RECOVERY/.test(runtime),\'Runtime Integrity 未驗證 placeholder zero-queue／順序補播\');\nassert(/const VERSION=6;/.test(migration)&&/STORY_REFERENCE_RECOVERY_VERSION/.test(migration),\'Story migration 必須提供 V6 stale reference recovery\');\nassert(/STORY_RUNTIME_STALE_REFERENCE_NOT_CLEANED/.test(runtime)&&/STORY_RUNTIME_PLACEHOLDER_PENDING_NOT_CLEANED/.test(runtime),\'Runtime Integrity 未覆蓋 stale／placeholder pending recovery\');')

cache={
 'thirdworldphase.js?v=20260928-thirdworld-batch12-3':'thirdworldphase.js?v=20260928-thirdworld-batch12-o1',
 'thirdworldmigrationregression.js?v=20260928-thirdworld-batch10-opt2':'thirdworldmigrationregression.js?v=20260928-thirdworld-batch12-o1',
 'thirdworldintegritycontract.js?v=20260928-thirdworld-batch12-4':'thirdworldintegritycontract.js?v=20260928-thirdworld-batch12-o1',
 'storymigration.js?v=20260918-retire-backfill1':'storymigration.js?v=20260928-thirdworld-batch12-o1',
 'storyruntimeintegrity.js?v=20260928-thirdworld-batch12-4':'storyruntimeintegrity.js?v=20260928-thirdworld-batch12-o1',
}
for old,new in cache.items(): rep('index.html',old,new)
