// 永久回歸檢查：銀河 101 篇＋宇宙 100 篇；高維 11 篇正式內容完整驗證。
const fs=require('fs');const vm=require('vm');
const files=['data.js','worldmaps-earth.js','worldmaps-solar.js','worldmaps-nearstar.js','worldmaps-frontier.js','worldmaps-orion.js','worldmaps-galactic-frontier.js','worldmaps-galactic-mid.js','worldmaps-core-outer.js','worldmaps-core-war.js','worldmaps-galactic-unification.js','secondworlddata.js','secondworldstoryregistry.js','storydata-earth.js','storydata-solar.js','storydata-nearstar.js','storydata-frontier.js','storydata-orion.js','storydata-galactic-frontier.js','storydata-galactic-mid.js','storydata-core-outer.js','storydata-core-war.js','storydata-galactic-unification.js','storydata-universe-galaxy-beyond.js','storydata-universe-local-group-war.js','storydata-universe-star-cluster-frontier.js','storydata-universe-stellar-battlefront.js','storydata-universe-cosmic-filament.js','storydata-universe-stellar-great-wall.js','storydata-universe-cosmic-deep-domain.js','storydata-universe-trans-domain-frontier.js','storydata-universe-myriad-domain-frontline.js','storydata-universe-cosmic-unification-war.js','storydata-higher-dimensional.js','storydata-higher-dimensional-stage2-3.js','storydata-higher-dimensional-stage4-5.js','storydata-higher-dimensional-stage6-7.js','storydata-higher-dimensional-stage8-9.js','storydata-higher-dimensional-final.js','storyintegrity.js'];
const context={console,setTimeout,clearTimeout,Date,Math,JSON,Object,Array,Set,Map,String,Number,Boolean,RegExp,Error,Buffer,atob:s=>Buffer.from(String(s),'base64').toString('binary'),btoa:s=>Buffer.from(String(s),'binary').toString('base64')};context.window=context;vm.createContext(context);
const expectedReadyW3=['higher-dimensional-intro','higher-dimensional-milestone-01','higher-dimensional-milestone-02','higher-dimensional-milestone-03','higher-dimensional-milestone-04','higher-dimensional-milestone-05','higher-dimensional-milestone-06','higher-dimensional-milestone-07','higher-dimensional-milestone-08','higher-dimensional-milestone-09','higher-dimensional-final'];
try{
 for(const file of files){if(!fs.existsSync(file))throw new Error(`缺少正式劇情資料檔：${file}`);vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});}
 const report=context.STORY_INTEGRITY_REPORT;if(!report){console.error('STORY_INTEGRITY_REPORT 不存在');process.exit(2);}
 if(Number(report.version)<12){console.error(`STORY_INTEGRITY_VERSION 過舊：${report.version}`);process.exit(4);}
 const expectedPolicy={intro:{pages:12,minChars:90,maxChars:155,minBlocks:3},regularBoss:{pages:11,minChars:90,maxChars:120,minBlocks:2},regionFinale:{pages:15,minChars:120,maxChars:155,minBlocks:3},finalBoss:{pages:31,minChars:90,maxChars:155,minBlocks:3}};
 const expectedThirdPolicy={intro:{pages:12,minChars:120,maxChars:155,minBlocks:3},stage:{pages:31,minChars:120,maxChars:155,minBlocks:3},final:{pages:31,minChars:120,maxChars:155,minBlocks:3}};
 if(JSON.stringify(report.formatPolicy||{})!==JSON.stringify(expectedPolicy)){console.error(`STORY FORMAT POLICY 不一致：${JSON.stringify(report.formatPolicy)}`);process.exit(6);}
 if(JSON.stringify(report.thirdWorldFormatPolicy||{})!==JSON.stringify(expectedThirdPolicy)){console.error(`W3 STORY FORMAT POLICY 不一致：${JSON.stringify(report.thirdWorldFormatPolicy)}`);process.exit(11);}
 if(Number(report.galaxyStories)!==101||Number(report.bossStoriesChecked)!==100){console.error(`銀河紀元劇情數量錯誤：${report.galaxyStories}/101, boss=${report.bossStoriesChecked}/100`);process.exit(7);}
 if(Number(report.universeRegions)!==10||Number(report.universeStoriesExpected)!==100||context.UNIVERSE_STORY_REGISTRY_READY!==true){console.error(`宇宙紀元 Registry 錯誤：regions=${report.universeRegions}, stories=${report.universeStoriesExpected}`);process.exit(8);}
 if(Number(report.universeStoriesLoaded)!==100){console.error(`目前宇宙正式文字應為 100/100，實際 ${report.universeStoriesLoaded}/100`);process.exit(10);}
 if(Number(report.thirdWorldStoriesExpected)!==11||Number(report.thirdWorldStoriesLoaded)!==11){console.error(`Batch 13-7 高維正式文字應為 11/11，實際 ${report.thirdWorldStoriesLoaded}/${report.thirdWorldStoriesExpected}`);process.exit(12);}
 expectedReadyW3.forEach(id=>{if(!context.CIVILIZATION_STORIES?.[id])throw new Error(`缺少已上線高維正式劇情 ${id}`);});
 const loadedW3=Object.keys(context.CIVILIZATION_STORIES||{}).filter(id=>id.startsWith('higher-dimensional-'));
 if(JSON.stringify(loadedW3)!==JSON.stringify(expectedReadyW3)){console.error(`Batch 13-7 runtime catalog 應完整 11 篇：${JSON.stringify(loadedW3)}`);process.exit(13);}
 const ready=(context.thirdWorldStoryTriggerDescriptors?.()||[]).filter(row=>row.contentReady===true).map(row=>row.storyId);
 if(JSON.stringify(ready)!==JSON.stringify(expectedReadyW3)){console.error(`Batch 13-7 contentReady 錯誤：${JSON.stringify(ready)}`);process.exit(14);}
 ['universe-galaxy-beyond-boss-1','universe-galaxy-beyond-boss-10','universe-local-group-war-boss-1','universe-local-group-war-boss-10','universe-cosmic-unification-war-boss-10'].forEach(id=>{if(!context.CIVILIZATION_STORIES?.[id])throw new Error(`缺少既有宇宙正式樣板 ${id}`);});
 if(Number(report.totalStoriesTarget)!==201||Number(report.allEraStoriesTarget)!==212){console.error(`劇情目標錯誤：legacy=${report.totalStoriesTarget}, allEra=${report.allEraStoriesTarget}`);process.exit(9);}
 if(report.passed){console.log(`STORY INTEGRITY PASSED | galaxy=${report.galaxyStories}/101 universe=${report.universeStoriesLoaded}/100 higher-dimensional=${report.thirdWorldStoriesLoaded}/11 approved=11 allEraTarget=${report.allEraStoriesTarget}`);process.exit(0);}
 console.error(`STORY INTEGRITY FAILED: ${report.errors.length} error(s)`);report.errors.forEach((e,i)=>console.error(`${i+1}. [${e.code}] ${e.message}`));process.exit(1);
}catch(error){console.error('STORY INTEGRITY CI EXECUTION FAILED');console.error(error&&error.stack?error.stack:error);process.exit(3);}
