(function(){
 const ALTERNATE_UNIVERSE_PLAYER_UI_VERSION=1;
 const HOME_BRIDGE_VERSION=1;
 let lastBattleReport=null;
 function esc(v){return String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));}
 function whole(v,fallback=0){const n=Math.floor(Number(v));return Number.isFinite(n)?n:fallback;}
 function fmt(v){return Math.max(0,whole(v,0)).toLocaleString();}
 function currentState(){try{return typeof state!=="undefined"&&state&&typeof state==="object"?state:(window.state&&typeof window.state==="object"?window.state:null);}catch(_){return window.state&&typeof window.state==="object"?window.state:null;}}
 function progress(){return typeof window.alternateUniverseProgressionSnapshot==="function"?window.alternateUniverseProgressionSnapshot(currentState()):null;}
 function depthInfo(depth){return typeof window.alternateUniverseDepthInfo==="function"?window.alternateUniverseDepthInfo(depth):null;}
 function baseStats(depth){return typeof window.alternateUniverseEnemyStats==="function"?window.alternateUniverseEnemyStats(depth):null;}
 function activeAttempt(){return typeof window.alternateUniverseActiveAttempt==="function"?window.alternateUniverseActiveAttempt(currentState()):null;}
 function failureStatus(depth){return typeof window.alternateUniverseFailureStatus==="function"?window.alternateUniverseFailureStatus(depth,currentState()):null;}
 function traitMeta(id){return window.MONSTER_TRAITS?.[id]||{name:id,desc:""};}
 function traitHtml(ids){const rows=(Array.isArray(ids)?ids:[]).map(id=>{const t=traitMeta(id);return `<div class="au-trait"><b>${esc(t.name)}</b><span>${esc(t.desc)}</span></div>`;}).join("");return rows?`<div class="au-traits">${rows}</div>`:'<div class="muted">尚未建立本次挑戰。</div>';}
 function infoTitle(info){return info?`U${info.depth}｜${esc(info.universeName)}・${esc(info.stageName||info.stageLabel||"")}`:"異宇宙";}
 function ensureStyles(){if(document.getElementById("alternate-universe-player-ui-style"))return;const style=document.createElement("style");style.id="alternate-universe-player-ui-style";style.textContent=`
 .au-home-entry{border-color:#596c9b;background:linear-gradient(135deg,rgba(18,27,50,.96),rgba(22,18,43,.96));box-shadow:0 18px 42px rgba(4,8,23,.28)}
 .au-home-entry .world-phase-kicker{color:#8ccfff}.au-home-entry h3{color:#e8f4ff}.au-home-entry .btn.primary{background:#294f80;border-color:#4e7fb9}
 .au-shell{max-width:980px;margin:0 auto;padding-bottom:24px}.au-hero,.au-card,.au-result{background:linear-gradient(180deg,#111a2b,#0c1220);border:1px solid #344d75;border-radius:14px;padding:16px;margin-bottom:14px;box-shadow:0 12px 30px rgba(0,0,0,.18)}
 .au-hero h2,.au-card h3,.au-result h3{margin:0 0 8px;color:#dfeeff}.au-kicker{font-size:12px;font-weight:800;letter-spacing:.14em;color:#79bfff;text-transform:uppercase}.au-progress-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:14px}.au-progress-grid>div,.au-stat-grid>div{background:#0a111d;border:1px solid #283c5d;border-radius:10px;padding:10px}.au-progress-grid span,.au-stat-grid span{display:block;font-size:12px;color:#8fa6c6}.au-progress-grid b,.au-stat-grid b{display:block;margin-top:4px;font-size:18px;color:#eff7ff}
 .au-card-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.au-stage{display:inline-block;padding:4px 9px;border:1px solid #4c6894;border-radius:999px;color:#a9d2ff;font-size:12px;font-weight:700}.au-stat-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin:12px 0}.au-traits{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:12px 0}.au-trait{background:#16162a;border:1px solid #4f4f7c;border-radius:10px;padding:10px}.au-trait b{display:block;color:#f0e8ff}.au-trait span{display:block;color:#b8afd0;font-size:12px;margin-top:3px;line-height:1.5}
 .au-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.au-actions .btn.primary{background:#285a8a;border-color:#4d82b9}.au-actions .btn.danger{background:#642f3f;border-color:#925069;color:#fff}.au-warning{border-color:#86556a;background:#25151e}.au-complete{border-color:#7f6a3c;background:linear-gradient(180deg,#292316,#17140e)}.au-complete h3{color:#ffe7a3}.au-review-row{display:grid;grid-template-columns:minmax(120px,180px) auto;gap:8px;align-items:end}.au-review-row label{display:grid;gap:5px;color:#9fb0c8;font-size:12px}.au-review-row input{width:100%;box-sizing:border-box;background:#0a111d;border:1px solid #344d75;color:#fff;border-radius:8px;padding:9px 10px}.au-result.win{border-color:#46775d}.au-result.loss{border-color:#875061}.au-result-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:10px}.au-result-meta>div{background:#0a111d;border-radius:9px;padding:9px}.au-result-meta span{display:block;color:#8fa6c6;font-size:12px}.au-result-meta b{display:block;color:#eef5ff;margin-top:4px}.au-note{font-size:12px;color:#91a2bb;line-height:1.6;margin-top:8px}
 @media(max-width:760px){.au-progress-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.au-stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.au-traits{grid-template-columns:1fr}.au-card-head{display:block}.au-stage{margin-top:6px}.au-review-row{grid-template-columns:1fr}.au-result-meta{grid-template-columns:1fr}}
 `;document.head.appendChild(style);}
 function homeEntryHtml(){
  if(typeof window.alternateUniverseHomeEntryVisible!=="function"||window.alternateUniverseHomeEntryVisible(currentState())!==true)return "";
  const snap=progress();const text=snap?.unlocked?`最深征服 U${whole(snap.deepestCleared,0)} / ${whole(snap.maxDepth,1000)}`:"已擊敗 10 名高維存在，異宇宙已開放。";
  return `<section class="world-phase-home-card au-home-entry" data-alternate-universe-home-entry="1"><div class="world-phase-home-copy"><div class="world-phase-kicker">終局挑戰</div><h3>異宇宙</h3><div class="world-phase-home-desc">跨越既有紀元，挑戰 200 個宇宙、1000 個深度。無資源收益，只記錄征服進度。</div><div class="world-phase-progress">${esc(text)}</div></div><div class="world-phase-home-actions"><button class="btn primary" onclick="openAlternateUniversePage()">進入異宇宙</button></div></section>`;
 }
 function installHomeBridge(){
  if(Number(window.ALTERNATE_UNIVERSE_HOME_BRIDGE_VERSION)>=HOME_BRIDGE_VERSION)return true;
  const base=window.secondWorldHomeEntryHtml;if(typeof base!=="function")return false;
  window.secondWorldHomeEntryHtml=function(){return String(base.apply(this,arguments)||"")+homeEntryHtml();};
  window.ALTERNATE_UNIVERSE_HOME_BRIDGE_VERSION=HOME_BRIDGE_VERSION;return true;
 }
 function unlockForEntry(){
  if(typeof window.ensureAlternateUniversePermanentUnlock!=="function")return {ok:false,reason:"access-owner-missing"};
  return window.ensureAlternateUniversePermanentUnlock(currentState());
 }
 function openPage(){const access=unlockForEntry();if(!access?.ok){alert(access?.reason==="third-world-bosses-incomplete"?"擊敗 10 名高維存在後才會解鎖異宇宙。":"異宇宙入口尚未完成解鎖，請重新整理後再試。");return false;}try{view="alternateuniverse";}catch(_){}lastBattleReport=null;renderPage();return true;}
 function progressHtml(snap){return `<div class="au-progress-grid"><div><span>征服深度</span><b>${fmt(snap?.deepestCleared)} / ${fmt(snap?.maxDepth||1000)}</b></div><div><span>已征服宇宙</span><b>${fmt(snap?.completedUniverses)} / ${fmt(snap?.totalUniverses||200)}</b></div><div><span>下一前線</span><b>${snap?.nextDepth?`U${fmt(snap.nextDepth)}`:"完成"}</b></div><div><span>剩餘深度</span><b>${fmt(snap?.remainingDepths)}</b></div></div>`;}
 function statsHtml(stats){if(!stats)return "";return `<div class="au-stat-grid"><div><span>HP</span><b>${fmt(stats.hp)}</b></div><div><span>ATK</span><b>${fmt(stats.atk)}</b></div><div><span>DEF</span><b>${fmt(stats.def)}</b></div><div><span>暴擊</span><b>${Number(stats.crit||0)}%</b></div><div><span>閃避</span><b>${Number(stats.dodge||0)}%</b></div></div>`;}
 function resultHtml(){const row=lastBattleReport;if(!row)return "";const result=row.result;const basis=result?.settlementBasis||result?.combatResult?.settlementBasis;const combat=result?.combat||result?.combatResult?.combat;const win=basis?.outcome==="win";const incomplete=basis?.outcome==="incomplete";const title=incomplete?"戰鬥未完成":win?"勝利":"敗北";const mode=row.review?"回顧戰":"正式攻略";return `<section class="au-result ${win?"win":"loss"}"><div class="au-kicker">${mode}</div><h3>${title}｜U${fmt(row.depth)}</h3><div class="au-result-meta"><div><span>回合</span><b>${fmt(basis?.turns||combat?.turns)}</b></div><div><span>玩家剩餘 HP</span><b>${fmt(basis?.playerEndHp??combat?.hp)}</b></div><div><span>敵方剩餘 HP</span><b>${fmt(basis?.enemyEndHp??combat?.enemyHp)}</b></div></div>${traitHtml(row.traits)}<div class="au-note">${row.review?"回顧戰不改 deepestCleared、不計失敗、不建立 activeAttempt，也沒有任何收益。":incomplete?"此戰未形成正式勝敗，activeAttempt 保留，可再次進行戰鬥。":win?"正式勝利已推進異宇宙征服進度。":"正式敗北已計入本輪此 U 的失敗次數。"}</div></section>`;}
 function frontierHtml(snap){
  if(snap?.completed)return `<section class="au-card au-complete"><div class="au-kicker">異宇宙征服完成</div><h3>全部異宇宙已征服</h3><div class="muted">1000 / 1000 深度・200 / 200 宇宙</div><div class="au-note">已完成所有正式異宇宙 progression。之後仍可自由進行無收益回顧戰。</div></section>`;
  const depth=whole(snap?.nextDepth,0),info=depthInfo(depth),base=baseStats(depth),failure=failureStatus(depth),attempt=activeAttempt();
  if(!depth||!info)return `<section class="au-card"><h3>異宇宙前線資料尚未載入</h3></section>`;
  const currentEncounter=attempt&&attempt.depth===depth&&typeof window.alternateUniverseCurrentAttemptEncounter==="function"?window.alternateUniverseCurrentAttemptEncounter(currentState()):null;
  const locked=failure?.locked===true;
  const failureText=locked?`本輪已達 ${whole(failure.failures,10)} / ${whole(failure.limit,10)} 敗，完成下一次轉生後解除鎖定。`:`本輪失敗 ${whole(failure?.failures,0)} / ${whole(failure?.limit,10)}；距鎖定尚餘 ${whole(failure?.failuresRemainingBeforeLock,10)} 敗。`;
  return `<section class="au-card ${locked?"au-warning":""}"><div class="au-card-head"><div><div class="au-kicker">目前正式前線</div><h3>${infoTitle(info)}</h3><div class="muted">第 ${fmt(info.universeNumber)} 宇宙・${esc(info.culture||"")}</div></div><span class="au-stage">${esc(info.stageName||info.stageLabel||"")}</span></div>${statsHtml(currentEncounter||base)}<div class="au-note">基礎暴擊 20%／閃避 20%；建立本次挑戰後固定抽取兩個既有怪物特性，F5 不重抽。</div><div class="au-note">${esc(failureText)}</div>${attempt&&attempt.depth===depth?`<h4>本次固定特性</h4>${traitHtml(attempt.traits)}<div class="au-actions"><button class="btn primary" onclick="fightAlternateUniverseFormal()">開始戰鬥</button><button class="btn danger" onclick="abandonAlternateUniverseFormal()">放棄挑戰</button></div>`:locked?"":`<div class="au-actions"><button class="btn primary" onclick="prepareAlternateUniverseFormal()">建立本次挑戰</button></div>`}</section>`;
 }
 function reviewHtml(snap){if(!snap?.unlocked||whole(snap.deepestCleared,0)<1)return "";const max=whole(snap.deepestCleared,0);return `<section class="au-card"><div class="au-kicker">回顧戰</div><h3>重打已征服 U</h3><div class="au-review-row"><label>回顧深度 U<input id="alternateUniverseReviewDepth" type="number" min="1" max="${max}" value="${max}"></label><button class="btn" onclick="fightAlternateUniverseReview()">開始回顧戰</button></div><div class="au-note">每次回顧戰臨時重新抽兩個 traits；不寫 activeAttempt、不計 failure、不改 progression，也沒有任何收益。</div></section>`;}
 function pageHtml(){const snap=progress();if(!snap?.unlocked)return `<div class="function-page"><div class="back-home"><button class="btn back-btn" onclick="go('home')">← 返回主頁</button></div><section class="au-card"><h3>異宇宙尚未解鎖</h3></section></div>`;return `<div class="function-page"><div class="back-home"><button class="btn back-btn" onclick="go('home')">← 返回主頁</button></div><section class="au-shell"><section class="au-hero"><div class="au-kicker">Alternate Universe</div><h2>異宇宙</h2><div class="muted">200 個宇宙 × 5 深度，共 1000U。正式勝利只推進征服進度，不提供 EXP、資源或裝備。</div>${progressHtml(snap)}</section>${resultHtml()}${frontierHtml(snap)}${reviewHtml(snap)}</section></div>`;}
 function renderPage(){ensureStyles();const main=document.getElementById("main");if(main)main.innerHTML=pageHtml();return !!main;}
 function prepareFormal(){const snap=progress();if(!snap?.nextDepth)return false;const result=typeof window.beginAlternateUniverseAttempt==="function"?window.beginAlternateUniverseAttempt(snap.nextDepth):{ok:false,reason:"attempt-owner-missing"};if(!result?.ok){alert(result?.reason==="depth-locked-for-life"?"本輪此深度已鎖定，完成下一次轉生後可再次挑戰。":"無法建立異宇宙挑戰，請重新整理後再試。");return false;}lastBattleReport=null;renderPage();return true;}
 function fightFormal(){const attempt=activeAttempt();if(!attempt)return false;const result=typeof window.runAndSettleAlternateUniverseCombat==="function"?window.runAndSettleAlternateUniverseCombat({logs:true}):{ok:false};if(!result?.ok){alert("異宇宙戰鬥未能完成正式結算，請重新整理後再試。");return false;}const combatResult=result.combatResult||null;lastBattleReport={review:false,depth:attempt.depth,traits:Array.from(attempt.traits||[]),result:combatResult||result};renderPage();return true;}
 function abandonFormal(){const attempt=activeAttempt();if(!attempt)return false;if(!confirm("放棄尚未結算的異宇宙挑戰會記 1 次失敗。確定放棄？"))return false;const result=typeof window.abandonAlternateUniverseAttempt==="function"?window.abandonAlternateUniverseAttempt({attemptId:attempt.attemptId}):{ok:false};if(!result?.ok){alert("無法放棄本次挑戰，請重新整理後再試。");return false;}lastBattleReport=null;renderPage();return true;}
 function fightReview(){const input=document.getElementById("alternateUniverseReviewDepth"),depth=whole(input?.value,0),access=typeof window.alternateUniverseReviewAccess==="function"?window.alternateUniverseReviewAccess(depth,currentState()):{ok:false};if(!access?.ok){alert("只能回顧已征服的異宇宙深度。");return false;}const result=typeof window.runAlternateUniverseCombat==="function"?window.runAlternateUniverseCombat({review:true,depth,logs:true}):{ok:false};if(!result?.ok){alert("回顧戰建立失敗，請重新整理後再試。");return false;}lastBattleReport={review:true,depth,traits:Array.from(result.traits||[]),result};renderPage();return true;}
 function install(){ensureStyles();installHomeBridge();try{if(typeof view!=="undefined"&&view==="home"&&typeof render==="function")setTimeout(()=>render(),0);}catch(_){}return true;}
 window.ALTERNATE_UNIVERSE_PLAYER_UI_VERSION=ALTERNATE_UNIVERSE_PLAYER_UI_VERSION;
 window.alternateUniverseHomeEntryHtml=homeEntryHtml;
 window.alternateUniversePageHtml=pageHtml;
 window.renderAlternateUniversePage=renderPage;
 window.openAlternateUniversePage=openPage;
 window.prepareAlternateUniverseFormal=prepareFormal;
 window.fightAlternateUniverseFormal=fightFormal;
 window.abandonAlternateUniverseFormal=abandonFormal;
 window.fightAlternateUniverseReview=fightReview;
 install();
})();
