(function(){
 function arenaWorld(){return Number(window.arenaWorldForState(state))===2?2:1;}
 function maxArenaRank(world=arenaWorld()){return Math.max(1,Math.floor(Number(window.getArenaMaxRankForWorld(Number(world)===2?2:1))||1));}
 function clampRank(value,world=arenaWorld()){return Math.max(1,Math.min(maxArenaRank(world),Math.floor(Number(value)||1)));}
 function arenaRegion(rank,world=arenaWorld()){const w=Number(world)===2?2:1,r=clampRank(rank,w);return window.getArenaRegionForWorld(w,r);}
 function arenaVenueName(rank,world=arenaWorld()){const w=Number(world)===2?2:1,r=clampRank(rank,w);return `${window.getArenaRegionNameForWorld(w,r)}競技場`;}
 function arenaState(world=arenaWorld()){return window.getArenaProgressForWorld(Number(world)===2?2:1,state);}
 function regionUnlockedCap(world=arenaWorld()){const w=Number(world)===2?2:1;return clampRank(window.getArenaRankCapForWorld(w,state),w);}
 function progressState(world=arenaWorld()){
  const w=Number(world)===2?2:1,arena=arenaState(w),max=maxArenaRank(w),highest=clampRank(arena?.highestArenaUnlocked||1,w),start=Math.max(1,highest-2),visible=[];
  for(let rank=start;rank<=highest;rank++)visible.push(rank);
  const nextRank=highest<max?highest+1:null,cap=regionUnlockedCap(w),combatReady=arena?.promotionReady===true,regionReady=nextRank==null?true:nextRank<=cap;
  return {world:w,highestArenaUnlocked:highest,windowStart:start,windowEnd:highest,assessmentRank:highest,assessmentName:arenaVenueName(highest,w),visibleRanks:visible,visibleArenas:visible.map(rank=>({rank,name:arenaVenueName(rank,w)})),nextRank,nextName:nextRank==null?null:arenaVenueName(nextRank,w),unlockedCap:cap,combatReady,regionReady,canPromote:nextRank!=null&&combatReady&&regionReady,canUnlockNext:nextRank!=null&&combatReady&&regionReady,atFinalWindow:nextRank==null,maxRank:max};
 }
 function selectVisibleRank(rank){const world=arenaWorld(),arena=arenaState(world),p=progressState(world),r=clampRank(rank,world);if(!arena||!p.visibleRanks.includes(r))return false;arena.activeRank=r;arena.rank=r;return true;}
 function clearActiveRank(){const world=arenaWorld(),arena=arenaState(world);if(!arena)return;const p=progressState(world);arena.activeRank=null;arena.rank=p.assessmentRank;}
 window.promoteArenaRank=function(){const world=arenaWorld(),arena=arenaState(world),p=progressState(world),assessment=typeof window.getArenaAssessmentStatus==="function"?window.getArenaAssessmentStatus():null;if(!arena||p.atFinalWindow)return {ok:false,reason:"max-arena",...(assessment||{})};if(!p.combatReady)return {ok:false,reason:"combat-not-qualified",...(assessment||{})};if(!p.regionReady)return {ok:false,reason:"region-locked",...(assessment||{})};arena.highestArenaUnlocked=clampRank(p.highestArenaUnlocked+1,world);arena.activeRank=null;arena.rank=arena.highestArenaUnlocked;arena.promotionReady=false;arena.lastCheckSignature=null;arena.lastCheckRuns=0;arena.lastCheckClearCount=0;save(false);if(view==="dungeon-arena"&&typeof openArenaDungeon==="function")openArenaDungeon();else if(typeof render==="function")render();const nextAssessment=typeof window.getArenaAssessmentStatus==="function"?window.getArenaAssessmentStatus():null;return {ok:true,...(nextAssessment||{})};};
 window.SECOND_WORLD_ARENA_PROGRESS_RULES_VERSION=3;window.ARENA_VENUE_WORLD_NAME_VERSION=4;window.ARENA_WINDOW_WORLD_OWNER_VERSION=3;window.ARENA_SECOND_WORLD_REGION_OWNER_VERSION=2;window.getArenaWindowState=progressState;window.getArenaProgressState=progressState;window.getArenaVisibleRanks=function(){return progressState().visibleRanks.slice();};window.getArenaAssessmentRank=function(){return progressState().assessmentRank;};window.getArenaHighestUnlocked=function(){return progressState().highestArenaUnlocked;};window.getArenaVenueName=arenaVenueName;window.getArenaVenueNameForWorld=arenaVenueName;window.isArenaRankVisible=function(rank){const p=progressState();return p.visibleRanks.includes(clampRank(rank,p.world));};window.selectArenaVenueRank=selectVisibleRank;window.clearArenaVenueSelection=clearActiveRank;
})();