(function(){
 const ARENA_COMPATIBILITY_PROFILE=Object.freeze({positionModelVersion:1,assessmentRuleVersion:4,assessmentStateVersion:4,assessmentRuntimeVersion:4,balanceVersion:6,rankBalanceVersion:3,positionApiVersion:1,enemyProfileVersion:1,pacingSourceVersion:1});
 const ARENA_POSITION_MODEL_VERSION=ARENA_COMPATIBILITY_PROFILE.positionModelVersion,ARENA_ASSESSMENT_RULE_VERSION=ARENA_COMPATIBILITY_PROFILE.assessmentRuleVersion,ARENA_BALANCE_COMPAT_VERSION=ARENA_COMPATIBILITY_PROFILE.balanceVersion,ARENA_ASSESS_RUNS=500,ARENA_ASSESS_CLEAR_TARGET=485;
 function finiteNonNegative(value,fallback=0){const n=Number(value);return Number.isFinite(n)&&n>=0?n:fallback;}
 function isObject(value){return !!value&&typeof value==="object"&&!Array.isArray(value);}
 function arenaWorldForState(target){return target?.secondWorld?.entered===true?2:1;}
 function firstWorldRegions(){return Array.isArray(WORLD_REGIONS)?WORLD_REGIONS:[];}
 function secondWorldRegions(){return Array.isArray(window.SECOND_WORLD_REGIONS)?window.SECOND_WORLD_REGIONS:[];}
 function arenaRegionsForWorld(world){return Number(world)===2?secondWorldRegions():firstWorldRegions();}
 function arenaRegionForWorld(world,rank){const w=Number(world)===2?2:1,regions=arenaRegionsForWorld(w),max=Math.max(1,regions.length||1),r=Math.max(1,Math.min(max,Math.floor(Number(rank)||1));if(w===2&&typeof window.secondWorldRegion==="function")return window.secondWorldRegion(r-1);return regions[r-1]||null;}
 function unlockedArenaRankCap(target){const regions=firstWorldRegions();if(!regions.length)return 1;const unlockedMap=Math.max(0,Math.floor(Number(target?.unlockedMap)||0));const unlockedRegions=regions.filter(region=>unlockedMap>=Math.max(0,Math.floor(Number(region?.mapStart)||0))).length;return Math.max(1,Math.min(regions.length,unlockedRegions||1));}
 function blankArenaProgress(){return {};}
 function arenaMaxRankForWorld(world){const regions=arenaRegionsForWorld(world);return Math.max(1,regions.length||1);}
 function secondWorldArenaRegionCap(target){if(arenaWorldForState(target)!==2)return 1;const regions=secondWorldRegions(),max=Math.max(1,regions.length||1);if(typeof window.secondWorldRegionVisible!=="function")return 1;let count=0;for(let i=0;i<max;i++){if(window.secondWorldRegionVisible(i,target))count=i+1;else break;}return Math.max(1,Math.min(max,count||1));}
 function arenaRankCapForWorld(target,world){return Number(world)===2?secondWorldArenaRegionCap(target):Math.max(1,Math.min(arenaMaxRankForWorld(1),unlockedArenaRankCap(target)));}
 function normalizeArenaProfile(source,target,world){
  const row=isObject(source)?source:blankArenaProgress(),maxRank=arenaMaxRankForWorld(world),cap=Math.max(1,Math.min(maxRank,arenaRankCapForWorld(target,world)));
  const hasHighest=Number.isFinite(Number(row.highestArenaUnlocked))&&Number(row.highestArenaUnlocked)>=1,hasWindowStart=Number.isFinite(Number(row.windowStart))&&Number(row.windowStart)>=1,legacyRank=Math.max(1,Math.min(maxRank,Math.floor(Number(row.rank)||1)));
  const positionModelCompatible=Math.floor(Number(row.positionModelVersion)||0)===ARENA_POSITION_MODEL_VERSION,assessmentRuleCompatible=Math.floor(Number(row.assessmentRuleVersion)||0)===ARENA_ASSESSMENT_RULE_VERSION,balanceCompatible=Math.floor(Number(row.balanceVersion)||0)===ARENA_BALANCE_COMPAT_VERSION;
  let highestArenaUnlocked,assessmentCompatible=false;if(hasHighest){highestArenaUnlocked=Math.floor(Number(row.highestArenaUnlocked));assessmentCompatible=positionModelCompatible&&assessmentRuleCompatible&&balanceCompatible;}else if(hasWindowStart)highestArenaUnlocked=Math.floor(Number(row.windowStart));else highestArenaUnlocked=legacyRank;
  highestArenaUnlocked=Math.max(1,Math.min(maxRank,cap,highestArenaUnlocked));const visibleStart=Math.max(1,highestArenaUnlocked-2),activeRaw=Math.floor(Number(row.activeRank)||0),activeRank=activeRaw>=visibleStart&&activeRaw<=highestArenaUnlocked?activeRaw:null;
  const runs=assessmentCompatible?Math.max(0,Math.min(ARENA_ASSESS_RUNS,Math.floor(Number(row.lastCheckRuns)||0))):0,clears=assessmentCompatible?Math.max(0,Math.min(runs,Math.floor(Number(row.lastCheckClearCount)||0))):0,signature=assessmentCompatible&&typeof row.lastCheckSignature==="string"&&row.lastCheckSignature?row.lastCheckSignature:null,promotionReady=!!signature&&runs===ARENA_ASSESS_RUNS&&clears>=ARENA_ASSESS_CLEAR_TARGET;
  const normalized={positionModelVersion:ARENA_POSITION_MODEL_VERSION,assessmentRuleVersion:ARENA_ASSESSMENT_RULE_VERSION,balanceVersion:ARENA_BALANCE_COMPAT_VERSION,highestArenaUnlocked,activeRank,rank:activeRank||highestArenaUnlocked,promotionReady,lastCheckSignature:signature,lastCheckRuns:runs,lastCheckClearCount:clears};Object.keys(row).forEach(key=>{if(!(key in normalized))delete row[key];});Object.assign(row,normalized);return row;
 }
 function normalizeArenaProgress(dungeon,target){
  const legacyArena=isObject(dungeon.arena)?dungeon.arena:null;
  if(!isObject(dungeon.arenaByWorld))dungeon.arenaByWorld={};
  if(!isObject(dungeon.arenaByWorld[1]))dungeon.arenaByWorld[1]=legacyArena||blankArenaProgress();
  if(!isObject(dungeon.arenaByWorld[2]))dungeon.arenaByWorld[2]=blankArenaProgress();
  normalizeArenaProfile(dungeon.arenaByWorld[1],target,1);normalizeArenaProfile(dungeon.arenaByWorld[2],target,2);
  try{delete dungeon.arena;}catch(e){}
  Object.defineProperty(dungeon,"arena",{configurable:true,enumerable:false,get(){return dungeon.arenaByWorld[arenaWorldForState(target)]||dungeon.arenaByWorld[1];},set(value){const world=arenaWorldForState(target);dungeon.arenaByWorld[world]=normalizeArenaProfile(value,target,world);}});
  return dungeon.arenaByWorld;
 }
 function arenaProgressForWorld(target,world=null){if(!isObject(target))return null;if(!isObject(target.dungeon))target.dungeon={};normalizeArenaProgress(target.dungeon,target);const key=Number(world)===2?2:Number(world)===1?1:arenaWorldForState(target);return target.dungeon.arenaByWorld[key];}
 window.ARENA_ASSESSMENT_STATE_VERSION=ARENA_COMPATIBILITY_PROFILE.assessmentStateVersion;window.getArenaVersionProfile=function(){return {...ARENA_COMPATIBILITY_PROFILE};};window.getArenaAssessmentCompatibilityVersions=function(){const v=window.getArenaVersionProfile();return {positionModelVersion:v.positionModelVersion,assessmentRuleVersion:v.assessmentRuleVersion,balanceVersion:v.balanceVersion};};window.unlockedArenaRankCapForState=unlockedArenaRankCap;
 window.ARENA_BY_WORLD_STATE_VERSION=2;window.ARENA_BY_WORLD_COMPAT_ALIAS_VERSION=2;window.ARENA_WORLD_OWNER_VERSION=2;window.ARENA_REGION_OWNER_VERSION=2;window.arenaWorldForState=arenaWorldForState;window.getArenaRegionsForWorld=function(world){return arenaRegionsForWorld(world).slice();};window.getArenaRegionForWorld=arenaRegionForWorld;window.getArenaRegionNameForWorld=function(world,rank){const region=arenaRegionForWorld(world,rank);return region?.name||`第${Math.max(1,Math.floor(Number(rank)||1))}區`;};window.normalizeArenaProgressByWorld=normalizeArenaProgress;window.getArenaProgressForWorld=function(world,target=null){const s=isObject(target)?target:(typeof state!=="undefined"?state:null);return arenaProgressForWorld(s,world);};window.getCurrentArenaProgress=function(target=null){const s=isObject(target)?target:(typeof state!=="undefined"?state:null);return arenaProgressForWorld(s,null);};window.SECOND_WORLD_ARENA_UNLOCK_VERSION=2;window.getArenaMaxRankForWorld=arenaMaxRankForWorld;window.getArenaRankCapForWorld=function(world,target=null){const s=isObject(target)?target:(typeof state!=="undefined"?state:null);return arenaRankCapForWorld(s,world);};window.getSecondWorldArenaRegionCap=function(target=null){const s=isObject(target)?target:(typeof state!=="undefined"?state:null);return secondWorldArenaRegionCap(s);};window.ARENA_ASSESS_RUNS=ARENA_ASSESS_RUNS;window.ARENA_ASSESS_CLEAR_TARGET=ARENA_ASSESS_CLEAR_TARGET;
 function normalizeDungeonState(target,options={}){if(!isObject(target))return null;if(!isObject(target.dungeon))target.dungeon={};const dungeon=target.dungeon;normalizeArenaProgress(dungeon,target);if(typeof window.normalizeMirrorDungeonState==="function")window.normalizeMirrorDungeonState(target,options?.timestamp??Date.now(),options?.mirrorOptions||{});return dungeon;}window.normalizeDungeonSaveState=normalizeDungeonState;window.DUNGEON_RUNTIME_NORMALIZATION_VERSION=2;window.DUNGEON_LEGACY_CLEANUP_OWNER="savemigration";
 function initializeVipHpIfNeeded(){if(!state||state.vipInitialized===true)return false;const baseMax=Math.max(1,equippedStats().hp),current=Math.max(0,Number(state.hp)||0),ratio=Math.max(0,Math.min(1,current/baseMax)),vipMax=Math.max(1,playerCombatStats().hp);state.hp=current>=baseMax?vipMax:Math.max(0,Math.min(vipMax,Math.round(vipMax*ratio)));state.vipInitialized=true;return true;}function normalizeFreshDungeonState(target){normalizeDungeonState(target);target.vipInitialized=true;return target;}if(typeof registerNewStateNormalizer==="function")registerNewStateNormalizer(normalizeFreshDungeonState);
 window.finalizeDungeonLoadedState=function(){const vipHpInitialized=initializeVipHpIfNeeded(),beforeMirrorStatus=state?.dungeon?.mirror?.daily?.status;normalizeDungeonState(state,{timestamp:Date.now(),mirrorOptions:{recoverInterrupted:true}});const afterMirrorStatus=state?.dungeon?.mirror?.daily?.status;state.saveVersion=typeof currentSaveVersion==="function"?currentSaveVersion():SAVE_VERSION;return {vipHpInitialized,recoveredInterruptedRun:false,recoveredInterruptedMirrorRun:beforeMirrorStatus==="running"&&afterMirrorStatus!=="running",dungeon:state.dungeon};};window.ensureDungeonState=function(){return normalizeDungeonState(state);};window.ensureDungeonProgressState=window.ensureDungeonState;
 window.addDungeonPoints=function(amount){const baseAdded=Math.floor(finiteNonNegative(amount,0)),multiplier=typeof vipDungeonPointMultiplier==="function"?vipDungeonPointMultiplier():1,adjusted=typeof adjustVipDungeonPoints==="function"?adjustVipDungeonPoints(baseAdded):Math.floor(baseAdded*multiplier),result=typeof addVipPoints==="function"?addVipPoints(adjusted):{added:adjusted,points:(state.vipPoints||0)+adjusted};state.vipPoints=Math.floor(finiteNonNegative(result.points,0));return {added:result.added??adjusted,baseAdded,points:state.vipPoints,multiplier,vipLevel:state.vipLevel||0,levelsGained:result.levelsGained||0};};
})();