(function(){
 const ARENA_COMPATIBILITY_PROFILE=Object.freeze({positionModelVersion:1,assessmentRuleVersion:4,assessmentStateVersion:4,assessmentRuntimeVersion:4,balanceVersion:7,rankBalanceVersion:4,positionApiVersion:1,enemyProfileVersion:1,pacingSourceVersion:1});
 const ARENA_POSITION_MODEL_VERSION=ARENA_COMPATIBILITY_PROFILE.positionModelVersion,ARENA_ASSESSMENT_RULE_VERSION=ARENA_COMPATIBILITY_PROFILE.assessmentRuleVersion,ARENA_BALANCE_COMPAT_VERSION=ARENA_COMPATIBILITY_PROFILE.balanceVersion,ARENA_ASSESS_RUNS=500,ARENA_ASSESS_CLEAR_TARGET=485;
 const W3_ARENA_TRANSACTION_KEY="thirdWorldArenaTransaction",W3_ARENA_TRANSACTION_VERSION=1,W3_ARENA_SAVE_CLEANUP_VERSION=1,W3_ARENA_TRANSACTION_NORMALIZATION_VERSION=1,W3_ARENA_RETIRED_RANK_CLEANUP_VERSION=1,W3_ARENA_RUN_CHOICES=Object.freeze([1,5,10,20]);
 function finiteNonNegative(value,fallback=0){const n=Number(value);return Number.isFinite(n)&&n>=0?n:fallback;}
 function isObject(value){return !!value&&typeof value==="object"&&!Array.isArray(value);}
 function whole(value,fallback=0){const n=Math.floor(Number(value));return Number.isFinite(n)?n:fallback;}
 function arenaWorldForState(target){if(target?.thirdWorld?.entered===true)return 3;return target?.secondWorld?.entered===true?2:1;}
 function firstWorldRegions(){return Array.isArray(WORLD_REGIONS)?WORLD_REGIONS:[];}
 function secondWorldRegions(){return Array.isArray(window.SECOND_WORLD_REGIONS)?window.SECOND_WORLD_REGIONS:[];}
 function arenaRegionsForWorld(world){const w=Number(world);if(w===3)return [];return w===2?secondWorldRegions():firstWorldRegions();}
 function arenaRegionForWorld(world,rank){const requested=Number(world);if(requested===3)return null;const w=requested===2?2:1,regions=arenaRegionsForWorld(w),max=Math.max(1,regions.length||1),r=Math.max(1,Math.min(max,Math.floor(Number(rank)||1)));if(w===2&&typeof window.secondWorldRegion==="function")return window.secondWorldRegion(r-1);return regions[r-1]||null;}
 function unlockedArenaRankCap(target){const regions=firstWorldRegions();if(!regions.length)return 1;const unlockedMap=Math.max(0,Math.floor(Number(target?.unlockedMap)||0));const unlockedRegions=regions.filter(region=>unlockedMap>=Math.max(0,Math.floor(Number(region?.mapStart)||0))).length;return Math.max(1,Math.min(regions.length,unlockedRegions||1));}
 function blankArenaProgress(){return {};}
 function arenaMaxRankForWorld(world){if(Number(world)===3)return 0;const regions=arenaRegionsForWorld(world);return Math.max(1,regions.length||1);}
 function secondWorldArenaRegionCap(target){if(target?.secondWorld?.entered!==true)return 1;const regions=secondWorldRegions(),max=Math.max(1,regions.length||1),eligible=typeof window.secondWorldArenaRegionEligible==="function"?window.secondWorldArenaRegionEligible:window.secondWorldRegionVisible;if(typeof eligible!=="function")return 1;let count=0;for(let i=0;i<max;i++){if(eligible(i,target))count=i+1;else break;}return Math.max(1,Math.min(max,count||1));}
 function arenaRankCapForWorld(target,world){if(Number(world)===3)return 0;return Number(world)===2?secondWorldArenaRegionCap(target):Math.max(1,Math.min(arenaMaxRankForWorld(1),unlockedArenaRankCap(target)));}
 function normalizeArenaProfile(source,target,world){
  const row=isObject(source)?source:blankArenaProgress(),maxRank=arenaMaxRankForWorld(world),cap=Math.max(1,Math.min(maxRank,arenaRankCapForWorld(target,world)));
  const hasHighest=Number.isFinite(Number(row.highestArenaUnlocked))&&Number(row.highestArenaUnlocked)>=1,hasWindowStart=Number.isFinite(Number(row.windowStart))&&Number(row.windowStart)>=1,legacyRank=Math.max(1,Math.min(maxRank,Math.floor(Number(row.rank)||1)));
  const positionModelCompatible=Math.floor(Number(row.positionModelVersion)||0)===ARENA_POSITION_MODEL_VERSION,assessmentRuleCompatible=Math.floor(Number(row.assessmentRuleVersion)||0)===ARENA_ASSESSMENT_RULE_VERSION,balanceCompatible=Math.floor(Number(row.balanceVersion)||0)===ARENA_BALANCE_COMPAT_VERSION;
  let highestArenaUnlocked,assessmentCompatible=false;if(hasHighest){highestArenaUnlocked=Math.floor(Number(row.highestArenaUnlocked));assessmentCompatible=positionModelCompatible&&assessmentRuleCompatible&&balanceCompatible;}else if(hasWindowStart)highestArenaUnlocked=Math.floor(Number(row.windowStart));else highestArenaUnlocked=legacyRank;
  highestArenaUnlocked=Math.max(1,Math.min(maxRank,cap,highestArenaUnlocked));const visibleStart=Math.max(1,highestArenaUnlocked-2),activeRaw=Math.floor(Number(row.activeRank)||0),activeRank=activeRaw>=visibleStart&&activeRaw<=highestArenaUnlocked?activeRaw:null;
  const runs=assessmentCompatible?Math.max(0,Math.min(ARENA_ASSESS_RUNS,Math.floor(Number(row.lastCheckRuns)||0))):0,clears=assessmentCompatible?Math.max(0,Math.min(runs,Math.floor(Number(row.lastCheckClearCount)||0))):0,signature=assessmentCompatible&&typeof row.lastCheckSignature==="string"&&row.lastCheckSignature?row.lastCheckSignature:null,promotionReady=!!signature&&runs===ARENA_ASSESS_RUNS&&clears>=ARENA_ASSESS_CLEAR_TARGET;
  const normalized={positionModelVersion:ARENA_POSITION_MODEL_VERSION,assessmentRuleVersion:ARENA_ASSESSMENT_RULE_VERSION,balanceVersion:ARENA_BALANCE_COMPAT_VERSION,highestArenaUnlocked,activeRank,rank:activeRank||highestArenaUnlocked,promotionReady,lastCheckSignature:signature,lastCheckRuns:runs,lastCheckClearCount:clears};Object.keys(row).forEach(key=>{if(!(key in normalized))delete row[key];});Object.assign(row,normalized);return row;
 }
 function cleanupRetiredWorld3ArenaRank(dungeon){if(!isObject(dungeon?.arenaByWorld)||!Object.prototype.hasOwnProperty.call(dungeon.arenaByWorld,"3"))return false;delete dungeon.arenaByWorld[3];return true;}
 function normalizeArenaProgress(dungeon,target){
  const legacyArena=isObject(dungeon.arena)?dungeon.arena:null;
  if(!isObject(dungeon.arenaByWorld))dungeon.arenaByWorld={};
  const retiredWorld3RankRemoved=cleanupRetiredWorld3ArenaRank(dungeon);
  if(!isObject(dungeon.arenaByWorld[1]))dungeon.arenaByWorld[1]=legacyArena||blankArenaProgress();
  if(!isObject(dungeon.arenaByWorld[2]))dungeon.arenaByWorld[2]=blankArenaProgress();
  normalizeArenaProfile(dungeon.arenaByWorld[1],target,1);normalizeArenaProfile(dungeon.arenaByWorld[2],target,2);
  try{delete dungeon.arena;}catch(e){}
  Object.defineProperty(dungeon,"arena",{configurable:true,enumerable:false,get(){const world=arenaWorldForState(target),compatWorld=world===1?1:2;return dungeon.arenaByWorld[compatWorld]||dungeon.arenaByWorld[1];},set(value){const world=arenaWorldForState(target),compatWorld=world===1?1:2;dungeon.arenaByWorld[compatWorld]=normalizeArenaProfile(value,target,compatWorld);}});
  return {arenaByWorld:dungeon.arenaByWorld,retiredWorld3RankRemoved};
 }
 function validBossIdsForMode(mode,bossIds){if(!Array.isArray(bossIds)||bossIds.length!==3||bossIds.some(id=>typeof id!=="string"||!id))return false;return mode==="fixed"?new Set(bossIds).size===1:mode==="varied"?new Set(bossIds).size===3:false;}
 function normalizeThirdWorldArenaTransaction(target){
  if(!isObject(target)){return {action:"none",reason:"no-state"};}if(!isObject(target.dungeon))target.dungeon={};const dungeon=target.dungeon;
  if(!Object.prototype.hasOwnProperty.call(dungeon,W3_ARENA_TRANSACTION_KEY))return {action:"none",reason:"missing"};
  const raw=dungeon[W3_ARENA_TRANSACTION_KEY],remove=reason=>{delete dungeon[W3_ARENA_TRANSACTION_KEY];return {action:"removed",reason};};
  if(target?.thirdWorld?.entered!==true)return remove("not-world3");if(!isObject(raw))return remove("not-object");
  const version=whole(raw.version,0),status=String(raw.status||""),mode=String(raw.mode||""),requestedRuns=whole(raw.requestedRuns,0),runIndex=whole(raw.runIndex,-1),stageIndex=whole(raw.stageIndex,-1),bossIds=Array.isArray(raw.bossIds)?raw.bossIds.map(id=>String(id||"")):[],dailyUsedBefore=whole(raw.dailyUsedBefore,-1),dailyUsedAfter=whole(raw.dailyUsedAfter,-1),dateKey=String(raw.dateKey||""),startedAt=Number(raw.startedAt),currentDateKey=String(target?.daily?.dateKey||"");
  if(version!==W3_ARENA_TRANSACTION_VERSION)return remove("unsupported-version");if(status!=="active")return remove("inactive-status");if(!W3_ARENA_RUN_CHOICES.includes(requestedRuns)||runIndex<0||runIndex>=requestedRuns||stageIndex<0||stageIndex>2)return remove("invalid-run-shape");if(!validBossIdsForMode(mode,bossIds))return remove("invalid-lineup");if(dailyUsedBefore<0||dailyUsedBefore>19||dailyUsedAfter!==dailyUsedBefore+1||dailyUsedAfter>20)return remove("invalid-daily-use");if(!Number.isFinite(startedAt)||startedAt<=0)return remove("invalid-start-time");if(dateKey&&currentDateKey&&dateKey!==currentDateKey)return remove("stale-date");
  const normalized={version:W3_ARENA_TRANSACTION_VERSION,status:"active",mode,runIndex,requestedRuns,stageIndex,bossIds,dailyUsedBefore,dailyUsedAfter,dateKey,startedAt};const currentHp=Number(raw.currentHp),updatedAt=Number(raw.updatedAt);if(Number.isFinite(currentHp)&&currentHp>=0)normalized.currentHp=Math.floor(currentHp);if(Number.isFinite(updatedAt)&&updatedAt>0)normalized.updatedAt=updatedAt;dungeon[W3_ARENA_TRANSACTION_KEY]=normalized;return {action:"preserved",reason:"valid",transaction:{...normalized,bossIds:bossIds.slice()}};
 }
 function arenaProgressForWorld(target,world=null){if(!isObject(target))return null;if(!isObject(target.dungeon))target.dungeon={};normalizeArenaProgress(target.dungeon,target);const requested=world==null?arenaWorldForState(target):Number(world);if(requested===3)return null;const key=requested===2?2:1;return target.dungeon.arenaByWorld[key];}
 window.ARENA_ASSESSMENT_STATE_VERSION=ARENA_COMPATIBILITY_PROFILE.assessmentStateVersion;window.getArenaVersionProfile=function(){return {...ARENA_COMPATIBILITY_PROFILE};};window.getArenaAssessmentCompatibilityVersions=function(){const v=window.getArenaVersionProfile();return {positionModelVersion:v.positionModelVersion,assessmentRuleVersion:v.assessmentRuleVersion,balanceVersion:v.balanceVersion};};window.unlockedArenaRankCapForState=unlockedArenaRankCap;
 window.ARENA_BY_WORLD_STATE_VERSION=2;window.ARENA_BY_WORLD_COMPAT_ALIAS_VERSION=2;window.ARENA_WORLD_OWNER_VERSION=3;window.ARENA_REGION_OWNER_VERSION=3;window.THIRD_WORLD_ARENA_NO_RANK_VERSION=1;window.THIRD_WORLD_ARENA_SAVE_CLEANUP_VERSION=W3_ARENA_SAVE_CLEANUP_VERSION;window.THIRD_WORLD_ARENA_TRANSACTION_NORMALIZATION_VERSION=W3_ARENA_TRANSACTION_NORMALIZATION_VERSION;window.THIRD_WORLD_ARENA_RETIRED_RANK_CLEANUP_VERSION=W3_ARENA_RETIRED_RANK_CLEANUP_VERSION;window.arenaWorldForState=arenaWorldForState;window.getArenaRegionsForWorld=function(world){return arenaRegionsForWorld(world).slice();};window.getArenaRegionForWorld=arenaRegionForWorld;window.getArenaRegionNameForWorld=function(world,rank){if(Number(world)===3)return "";const region=arenaRegionForWorld(world,rank);return region?.name||`第${Math.max(1,Math.floor(Number(rank)||1))}區`;};window.normalizeArenaProgressByWorld=normalizeArenaProgress;window.normalizeThirdWorldArenaTransaction=normalizeThirdWorldArenaTransaction;window.getArenaProgressForWorld=function(world,target=null){const s=isObject(target)?target:(typeof state!=="undefined"?state:null);return arenaProgressForWorld(s,world);};window.getCurrentArenaProgress=function(target=null){const s=isObject(target)?target:(typeof state!=="undefined"?state:null);return arenaProgressForWorld(s,null);};window.SECOND_WORLD_ARENA_UNLOCK_VERSION=2;window.getArenaMaxRankForWorld=arenaMaxRankForWorld;window.getArenaRankCapForWorld=function(world,target=null){const s=isObject(target)?target:(typeof state!=="undefined"?state:null);return arenaRankCapForWorld(s,world);};window.getSecondWorldArenaRegionCap=function(target=null){const s=isObject(target)?target:(typeof state!=="undefined"?state:null);return secondWorldArenaRegionCap(s);};window.ARENA_ASSESS_RUNS=ARENA_ASSESS_RUNS;window.ARENA_ASSESS_CLEAR_TARGET=ARENA_ASSESS_CLEAR_TARGET;
 function normalizeDungeonState(target,options={}){if(!isObject(target))return null;if(!isObject(target.dungeon))target.dungeon={};const dungeon=target.dungeon,arenaReport=normalizeArenaProgress(dungeon,target),transactionReport=normalizeThirdWorldArenaTransaction(target);if(typeof window.normalizeMirrorDungeonState==="function")window.normalizeMirrorDungeonState(target,options?.timestamp??Date.now(),options?.mirrorOptions||{});window.LAST_DUNGEON_NORMALIZATION_REPORT={version:3,retiredWorld3ArenaRankRemoved:arenaReport.retiredWorld3RankRemoved===true,thirdWorldArenaTransactionAction:transactionReport.action,thirdWorldArenaTransactionReason:transactionReport.reason};return dungeon;}window.normalizeDungeonSaveState=normalizeDungeonState;window.DUNGEON_RUNTIME_NORMALIZATION_VERSION=3;window.DUNGEON_LEGACY_CLEANUP_OWNER="savemigration";
 function runDungeonStateMigrationRegression(){const errors=[],cases=[];const run=(id,target,check)=>{try{normalizeDungeonState(target,{timestamp:1700000000000});const ok=check(target,window.LAST_DUNGEON_NORMALIZATION_REPORT)===true;cases.push({id,ok,report:{...window.LAST_DUNGEON_NORMALIZATION_REPORT}});if(!ok)errors.push({code:id,target,report:{...window.LAST_DUNGEON_NORMALIZATION_REPORT}});}catch(error){cases.push({id,ok:false,error:String(error?.message||error)});errors.push({code:id,error:String(error?.message||error)});}};const profile={positionModelVersion:1,assessmentRuleVersion:4,balanceVersion:7,highestArenaUnlocked:2,rank:2,lastCheckRuns:0,lastCheckClearCount:0};run("RETIRED_W3_RANK_REMOVED",{secondWorld:{entered:true},thirdWorld:{entered:true},dungeon:{arenaByWorld:{1:{...profile},2:{...profile},3:{rank:9}}}},(s,r)=>!Object.prototype.hasOwnProperty.call(s.dungeon.arenaByWorld,"3")&&s.dungeon.arenaByWorld[1].rank===2&&s.dungeon.arenaByWorld[2].rank===2&&r.retiredWorld3ArenaRankRemoved===true);const validTxn={version:1,status:"active",mode:"fixed",runIndex:0,requestedRuns:5,stageIndex:1,bossIds:["a","a","a"],dailyUsedBefore:3,dailyUsedAfter:4,dateKey:"2026-09-29",startedAt:1000,currentHp:1234,garbage:"remove"};run("VALID_W3_TRANSACTION_PRESERVED",{secondWorld:{entered:true},thirdWorld:{entered:true},daily:{dateKey:"2026-09-29"},dungeon:{thirdWorldArenaTransaction:{...validTxn}}},(s,r)=>s.dungeon.thirdWorldArenaTransaction?.currentHp===1234&&!Object.prototype.hasOwnProperty.call(s.dungeon.thirdWorldArenaTransaction,"garbage")&&r.thirdWorldArenaTransactionAction==="preserved");run("INVALID_W3_TRANSACTION_REMOVED",{secondWorld:{entered:true},thirdWorld:{entered:true},daily:{dateKey:"2026-09-29"},dungeon:{thirdWorldArenaTransaction:{...validTxn,mode:"varied",bossIds:["a","a","a"]}}},(s,r)=>!Object.prototype.hasOwnProperty.call(s.dungeon,"thirdWorldArenaTransaction")&&r.thirdWorldArenaTransactionAction==="removed");run("STALE_W3_TRANSACTION_REMOVED",{secondWorld:{entered:true},thirdWorld:{entered:true},daily:{dateKey:"2026-09-30"},dungeon:{thirdWorldArenaTransaction:{...validTxn}}},(s,r)=>!Object.prototype.hasOwnProperty.call(s.dungeon,"thirdWorldArenaTransaction")&&r.thirdWorldArenaTransactionReason==="stale-date");const report={version:1,passed:errors.length===0,errors,cases,checkedAt:Date.now()};window.DUNGEON_STATE_MIGRATION_REGRESSION_REPORT=report;return report;}window.runDungeonStateMigrationRegression=runDungeonStateMigrationRegression;window.DUNGEON_STATE_MIGRATION_REGRESSION_VERSION=1;
 function initializeVipHpIfNeeded(){if(!state||state.vipInitialized===true)return false;const baseMax=Math.max(1,equippedStats().hp),current=Math.max(0,Number(state.hp)||0),ratio=Math.max(0,Math.min(1,current/baseMax)),vipMax=Math.max(1,playerCombatStats().hp);state.hp=current>=baseMax?vipMax:Math.max(0,Math.min(vipMax,Math.round(vipMax*ratio)));state.vipInitialized=true;return true;}function normalizeFreshDungeonState(target){normalizeDungeonState(target);target.vipInitialized=true;return target;}if(typeof registerNewStateNormalizer==="function")registerNewStateNormalizer(normalizeFreshDungeonState);
 window.finalizeDungeonLoadedState=function(){const vipHpInitialized=initializeVipHpIfNeeded(),beforeMirrorStatus=state?.dungeon?.mirror?.daily?.status;normalizeDungeonState(state,{timestamp:Date.now(),mirrorOptions:{recoverInterrupted:true}});const arenaRecovery=typeof window.recoverInterruptedThirdWorldArenaRun==="function"?window.recoverInterruptedThirdWorldArenaRun(state):{recovered:false},afterMirrorStatus=state?.dungeon?.mirror?.daily?.status;state.saveVersion=typeof currentSaveVersion==="function"?currentSaveVersion():SAVE_VERSION;return {vipHpInitialized,recoveredInterruptedRun:arenaRecovery?.recovered===true,recoveredInterruptedArenaRun:arenaRecovery?.recovered===true,recoveredInterruptedMirrorRun:beforeMirrorStatus==="running"&&afterMirrorStatus!=="running",dungeon:state.dungeon};};window.ensureDungeonState=function(){return normalizeDungeonState(state);};window.ensureDungeonProgressState=window.ensureDungeonState;
 window.addDungeonPoints=function(amount){const baseAdded=Math.floor(finiteNonNegative(amount,0)),multiplier=typeof vipDungeonPointMultiplier==="function"?vipDungeonPointMultiplier():1,adjusted=typeof adjustVipDungeonPoints==="function"?adjustVipDungeonPoints(baseAdded):Math.floor(baseAdded*multiplier),result=typeof addVipPoints==="function"?addVipPoints(adjusted):{added:adjusted,points:(state.vipPoints||0)+adjusted};state.vipPoints=Math.floor(finiteNonNegative(result.points,0));return {added:result.added??adjusted,baseAdded,points:state.vipPoints,multiplier,vipLevel:state.vipLevel||0,levelsGained:result.levelsGained||0};};
})();