(function(){
 let pending=null,busy=false;
 function ensure(){normalizeEnhancementState(state);}
 function fmt(stat,value){const rate=stat==="crit"||stat==="dodge";const n=rate?round1(value):Math.ceil(value);return `${STAT_LABELS[stat]||stat} +${n}${rate?"%":""}`;}
 function level(type){ensure();return enhancementLevel(state,type);}
 function progress(){return ENHANCEMENT_SLOTS.reduce((sum,type)=>sum+level(type),0);}
 function slotCard(type){
  const lv=level(type),max=lv>=ENHANCEMENT_MAX_LEVEL,item=state.equipment?.[type]||null,next=Math.min(ENHANCEMENT_MAX_LEVEL,lv+1),cost=max?null:enhancementUpgradeCost(next),pct=enhancementBonusPercent(lv),nextPct=enhancementBonusPercent(next);
  let itemHtmlBlock=`<div class="enhance-empty muted">目前未裝備；欄位仍可永久強化。</div>`;
  if(item){const stat=item.mainStat?.stat||mainStatForType(type),raw=Math.max(0,Number(item.mainStat?.value)||0),actual=enhancedMainStatValue(raw,lv),nextValue=enhancedMainStatValue(raw,next);itemHtmlBlock=`<div class="enhance-item">${itemHtml(item,true)}</div><div class="enhance-stat-row"><span>原始主能力</span><b>${fmt(stat,raw)}</b></div><div class="enhance-stat-row current"><span>目前實際主能力</span><b>${fmt(stat,actual)}</b></div>${max?"":`<div class="enhance-stat-row next"><span>強化後主能力</span><b>${fmt(stat,nextValue)}</b></div>`}`;}
  return `<section class="enhance-slot-card"><div class="enhance-slot-head"><div><h3>${EQUIPMENT_LABELS[type]}</h3><span class="muted">欄位永久強化</span></div><strong>${max?`+${lv} MAX`:`+${lv} / ${ENHANCEMENT_MAX_LEVEL}`}</strong></div><div class="enhance-effect">主能力加成 <b>+${pct}%</b>${max?"":` <span>→ +${nextPct}%</span>`}</div>${itemHtmlBlock}${max?`<div class="enhance-max">已達最高強化等級</div>`:`<div class="enhance-cost"><span>下一級 +${next}</span><span>基礎強化石 ×${cost.basic.toLocaleString()}</span><span>進階強化石 ×${cost.advanced.toLocaleString()}</span></div><button class="btn primary enhance-action" onclick="openEnhancementConfirm('${type}')" ${state.enhancement.basicStones<cost.basic||state.enhancement.advancedStones<cost.advanced?"disabled":""}>強化至 +${next}</button>`}</section>`;
 }
 function page(){ensure();return `<div class="function-page enhancement-page"><div class="back-home"><button class="btn back-btn" onclick="go('home')">← 返回主頁</button></div><div class="enhance-shell"><div class="card enhance-summary"><div class="enhance-title"><div><h2>裝備欄位強化</h2><div class="muted">永久提升裝備欄位主能力；更換或遺失裝備不影響強化等級。</div></div><div class="enhance-progress">強化進度 <b>${progress()} / ${ENHANCEMENT_SLOTS.length*ENHANCEMENT_MAX_LEVEL}</b></div></div><div class="enhance-resources"><div><span>基礎強化石</span><b>${state.enhancement.basicStones.toLocaleString()}</b></div><div><span>進階強化石</span><b>${state.enhancement.advancedStones.toLocaleString()}</b></div></div></div><div class="enhance-grid">${ENHANCEMENT_SLOTS.map(slotCard).join("")}</div></div></div>`;}
 function ensureModal(){if(document.getElementById("enhancementConfirmModal"))return;const el=document.createElement("div");el.className="modal";el.id="enhancementConfirmModal";el.innerHTML=`<div class="modal-box enhancement-confirm-box"><h3>確認強化</h3><div id="enhancementConfirmDetail"></div><div class="controls"><button class="btn" onclick="closeEnhancementConfirm()">取消</button><button id="enhancementConfirmButton" class="btn primary" onclick="confirmEnhancementUpgrade()">確認強化</button></div></div>`;document.body.appendChild(el);}
 window.openEnhancementConfirm=function(type){ensure();if(busy||!ENHANCEMENT_SLOTS.includes(type))return;const lv=level(type);if(lv>=ENHANCEMENT_MAX_LEVEL)return;const next=lv+1,cost=enhancementUpgradeCost(next);if(state.enhancement.basicStones<cost.basic||state.enhancement.advancedStones<cost.advanced)return alert("強化石不足。");pending={type,level:lv,next,cost};ensureModal();document.getElementById("enhancementConfirmDetail").innerHTML=`<div class="enhance-confirm-question">確定要強化<b>${EQUIPMENT_LABELS[type]}欄位</b>嗎？</div><div class="enhance-confirm-lines"><div><span>強化等級</span><b>+${lv} → +${next}</b></div><div><span>主能力加成</span><b>+${enhancementBonusPercent(lv)}% → +${enhancementBonusPercent(next)}%</b></div><div><span>基礎強化石</span><b>×${cost.basic.toLocaleString()}</b></div><div><span>進階強化石</span><b>×${cost.advanced.toLocaleString()}</b></div></div>`;document.getElementById("enhancementConfirmModal").classList.add("show");};
 window.closeEnhancementConfirm=function(){if(busy)return;pending=null;document.getElementById("enhancementConfirmModal")?.classList.remove("show");};
 window.confirmEnhancementUpgrade=function(){if(busy||!pending)return;busy=true;const btn=document.getElementById("enhancementConfirmButton");if(btn)btn.disabled=true;try{ensure();const p=pending,current=level(p.type),cost=enhancementUpgradeCost(p.next);if(current!==p.level||p.next!==current+1){alert("強化狀態已變更，請重新操作。");return;}if(state.enhancement.basicStones<cost.basic||state.enhancement.advancedStones<cost.advanced){alert("強化石不足。");return;}state.enhancement.basicStones-=cost.basic;state.enhancement.advancedStones-=cost.advanced;state.enhancement.levels[p.type]=p.next;if(typeof restorePlayerHp==="function")restorePlayerHp({save:false});else normalizeHP();save(false);pending=null;document.getElementById("enhancementConfirmModal")?.classList.remove("show");render();}finally{if(btn)btn.disabled=false;busy=false;}};
 window.enhancementPage=page;
 window.ENHANCEMENT_UI_SUCCESS_ALERT_DISABLED=true;
 window.ENHANCEMENT_UI_UNIFORM_GRID=true;
 function styles(){if(document.getElementById("enhancement-ui-styles"))return;const s=document.createElement("style");s.id="enhancement-ui-styles";s.textContent=`.enhance-shell{max-width:1120px;margin:0 auto}.enhance-summary{margin-bottom:14px}.enhance-title{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.enhance-title h2{margin:0 0 5px}.enhance-progress{white-space:nowrap;color:#cdbb90}.enhance-progress b{color:#f0d494}.enhance-resources{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px}.enhance-resources>div{background:#10161d;border:1px solid #3c4651;border-radius:10px;padding:12px 14px;display:flex;justify-content:space-between}.enhance-resources span{color:#aeb9c5}.enhance-resources b{color:#f0d494;font-size:18px}.enhance-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.enhance-slot-card{background:linear-gradient(180deg,#171d25,#0f141a);border:1px solid #424c58;border-radius:13px;padding:15px}.enhance-slot-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.enhance-slot-head h3{margin:0;color:#f0d494}.enhance-slot-head strong{font-size:18px;color:#dce8f4}.enhance-effect{margin:13px 0;padding:9px 10px;background:#0c1218;border-radius:8px}.enhance-effect b{color:#7fc8ff}.enhance-effect span{color:#8fa0b1}.enhance-item{margin-bottom:8px}.enhance-stat-row{display:flex;justify-content:space-between;gap:10px;padding:5px 0}.enhance-stat-row span{color:#9eaab6}.enhance-stat-row.current b{color:#dce8f4}.enhance-stat-row.next b{color:#86d99a}.enhance-empty{padding:13px 0}.enhance-cost{display:flex;gap:12px;flex-wrap:wrap;margin:13px 0 9px;padding-top:10px;border-top:1px solid #303944;color:#c5cdd6}.enhance-cost span:first-child{color:#f0d494}.enhance-action{width:100%}.enhance-action:disabled{opacity:.45}.enhance-max{text-align:center;margin-top:13px;padding:10px;border:1px solid #4b5945;border-radius:8px;color:#9fd59b}.enhancement-confirm-box{max-width:430px}.enhancement-confirm-box h3{color:#f0d494}.enhance-confirm-question{margin-bottom:13px}.enhance-confirm-question b{color:#f0d494;margin-left:4px}.enhance-confirm-lines{border:1px solid #39434e;border-radius:10px;padding:8px 12px;background:#0f151b}.enhance-confirm-lines>div{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid #29313a}.enhance-confirm-lines>div:last-child{border-bottom:0}.enhance-confirm-lines span{color:#aeb9c5}@media(max-width:760px){.enhance-summary{padding:12px}.enhance-title{display:block}.enhance-progress{margin-top:10px}.enhance-resources{grid-template-columns:1fr;gap:7px}.enhance-grid{grid-template-columns:1fr;gap:9px}.enhance-slot-card{padding:12px}.enhance-cost{gap:7px 12px;font-size:13px}}`;document.head.appendChild(s);}styles();ensureModal();
})();
