(function(){
 const baseGameGuidePage=window.gameGuidePage;
 if(typeof baseGameGuidePage!=="function")return;
 const oldBounty=`<div class="guide-item"><h4>懸賞戰</h4><div class="guide-item-body">懸賞戰為單場挑戰，可能遇到普通、高級或危險懸賞。難度越高，EXP、金幣與裝備數量越多；懸賞掉落的裝備最低為稀有品質。</div></div>`;
 const newBounty=`<div class="guide-item"><h4>懸賞戰</h4><div class="guide-item-body">懸賞戰是資源型副本，主打高 EXP、高金幣與多裝備。每次會隨機遇到普通、高級或危險懸賞，實際獎勵在戰後結算；掉落裝備最低為稀有品質。</div></div><div class="guide-item"><h4>懸賞連續挑戰</h4><div class="guide-item-body">懸賞可選單次或連續挑戰。連續模式會在每一場真正開始前消耗 1 次副本挑戰次數，每場結束後 HP 會回滿並自動進入下一場。玩家死亡、挑戰次數不足，或手動要求停止時會結束；手動停止會在目前這一場結束後生效，最後統一顯示總結算。</div></div>`;
 const oldArena=`<div class="guide-item"><h4>競技場</h4><div class="guide-item-body">競技場共有普通、困難、極限 3 種難度。按下開始後會自動連續進行 3 場戰鬥，三戰之間不回血；任一戰失敗即結束並進入結算。整組競技場結束後 HP 會回滿。每擊敗一名敵人都能取得部分 VIP 積分，每遇到新的敵人都會重新取得一次先制機會。</div></div>`;
 const newArena=`<div class="guide-item"><h4>十大競技場</h4><div class="guide-item-body">競技場共有 10 個，名稱直接對應主線 10 大區域：地球戰爭競技場、太陽系戰爭競技場、近星戰爭競技場、星際邊疆競技場、獵戶臂戰爭競技場、銀河邊境競技場、銀河中域競技場、銀河核心外圍競技場、銀河核心戰爭競技場、銀河統合戰爭競技場。</div></div><div class="guide-item"><h4>逐個解鎖</h4><div class="guide-item-body">Lv15 開放競技場時，只有地球戰爭競技場已解鎖。要開下一個競技場，必須讓目前最高已解鎖競技場的高難戰力評估達到 90%，並且主線已解鎖下一個競技場對應區域。兩個條件缺一不可。</div></div><div class="guide-item"><h4>戰力評估與主線條件</h4><div class="guide-item-body">戰力評估固定用目前最高已解鎖競技場的高難，模擬 500 次完整三連戰，至少 450 次全通才算通過。例如要從地球戰爭競技場開啟太陽系戰爭競技場，除了地球戰爭競技場高難至少 450 / 500，主線第 2 區「太陽系戰爭」也必須已解鎖。要開近星戰爭競技場則同理，需要太陽系戰爭競技場達 90% 且主線第 3 區已開。</div></div><div class="guide-item"><h4>畫面最多顯示最近3個</h4><div class="guide-item-body">已解鎖 1 個時只顯示第 1 個；已解鎖 2 個時顯示第 1～2 個；已解鎖 3 個時顯示第 1～3 個。當第 4 個競技場解鎖後，第 1 個會從競技場首頁消失，改顯示第 2～4 個；之後永遠只保留最近最多 3 個已解鎖競技場，最後為第 8～10 個。</div></div><div class="guide-item"><h4>低／中／高難</h4><div class="guide-item-body">每一個競技場都有低難、中難、高難 3 種難度。玩家先選競技場，再選難度。低難偏向穩定通關，中難有明顯風險，高難是最高風險，也是解鎖下一競技場時唯一使用的戰力評估難度。每次挑戰固定連續進行 3 戰，三戰之間不回血；任一戰失敗就結束該輪。</div></div><div class="guide-item"><h4>競技場連續挑戰</h4><div class="guide-item-body">任一目前顯示的競技場、任一難度都可選單次或連續挑戰。連續模式會鎖定開始時選擇的競技場與難度，一個完整三連戰算一輪；三戰內不回血，新一輪開始前才會補滿 HP 並消耗下一次副本挑戰次數。玩家死亡、挑戰次數不足，或手動要求停止時會結束；手動停止會在目前整輪三連戰結束後生效，最後統一顯示總結算。</div></div><div class="guide-item"><h4>競技場積分</h4><div class="guide-item-body">競技場 VIP 積分會隨競技場序號提高。第 1 個競技場的低難、中難、高難全通總積分分別為 180、300、420；之後每增加 1 個競技場，三種難度的全通總積分都增加 130，且三戰的積分會一起按比例提高。</div></div>`;
 window.gameGuidePage=function(){
  let html=baseGameGuidePage();
  html=html.replace(oldBounty,newBounty).replace(oldArena,newArena);
  return html;
 };
})();