(function(){
 const baseGameGuidePage=window.gameGuidePage;
 if(typeof baseGameGuidePage!=="function")return;
 const oldBounty=`<div class="guide-item"><h4>懸賞戰</h4><div class="guide-item-body">懸賞戰為單場挑戰，可能遇到普通、高級或危險懸賞。難度越高，EXP、金幣與裝備數量越多；懸賞掉落的裝備最低為稀有品質。</div></div>`;
 const newBounty=`<div class="guide-item"><h4>懸賞戰</h4><div class="guide-item-body">懸賞戰是資源型副本，主打高 EXP、高金幣與多裝備。每次會隨機遇到普通、高級或危險懸賞，實際獎勵在戰後結算；掉落裝備最低為稀有品質。</div></div><div class="guide-item"><h4>懸賞連續挑戰</h4><div class="guide-item-body">懸賞可選單次或連續挑戰。連續模式會在每一場真正開始前消耗 1 次副本挑戰次數，每場結束後 HP 會回滿並自動進入下一場。玩家死亡、挑戰次數不足，或手動要求停止時會結束；手動停止會在目前這一場結束後生效，最後統一顯示總結算。</div></div>`;
 const oldArena=`<div class="guide-item"><h4>競技場</h4><div class="guide-item-body">競技場共有普通、困難、極限 3 種難度。按下開始後會自動連續進行 3 場戰鬥，三戰之間不回血；任一戰失敗即結束並進入結算。整組競技場結束後 HP 會回滿。每擊敗一名敵人都能取得部分 VIP 積分，每遇到新的敵人都會重新取得一次先制機會。</div></div>`;
 const newArena=`<div class="guide-item"><h4>十大區域競技場</h4><div class="guide-item-body">競技場共有 10 個，名稱直接對應主線 10 大區域：地球戰爭競技場、太陽系戰爭競技場、近星戰爭競技場、星際邊疆競技場、獵戶臂戰爭競技場、銀河邊境競技場、銀河中域競技場、銀河核心外圍競技場、銀河核心戰爭競技場、銀河統合戰爭競技場。正式名稱不使用普通、困難、極限。</div></div><div class="guide-item"><h4>逐個解鎖</h4><div class="guide-item-body">Lv15 開放競技場時只有地球戰爭競技場。要解鎖下一個競技場，必須讓目前最高已解鎖競技場的戰力評估達到 90%，並且主線已解鎖下一個競技場對應區域。兩個條件缺一不可。</div></div><div class="guide-item"><h4>最近最多3個競技場</h4><div class="guide-item-body">已解鎖 1 個時只顯示第 1 個；已解鎖 2 個時顯示第 1～2 個；已解鎖 3 個時顯示第 1～3 個。解鎖第 4 個後，第 1 個消失，改顯示第 2～4 個；之後永遠保留最近最多 3 個，最後為第 8～10 個。</div></div><div class="guide-item"><h4>位置算法</h4><div class="guide-item-body">目前畫面由左至右依序套用低／中／高位置算法。只開 1 個競技場時，第 1 個使用低位置；開到 2 個時，第 1 個低、第 2 個中；開到 3 個以上時，最近 3 個固定為左低、中中、右高。位置算法控制敵人的暴擊、閃避、特性與 VIP 積分模板；HP、ATK、DEF 則只依競技場實際階層計算。</div></div><div class="guide-item"><h4>位置會隨進度改變</h4><div class="guide-item-body">同一個競技場在不同階段可能使用不同位置算法。例如顯示第 1～3 個時，近星戰爭競技場在最右側，使用高位置；解鎖第 4 個後畫面變成第 2～4 個，近星戰爭競技場移到中間，改用中位置；再解鎖第 5 個後它移到左側，改用低位置。它的 HP／ATK／DEF 階層倍率仍然始終是第 3 個競技場。</div></div><div class="guide-item"><h4>戰力評估與主線條件</h4><div class="guide-item-body">戰力評估永遠測目前最高已解鎖競技場在當下位置的算法，模擬 500 次完整三連戰，至少 450 次全通才算通過。第 1 個競技場作為最高時使用低位置，第 2 個作為最高時使用中位置，第 3 個起最高競技場都位於右側，因此使用高位置。通過戰力評估後，還要等下一競技場對應主線區域已解鎖，才能手動開啟下一個。</div></div><div class="guide-item"><h4>單次與連續挑戰</h4><div class="guide-item-body">點選目前顯示的任一區域競技場後，直接進入該競技場準備頁，不需要再選第二層難度。每輪固定三戰，三戰之間不回血；可選單次或連續挑戰。連續模式會鎖定開始時選到的競技場與當下位置算法，新一輪開始才會補滿 HP 並消耗下一次副本挑戰次數。</div></div><div class="guide-item"><h4>VIP 積分</h4><div class="guide-item-body">VIP 積分同時受競技場序號與目前位置模板影響。低位置基準為 180 + 130×(R−1)，中位置為 300 + 130×(R−1)，高位置為 420 + 130×(R−1)，其中 R 是競技場序號；三戰積分會依原比例一起調整。</div></div>`;
 window.gameGuidePage=function(){
  let html=baseGameGuidePage();
  html=html.replace(oldBounty,newBounty).replace(oldArena,newArena);
  return html;
 };
})();
