(function(){
 let selectedEra="galaxy",selectedRegion="earth",selectedStory="earth-prologue";
 function esc(v){return String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));}
 function stories(){return window.CIVILIZATION_STORIES||{};}function regions(){return selectedEra==="universe"?(Array.isArray(window.CIVILIZATION_UNIVERSE_STORY_REGIONS)?window.CIVILIZATION_UNIVERSE_STORY_REGIONS:[]):(Array.isArray(window.CIVILIZATION_STORY_REGIONS)?window.CIVILIZATION_STORY_REGIONS:[]);}function currentRegion(){return regions().find(x=>x.id===selectedRegion)||regions()[0]||null;}function rows(region=currentRegion()){return Array.isArray(region?.stories)?region.stories:[];}
 function normalize(){const region=currentRegion();if(!region){selectedRegion="";selectedStory="";return;}selectedRegion=region.id;if(!rows(region).some(x=>x.id===selectedStory))selectedStory=rows(region)[0]?.id||"";}function positions(){normalize();const rs=regions(),ri=rs.findIndex(r=>r.id===selectedRegion),list=rows(rs[ri]),si=list.findIndex(s=>s.id===selectedStory);return {rs,ri,list,si};}
 function issueRows(items,type){const list=Array.isArray(items)?items:[];if(!list.length)return "";const color=type==="error"?"#ff9b9b":"#f1d38b";return `<div style="margin-top:8px;display:grid;gap:5px">${list.map((item,i)=>`<div style="padding:7px 9px;border:1px solid #334153;border-radius:8px"><b style="color:${color}">${i+1}. ${esc(item?.code||"UNKNOWN")}</b><br><span class="muted">${esc(item?.message||"")}</span></div>`).join("")}</div>`;}
 function integrityHtml(){const d=window.STORY_INTEGRITY_REPORT,r=window.STORY_RUNTIME_INTEGRITY_REPORT;const dataStatus=d?.passed?`通過・銀河 ${Number(d.galaxyStories)||101}/101・宇宙資料 ${Number(d.universeStoriesLoaded)||0}/100（架構 ${Number(d.universeStoriesExpected)||0}/100）`:`失敗・${d?.errors?.length||0} 項錯誤`;const runtimeStatus=r?.passed?"通過":`失敗・${r?.errors?.length||0} 項錯誤`;return `<div><b>資料完整性</b><div style="margin-top:4px;font-weight:800">${esc(dataStatus)}</div>${issueRows(d?.errors,"error")}</div><div style="margin-top:12px"><b>執行期完整性</b><div style="margin-top:4px;font-weight:800">${esc(runtimeStatus)}</div>${issueRows(r?.errors,"error")}</div>`;}
 function regionOptions(){normalize();return regions().map(r=>`<option value="${esc(r.id)}" ${r.id===selectedRegion?"selected":""}>${esc(r.name)}</option>`).join("");}function storyOptions(){normalize();return rows().map(s=>`<option value="${esc(s.id)}" ${s.id===selectedStory?"selected":""}>${esc(s.label)}${stories()[s.id]?"":"（尚未建立）"}</option>`).join("");}function metaHtml(){normalize();const story=stories()[selectedStory],p=positions(),row=p.list[p.si];if(!row)return `<div class="muted">目前沒有可預覽劇情。</div>`;return `<div class="muted" style="line-height:1.65">紀元：${selectedEra==="universe"?"宇宙紀元":"銀河紀元"}<br>劇情編號：${esc(row.id)}<br>本區第 ${p.si+1} / ${p.list.length} 篇${story?`・共 ${story.pages?.length||0} 頁`:`・正式文字將於後續批次建立`}</div>`;}function nav(label,fn,disabled){return `<button class="btn" onclick="${fn}" ${disabled?"disabled":""}>${label}</button>`;}
 window.gmStoryTestHtml=function(){normalize();const p=positions();return `<div class="muted gm-hub-note">共用正式劇情系統預覽；不修改角色進度、不記錄已讀狀態。</div><div class="card" style="margin-top:10px;padding:12px">${integrityHtml()}<div style="margin-top:10px"><button class="btn" onclick="gmStoryRunIntegrity()">重新檢查完整性</button></div></div><div class="controls" style="align-items:end;margin-top:10px"><label>紀元<br><select class="btn" onchange="gmStoryChangeEra(this.value)"><option value="galaxy" ${selectedEra==="galaxy"?"selected":""}>銀河紀元</option><option value="universe" ${selectedEra==="universe"?"selected":""}>宇宙紀元</option></select></label><label>區域<br><select class="btn" onchange="gmStoryChangeRegion(this.value)">${regionOptions()}</select></label><label>劇情<br><select class="btn" onchange="gmStoryChangeEntry(this.value)">${storyOptions()}</select></label><button class="btn blue" onclick="gmPreviewStory()" ${stories()[selectedStory]?"":"disabled"}>預覽劇情</button></div><div class="card" style="margin-top:10px;padding:12px">${metaHtml()}<div class="controls" style="margin-top:10px">${nav("← 上一區","gmStoryMoveRegion(-1)",p.ri<=0)}${nav("下一區 →","gmStoryMoveRegion(1)",p.ri<0||p.ri>=p.rs.length-1)}${nav("← 上一篇","gmStoryMoveEntry(-1)",p.si<=0)}${nav("下一篇 →","gmStoryMoveEntry(1)",p.si<0||p.si>=p.list.length-1)}</div></div>`;};
 window.gmStoryChangeEra=function(value){selectedEra=value==="universe"?"universe":"galaxy";const first=regions()[0];selectedRegion=first?.id||"";selectedStory=first?.stories?.[0]?.id||"";if(typeof render==="function")render();};window.gmStoryChangeRegion=function(id){selectedRegion=String(id||"");selectedStory=currentRegion()?.stories?.[0]?.id||"";if(typeof render==="function")render();};window.gmStoryChangeEntry=function(id){selectedStory=String(id||"");if(typeof render==="function")render();};
 window.gmStoryMoveRegion=function(delta){const p=positions(),next=p.ri+Number(delta||0);if(next<0||next>=p.rs.length)return false;selectedRegion=p.rs[next].id;selectedStory=rows(p.rs[next])[0]?.id||"";if(typeof render==="function")render();return true;};window.gmStoryMoveEntry=function(delta){const p=positions(),next=p.si+Number(delta||0);if(next<0||next>=p.list.length)return false;selectedStory=p.list[next].id;if(typeof render==="function")render();return true;};
 window.gmStoryRunIntegrity=function(){window.runCivilizationStoryIntegrity?.();window.runCivilizationStoryRuntimeIntegrity?.();if(typeof render==="function")render();return true;};window.gmPreviewStory=function(){normalize();if(!stories()[selectedStory]){alert("這篇宇宙紀元正式劇情尚未建立。");return false;}return window.openStory?.(selectedStory)===true;};
 function loadUniverseSample(){if(typeof document==="undefined"||stories()["universe-galaxy-beyond-boss-1"]||document.querySelector?.('script[data-universe-story-sample]'))return;const script=document.createElement("script");script.src="storydata-universe-galaxy-beyond.js?v=20260923-universe-story-batch2";script.dataset.universeStorySample="1";script.onload=()=>{window.runCivilizationStoryIntegrity?.();window.runCivilizationStoryRuntimeIntegrity?.();if(typeof render==="function"&&window.gmUnlocked===true)render();};document.head.appendChild(script);}
 if(typeof window.registerGmHubSection==="function")window.registerGmHubSection("test","劇情測試",window.gmStoryTestHtml,{id:"gm-story-test",position:"prepend"});window.GM_STORY_TEST_VERSION=5;loadUniverseSample();
})();