(function(){
 const VERSION=2;
 const EXPECTED_VERSIONS=Object.freeze({SAVE_SCHEMA_VERSION:16,SAVE_LOAD_PIPELINE_VERSION:2,SAVE_NORMALIZATION_PIPELINE_VERSION:2,SAVE_NORMALIZATION_PIPELINE_STAGE_LABELS_VERSION:1,SAVE_LEGACY_SUPPORT_POLICY_VERSION:1,SAVE_FUTURE_VERSION_GUARD_VERSION:1,OFFLINE_STATE_NORMALIZATION_VERSION:1,LEGACY_COMPATIBILITY_OWNER_VERSION:1,SCRIPT_LOAD_POLICY_VERSION:2,WORLD_PHASE_VERSION:6,WORLD_PHASE_SHARED_CORE_VERSION:3,WORLD_PHASE_ENTRY_REQUIREMENT_CORE_VERSION:1,WORLD_PHASE_SAFE_TRANSITION_VERSION:3,WORLD_PHASE_TRANSITION_CALLBACK_CONTRACT_VERSION:1,WORLD_TRANSITION_CLEANUP_VERSION:1,WORLD_TRANSITION_RUNTIME_GUARD_VERSION:1,WORLD_PHASE_METADATA_VERSION:2,WORLD_PHASE_PRIMARY_RESOURCE_VERSION:2,WORLD_PHASE_ENHANCEMENT_REQUIREMENT_OWNER_VERSION:2,SECOND_WORLD_ENTRY_PURE_READ_VERSION:2,WORLD_PHASE_UI_VERSION:3,WORLD_PHASE_SHARED_UI_VERSION:1,THIRD_WORLD_PHASE_VERSION:3,THIRD_WORLD_PERSISTENCE_POLICY_VERSION:1,THIRD_WORLD_COMPLETION_DERIVATION_VERSION:1,THIRD_WORLD_ENTRY_REQUIREMENTS_VERSION:1,THIRD_WORLD_ENTRY_TRANSITION_VERSION:2,THIRD_WORLD_ENTRY_STATE_MUTATION_VERSION:1,THIRD_WORLD_STATE_MIGRATION_VERSION:1,THIRD_WORLD_PRE_SCHEMA16_DISCARD_VERSION:1,SAVE_PRE_SCHEMA16_BACKUP_VERSION:1,GEAR_WORLD_FIELD_MIGRATION_VERSION:2,THIRD_WORLD_PHASE_INTEGRITY_VERSION:4,PLAYER_SEMANTICS_UI_VERSION:6,PLAYER_SEMANTICS_WORLD_PHASE_VERSION:1,LEVEL_PROGRESSION_AUDIT_VERSION:1,PLAYER_TITLE_CATALOG_VERSION:3,PLAYER_TITLE_INTEGRITY_VERSION:9,GM_PLAYER_TITLE_PREVIEW_INTEGRITY_VERSION:2,PLAYER_TITLE_UNIVERSE_VISUAL_INTEGRITY_VERSION:2,ARENA_BY_WORLD_STATE_VERSION:2,ARENA_BY_WORLD_MIGRATION_VERSION:1,SECOND_WORLD_ARENA_UNLOCK_VERSION:2,SECOND_WORLD_ARENA_RANK_CURVE_VERSION:2,SECOND_WORLD_CIVILIZATION_COMBAT_VERSION:2,BOUNTY_BALANCE_VERSION:2,BOUNTY_DIFFICULTY_FORMULA_VERSION:2,SECOND_WORLD_ADVENTURE_UI_VERSION:4,SECOND_WORLD_CALAMITY_FULL_INTEGRITY_VERSION:2,LEVEL_PROGRESSION_VERSION:1,VIP_PROGRESSION_VERSION:14,VIP_UNBOUNDED_LEVEL_VERSION:1,VIP_PERK_MAX_LEVEL:20,VIP_POINTS_SOURCE_OF_TRUTH_VERSION:1,VIP_STATE_RECONCILIATION_VERSION:1,VIP_ADD_POINTS_OWNER_REQUIRED_VERSION:1,VIP_UI_VERSION:2,GM_UNBOUNDED_VIP_TEST_VERSION:1,VIP_UNBOUNDED_INTEGRITY_VERSION:1,GAME_GUIDE_VERSION:19});
 const REQUIRED_APIS=Object.freeze(["normalizeSaveState","migrateSave","load","saveWriteGuardStatus","saveCompatibilityFor","assertSaveVersionSupported","normalizeOfflineSaveState","currentWorldPhase","worldProgressionEnabled","worldPhaseSnapshot","primaryWorldResourceSnapshot","scriptLoadGroupFor","worldPhaseSpecializationRequirement","worldPhaseEnhancementRequirement","worldPhaseMarkRequirement","summarizeWorldEntryRequirements","runWorldTransition","worldTransitionRuntimeStatus","resetOfflineStateForWorldTransition","restoreLostGearForWorldTransition","resetWorldTransitionTransientRuntime","worldPhaseHomeEntryHtml","openWorldPhaseRequirements","openWorldPhaseConfirmation","confirmWorldPhaseEntry","openSecondWorldRequirements","openThirdWorldRequirements","showWorldPhaseUnlockNotice","createBlankThirdWorldState","normalizeThirdWorldState","thirdWorldState","thirdWorldBossesAllDefeated","thirdWorldCompletionSnapshot","finalSecondWorldStoryId","isFinalSecondWorldStoryId","finalSecondWorldBossKilled","finalSecondWorldStoryCompleted","thirdWorldEntryRequirements","canEnterThirdWorld","applyThirdWorldEntryState","enterThirdWorld","normalizePlayerTitleState","playerIdentityNameHtml","equipPlayerTitle","getArenaProgressForWorld","getCurrentArenaProgress","getArenaVersionProfile","effectiveLevelCap","effectiveExpNeed","levelProgressionAudit","civilizationCombatDamageMultiplier","secondWorldBossBaseStats","runSecondWorldBossCombat","secondWorldAdventurePageHtml","gameGuideCategoriesForState","vipThreshold","vipLevelFromPoints","normalizeVipState","vipBonusStats","gmVipManagementHtml","gmSetTestVipLevel"]);
 function runThirdWorldFoundationProbe(){
  const errors=[],fail=(code,data=null)=>errors.push({code,data});
  try{
   const blank=window.createBlankThirdWorldState?.();
   if(!blank||blank.entered!==false||blank.completed!==false||blank.dimensionalStrings!==0||blank.coreLevel!==0||!Array.isArray(blank.bosses)||blank.bosses.length!==10||blank.bosses.some(row=>Number(row?.currentHp)!==1100000000)||blank.story?.introSeen!==false||blank.story?.unlockedStage!==0||blank.story?.finalSeen!==false)fail("BLANK_STATE",blank||null);
   const malformed={thirdWorld:{entered:false,completed:true,dimensionalStrings:-10,coreLevel:99,transientDeaths:77,bosses:[{currentHp:-5,tempShield:99},{currentHp:99999999999}],story:{introSeen:1,unlockedStage:99,finalSeen:"yes",tempStage:9}},secondWorld:{entered:false}};
   window.normalizeThirdWorldState?.(malformed);const snapshot=JSON.stringify(malformed);window.normalizeThirdWorldState?.(malformed);
   if(malformed.thirdWorld?.entered!==true||malformed.secondWorld?.entered!==true||malformed.thirdWorld?.dimensionalStrings!==0||malformed.thirdWorld?.coreLevel!==10||malformed.thirdWorld?.bosses?.length!==10||malformed.thirdWorld?.bosses?.[0]?.currentHp!==0||malformed.thirdWorld?.bosses?.[1]?.currentHp!==1100000000||malformed.thirdWorld?.story?.introSeen!==false||malformed.thirdWorld?.story?.unlockedStage!==10||malformed.thirdWorld?.story?.finalSeen!==false)fail("NORMALIZATION",malformed);
   if(Object.prototype.hasOwnProperty.call(malformed.thirdWorld,"transientDeaths")||Object.prototype.hasOwnProperty.call(malformed.thirdWorld.bosses[0],"tempShield")||Object.prototype.hasOwnProperty.call(malformed.thirdWorld.story,"tempStage"))fail("PERSISTENCE_ALLOWLIST",malformed.thirdWorld);
   if(JSON.stringify(malformed)!==snapshot)fail("NORMALIZATION_NOT_IDEMPOTENT",malformed);
   const galaxy={gold:123,secondWorld:{entered:false,darkMatter:5,darkEnergy:2},thirdWorld:{entered:false,dimensionalStrings:9}},universe={gold:123,secondWorld:{entered:true,darkMatter:456,darkEnergy:7},thirdWorld:{entered:false,dimensionalStrings:9}},higher={gold:123,secondWorld:{entered:true,darkMatter:456,darkEnergy:7},thirdWorld:{entered:true,dimensionalStrings:789}};
   if(window.currentWorldPhase?.(galaxy)!==1||window.currentWorldPhase?.(universe)!==2||window.currentWorldPhase?.(higher)!==3)fail("CURRENT_PHASE");
   if(window.worldProgressionEnabled?.(2.9,universe)!==false||window.worldPhaseMeta?.(3.1)!==null)fail("STRICT_WORLD_INDEX");
   const meta1=window.WORLD_PHASE_METADATA?.[1],meta2=window.WORLD_PHASE_METADATA?.[2],meta3=window.WORLD_PHASE_METADATA?.[3];if(meta1?.stateKey!==null||meta2?.stateKey!=="secondWorld"||meta3?.stateKey!=="thirdWorld")fail("WORLD_METADATA",{meta1,meta2,meta3});
   const phase=window.worldPhaseSnapshot?.(higher),gRes=window.primaryWorldResourceSnapshot?.(galaxy),uRes=window.primaryWorldResourceSnapshot?.(universe),hRes=window.primaryWorldResourceSnapshot?.(higher);
   if(phase?.current!==3||phase?.entered?.[2]!==true||phase?.entered?.[3]!==true||phase?.progression?.[1]!==false||phase?.progression?.[2]!==false||phase?.progression?.[3]!==true)fail("PHASE_SNAPSHOT",phase||null);
   if(gRes?.label!=="金幣"||gRes?.amount!==123||uRes?.label!=="暗物質"||uRes?.amount!==456||uRes?.secondaryLabel!=="暗能量"||uRes?.secondaryAmount!==7||hRes?.label!=="維度之弦"||hRes?.amount!==789||hRes?.secondaryLabel!==null)fail("RESOURCE_OWNER",{gRes,uRes,hRes});
   const completedProbe={thirdWorld:{entered:true,completed:false,dimensionalStrings:0,coreLevel:0,bosses:Array.from({length:10},()=>({currentHp:0})),story:{introSeen:true,unlockedStage:10,finalSeen:false}},secondWorld:{entered:true}};const completion=window.thirdWorldCompletionSnapshot?.(completedProbe);if(completion?.bossesDefeated!==true||completion?.storedCompleted!==false||completion?.readyForCompletionOwner!==true)fail("COMPLETION_DERIVATION",completion||null);
   const finalStoryId=window.finalSecondWorldStoryId?.(),specKeys=Array.from(window.SPECIALIZATION_KEYS||[]),markIds=Array.from(window.CIVILIZATION_MARK_IDS||[]),slots=Array.from(window.ENHANCEMENT_SLOTS||[]);
   const eligibleProbe={level:1000,exp:54321,vipPoints:window.vipThreshold?.(20)??400000,specializations:Object.fromEntries(specKeys.map(key=>[key,60])),marks:{entries:Object.fromEntries(markIds.map(id=>[id,{level:10}]))},enhancement:{levels:Object.fromEntries(slots.map(slot=>[slot,40]))},equipment:{sentinel:"equipment-kept"},inventory:[{id:"kept-item"}],lostGear:[{id:"lost-row",item:{id:"restored-item",world:2}}],pendingBlackMarketEncounter:true,offline:{farmMap:5,farmEnemy:2,avgBattleMs:1200,sampleCount:2,battleSamples:[{world:2}],pendingSettlement:{pending:true},lastSettledAt:1,maxObservedWallClock:1,timeLockUntil:99},secondWorld:{entered:true,darkMatter:999,darkEnergy:88,civilizationLevel:10,mainline:{bossKilled:Array.from({length:100},(_,index)=>index===99)}},thirdWorld:{entered:false},storyProgress:{completedStories:finalStoryId?[finalStoryId]:[]},dungeon:{sentinel:"dungeon-kept"},playerTitles:{sentinel:"titles-kept"}};
   const entry=window.thirdWorldEntryRequirements?.(eligibleProbe);if(!finalStoryId||entry?.eligible!==true||entry?.total!==7||entry?.completed!==7||entry?.mainline?.bossCompleted!==true||entry?.mainline?.finalStoryCompleted!==true||entry?.enhancement?.requiredLevel!==40||entry?.civilization?.required!==10||entry?.vip?.required!==20||entry?.specializations?.requiredLevel!==60||entry?.marks?.requiredLevel!==10||window.canEnterThirdWorld?.(eligibleProbe)!==true)fail("THIRD_WORLD_ENTRY_READY",{finalStoryId,entry});
   if(window.isFinalSecondWorldStoryId?.(finalStoryId)!==true||window.isFinalSecondWorldStoryId?.("not-final-story")!==false)fail("THIRD_WORLD_FINALE_STORY_MATCHER",finalStoryId||null);
   const transitionProbe=JSON.parse(JSON.stringify(eligibleProbe)),transition=window.applyThirdWorldEntryState?.(transitionProbe);
   if(transition?.ok!==true||transition?.restoredLostGear!==1||window.currentWorldPhase?.(transitionProbe)!==3||window.worldProgressionEnabled?.(2,transitionProbe)!==false||window.worldProgressionEnabled?.(3,transitionProbe)!==true||transitionProbe.thirdWorld?.entered!==true||transitionProbe.thirdWorld?.dimensionalStrings!==0||transitionProbe.thirdWorld?.coreLevel!==0||transitionProbe.secondWorld?.entered!==true||transitionProbe.secondWorld?.darkMatter!==0||transitionProbe.secondWorld?.darkEnergy!==0||transitionProbe.secondWorld?.civilizationLevel!==10||transitionProbe.level!==1000||transitionProbe.exp!==54321||transitionProbe.equipment?.sentinel!=="equipment-kept"||transitionProbe.inventory?.some(row=>row?.id==="kept-item")!==true||transitionProbe.inventory?.some(row=>row?.id==="restored-item")!==true||transitionProbe.lostGear?.length!==0||transitionProbe.pendingBlackMarketEncounter!==false||transitionProbe.offline?.battleSamples?.length!==0||transitionProbe.offline?.pendingSettlement!==null||transitionProbe.offline?.farmMap!==null||transitionProbe.offline?.farmEnemy!==null||transitionProbe.dungeon?.sentinel!=="dungeon-kept"||transitionProbe.playerTitles?.sentinel!=="titles-kept")fail("THIRD_WORLD_ENTRY_STATE_MUTATION",{transition,transitionProbe});
   const blockedProbe=JSON.parse(JSON.stringify(eligibleProbe));blockedProbe.level=999;const blocked=window.thirdWorldEntryRequirements?.(blockedProbe);if(blocked?.eligible!==false||blocked?.completed!==6||blocked?.level?.ok!==false)fail("THIRD_WORLD_ENTRY_BLOCKED",blocked||null);
   const storyBlockedProbe=JSON.parse(JSON.stringify(eligibleProbe));storyBlockedProbe.storyProgress.completedStories=[];const storyBlocked=window.thirdWorldEntryRequirements?.(storyBlockedProbe);if(storyBlocked?.eligible!==false||storyBlocked?.mainline?.bossCompleted!==true||storyBlocked?.mainline?.finalStoryCompleted!==false||storyBlocked?.mainline?.ok!==false)fail("THIRD_WORLD_MAINLINE_DUAL_GATE",storyBlocked||null);
   if(Number(window.WORLD_PHASE_UI_VERSION)!==3||Number(window.WORLD_PHASE_SHARED_UI_VERSION)!==1)fail("WORLD_PHASE_SHARED_UI_VERSION",{ui:window.WORLD_PHASE_UI_VERSION,shared:window.WORLD_PHASE_SHARED_UI_VERSION});
   const groups={world:window.scriptLoadGroupFor?.("thirdworldphase.js"),gm:window.scriptLoadGroupFor?.("thirdworldgm.js"),integrity:window.scriptLoadGroupFor?.("thirdworldintegrity.js")};if(groups.world!=="world"||groups.gm!=="gm"||groups.integrity!=="integrity")fail("SCRIPT_LOAD_POLICY",groups);
   if(typeof newState==="function"){const fresh=newState();if(!fresh?.thirdWorld||fresh.thirdWorld.entered!==false||fresh.thirdWorld.bosses?.length!==10)fail("NEW_STATE_THIRD_WORLD",fresh?.thirdWorld||null);}
   if(typeof state!=="undefined"&&state?.thirdWorld?.entered===true&&(state?.secondWorld?.entered!==true||window.currentWorldPhase?.(state)!==3))fail("LIVE_STATE_INVARIANT",{secondWorld:state?.secondWorld?.entered,thirdWorld:state?.thirdWorld?.entered,phase:window.currentWorldPhase?.(state)});
  }catch(error){fail("EXCEPTION",String(error?.message||error));}
  return {version:4,passed:errors.length===0,errors,checkedAt:Date.now()};
 }
 window.THIRD_WORLD_PHASE_INTEGRITY_VERSION=4;window.THIRD_WORLD_PHASE_INTEGRITY_REPORT=runThirdWorldFoundationProbe();
 function run(options={}){
  const errors=[];
  Object.entries(EXPECTED_VERSIONS).forEach(([name,expected])=>{const actual=Number(window[name]);if(actual!==expected)errors.push({code:"VERSION_MISMATCH",name,expected,actual:Number.isFinite(actual)?actual:null});});
  REQUIRED_APIS.forEach(name=>{if(typeof window[name]!=="function")errors.push({code:"API_MISSING",name});});
  if(window.THIRD_WORLD_PHASE_INTEGRITY_REPORT?.passed!==true)errors.push({code:"THIRD_WORLD_PHASE_INTEGRITY",report:window.THIRD_WORLD_PHASE_INTEGRITY_REPORT||null});
  if(window.VIP_UNBOUNDED_INTEGRITY_REPORT?.passed!==true)errors.push({code:"VIP_UNBOUNDED_INTEGRITY",report:window.VIP_UNBOUNDED_INTEGRITY_REPORT||null});
  if(Number(window.SAVE_MIN_SUPPORTED_VERSION)!==1||String(window.SAVE_LEGACY_SUPPORT_MODE||"")!=="all-known")errors.push({code:"SAVE_LEGACY_POLICY",minSupportedVersion:window.SAVE_MIN_SUPPORTED_VERSION,mode:window.SAVE_LEGACY_SUPPORT_MODE});
  if(window.LEGACY_COMPATIBILITY_OWNER_REPORT?.passed!==true)errors.push({code:"LEGACY_COMPATIBILITY_OWNER",report:window.LEGACY_COMPATIBILITY_OWNER_REPORT||null});
  if(Number(window.LEGACY_SAVE_VERSION)!==13||Number(window.LEGACY_FIRST_WORLD_LEVEL_CAP)!==500||String(window.SAVE_SCHEMA_RUNTIME_OWNER||"")!=="savemigration"||String(window.LEVEL_CAP_RUNTIME_OWNER||"")!=="levelprogression"||String(window.ARENA_PROGRESS_RUNTIME_OWNER||"")!=="arenaByWorld")errors.push({code:"LEGACY_OWNER_POLICY"});
  if(!Array.isArray(window.CIVILIZATION_PLAYER_TITLE_DEFS)||window.CIVILIZATION_PLAYER_TITLE_DEFS.length!==10||!Array.isArray(window.UNIVERSE_CALAMITY_PLAYER_TITLE_DEFS)||window.UNIVERSE_CALAMITY_PLAYER_TITLE_DEFS.length!==10||!Array.isArray(window.MIRROR_PLAYER_TITLE_DEFS)||window.MIRROR_PLAYER_TITLE_DEFS.length!==6||!Array.isArray(window.PLAYER_TITLE_DEFS)||window.PLAYER_TITLE_DEFS.length!==26)errors.push({code:"TITLE_CATALOG_COUNT"});
  const arenaProfile=typeof window.getArenaVersionProfile==="function"?window.getArenaVersionProfile():null;if(!arenaProfile||arenaProfile.balanceVersion!==6||arenaProfile.rankBalanceVersion!==3||arenaProfile.assessmentRuleVersion!==4||arenaProfile.assessmentStateVersion!==4||arenaProfile.assessmentRuntimeVersion!==4)errors.push({code:"ARENA_PROFILE_MISMATCH",profile:arenaProfile});
  if(Number(window.SECOND_WORLD_BOSS_BASE_STATS?.base)!==2700||Number(window.SECOND_WORLD_BOSS_BASE_STATS?.ratio?.hp)!==12||Number(window.SECOND_WORLD_BOSS_BASE_STATS?.ratio?.atk)!==2||Number(window.SECOND_WORLD_BOSS_BASE_STATS?.ratio?.def)!==1)errors.push({code:"SECOND_WORLD_BOSS_FORMULA"});
  try{const legacy=window.saveCompatibilityFor?.({saveVersion:window.SAVE_MIN_SUPPORTED_VERSION}),supported=window.saveCompatibilityFor?.({saveVersion:window.SAVE_SCHEMA_VERSION}),future=window.saveCompatibilityFor?.({saveVersion:Number(window.SAVE_SCHEMA_VERSION)+1});if(legacy?.supported!==true||legacy?.isLegacy!==true||supported?.supported!==true||supported?.isFuture!==false||future?.supported!==false||future?.isFuture!==true)errors.push({code:"SAVE_COMPATIBILITY_POLICY",legacy,supported,future});}catch(error){errors.push({code:"SAVE_COMPATIBILITY_POLICY_PROBE",error:String(error?.message||error)});}
  try{const probe={saveVersion:window.SAVE_SCHEMA_VERSION,offline:{battleSampleVersion:0,battleSamples:[{sampleVersion:999}],farmMap:999,farmEnemy:9,avgBattleMs:-1,sampleCount:999,lastSettledAt:-1,maxObservedWallClock:-1,timeLockUntil:-1}};const first=window.normalizeOfflineSaveState?.(probe,{sourceVersion:window.SAVE_SCHEMA_VERSION,currentTime:123456789}),snapshot=JSON.stringify(probe.offline),second=window.normalizeOfflineSaveState?.(probe,{sourceVersion:window.SAVE_SCHEMA_VERSION,currentTime:123456789});if(!first||!second||probe.offline.battleSampleVersion!==3||probe.offline.battleSamples.length!==0||probe.offline.farmMap!==null||probe.offline.farmEnemy!==null||JSON.stringify(probe.offline)!==snapshot)errors.push({code:"OFFLINE_STATE_NORMALIZATION",offline:probe.offline});}catch(error){errors.push({code:"OFFLINE_STATE_NORMALIZATION_PROBE",error:String(error?.message||error)});}
  return {version:VERSION,phase:String(options.phase||"runtime"),passed:errors.length===0,errors,checkedAt:Date.now()};
 }
 window.CIVILIZATION_INTEGRITY_CONTRACT_VERSION=VERSION;window.CIVILIZATION_INTEGRITY_EXPECTED_VERSIONS=EXPECTED_VERSIONS;window.runCivilizationIntegrityContract=run;
})();