(function(){
 const CONFIG=window.MIRROR_DUNGEON_CONFIG;if(!CONFIG)throw new Error("Mirror dungeon config missing.");
 let mirrorTestHtml="";
 let mirrorTestResult=null;
 function pct(value,total){return total?Math.round(value/total*10000)/100:0;}
 function currentInfo(){return typeof mirrorDungeonStatus==="function"?mirrorDungeonStatus():{status:"idle",history:{bestWins:0,bestDate:null,miracleDates:[]}};}
 function resultBox(){const box=document.getElementById("gmMirrorTestResult");if(box)box.innerHTML=mirrorTestHtml;}
 function snapshot(){
  if(typeof window.normalizeMirrorCombatSnapshot!=="function")return typeof createMirrorCombatSnapshot==="function"?createMirrorCombatSnapshot():null;
  const character=typeof window.gmTestCharacterSnapshot==="function"?window.gmTestCharacterSnapshot():null;
  const stats=typeof window.gmTestPlayerStats==="function"?window.gmTestPlayerStats():null;
  const specs=typeof window.specializationLevelsSnapshot==="function"?window.specializationLevelsSnapshot(true):{};
  const marks=typeof window.markLevelsSnapshot==="function"?window.markLevelsSnapshot(true):{};
  const enhancements=typeof window.gmTestEnhancementSlots==="function"?Object.fromEntries(window.gmTestEnhancementSlots().map(type=>[type,window.gmTestEnhancementLevel(type)])):{};
  return window.normalizeMirrorCombatSnapshot({playerName:String(state?.playerName||"玩家"),level:Math.max(1,Math.floor(Number(character?.level)||1)),vipLevel:Math.max(0,Math.floor(Number(window.gmTestVipLevel)||0)),stats,specializations:specs,specializationBonuses:typeof window.mirrorSpecializationBonuses==="function"?window.mirrorSpecializationBonuses(specs):{},enhancementLevels:enhancements,marks,equipment:character?.equipment||{}});
 }
 function eventCounts(target,events){(events||[]).forEach(evt=>{if(evt.type==="combo")target.combo++;else if(evt.type==="counter")target.counter++;else if(evt.type==="drain")target.drain++;else if(evt.type==="attack"){if(evt.penetration)target.penetration++;if(evt.initiative)target.initiative++;}});}
 function simulate(runs){const snap=snapshot();if(!snap||typeof runMirrorCombatCore!=="function")return null;const totalPerRun=CONFIG.runBattles,summary={runs,totalBattles:runs*totalPerRun,totalWins:0,playerFirst:0,playerFirstWins:0,mirrorFirst:0,mirrorFirstWins:0,totalTurns:0,distribution:Array(totalPerRun+1).fill(0),events:{initiative:0,combo:0,penetration:0,counter:0,drain:0}};for(let r=0;r<runs;r++){let wins=0;for(let i=0;i<totalPerRun;i++){const out=runMirrorCombatCore(snap,{logs:false});if(out.win){wins++;summary.totalWins++;}if(out.firstActor==="player"){summary.playerFirst++;if(out.win)summary.playerFirstWins++;}else{summary.mirrorFirst++;if(out.win)summary.mirrorFirstWins++;}summary.totalTurns+=Math.max(0,Number(out.turns)||0);eventCounts(summary.events,out.events);}summary.distribution[wins]++;}return summary;}
 function seededRng(seed,first){let firstPending=true,x=seed>>>0;return function(){if(firstPending){firstPending=false;return first;}x=(Math.imul(x,1664525)+1013904223)>>>0;return x/4294967296;};}
 function symmetryRegression(pairCount=64){
  const base=snapshot();if(!base||typeof normalizeMirrorCombatSnapshot!=="function"||typeof runMirrorCombatCore!=="function")return null;
  const probe=JSON.parse(JSON.stringify(base)),max=Math.max(0,Number(window.SPECIALIZATION_MAX_LEVEL)||60);probe.specializations={...(probe.specializations||{}),initiative:max,combo:max,penetration:max,counter:max,drain:max};if(typeof window.mirrorSpecializationBonuses==="function")probe.specializationBonuses=window.mirrorSpecializationBonuses(probe.specializations);probe.marks=Object.fromEntries(Array.from(window.MARK_KEYS||[]).map(key=>[key,Number(window.MARK_MAX_LEVEL)||10]));const snap=normalizeMirrorCombatSnapshot(probe),errors=[];
  for(let seed=1;seed<=pairCount;seed++){
   const a=runMirrorCombatCore(snap,{logs:false,rng:seededRng(seed,.25)}),b=runMirrorCombatCore(snap,{logs:false,rng:seededRng(seed,.75)});
   if(a.firstActor!=="player"||b.firstActor!=="mirror")errors.push(`seed ${seed} 先攻異常`);
   if(a.winner===b.winner)errors.push(`seed ${seed} 勝者未互換`);
   if(a.turns!==b.turns)errors.push(`seed ${seed} 回合數不一致`);
   if(a.playerHp!==b.mirrorHp||a.mirrorHp!==b.playerHp)errors.push(`seed ${seed} HP 未鏡像互換`);
   if(a.events?.at(-1)?.type!=="battleEnd"||b.events?.at(-1)?.type!=="battleEnd")errors.push(`seed ${seed} battleEnd 異常`);
  }
  return {pairs:pairCount,passed:errors.length===0,errors};
 }
 function distributionHtml(s){return s.distribution.map((count,wins)=>count?`<span>${wins}勝：${count}次</span>`:"").filter(Boolean).join("　");}
 function summaryHtml(s,label){const avg=Math.round(s.totalWins/s.runs*100)/100,totalRate=pct(s.totalWins,s.totalBattles),pFirst=pct(s.playerFirstWins,s.playerFirst),mFirst=pct(s.mirrorFirstWins,s.mirrorFirst),avgTurns=Math.round(s.totalTurns/s.totalBattles*100)/100;return `<div class="notice"><b>鏡像戰・${label}</b><div class="muted gm-test-context">純沙盒模擬，不消耗今日鏡像戰、不發 VIP、不更新歷史或神蹟。</div><div class="stats" style="margin-top:10px;grid-template-columns:repeat(auto-fit,minmax(135px,1fr))"><div class="stat">平均每次勝場<b>${avg}</b></div><div class="stat">玩家總勝率<b>${totalRate}%</b></div><div class="stat">玩家先攻時勝率<b>${pFirst}%</b></div><div class="stat">鏡像先攻時玩家勝率<b>${mFirst}%</b></div><div class="stat">平均回合<b>${avgTurns}</b></div></div><div class="muted" style="margin-top:9px">勝場分布：${distributionHtml(s)}</div><div class="muted" style="margin-top:6px">觸發統計：先制 ${s.events.initiative}・連擊 ${s.events.combo}・穿透 ${s.events.penetration}・反擊 ${s.events.counter}・汲取 ${s.events.drain}</div></div>`;}
 window.gmMirrorTest=function(runs){const n=runs===100?100:1,button=document.getElementById(n===100?"gmMirrorTest100":"gmMirrorTest1");if(button){button.disabled=true;button.textContent="測試中…";}setTimeout(()=>{try{const s=simulate(n);if(s)mirrorTestResult={...(mirrorTestResult||{}),simulation:JSON.parse(JSON.stringify(s))};mirrorTestHtml=s?summaryHtml(s,n===100?`100 次完整挑戰（${(100*CONFIG.runBattles).toLocaleString()} 場）`:`1 次完整挑戰（${CONFIG.runBattles} 場）`):`<div class="notice">鏡像戰核心尚未載入。</div>`;}catch(err){console.error("Mirror GM simulation failed",err);mirrorTestHtml=`<div class="notice">鏡像戰測試失敗，請重新整理後再試。</div>`;}resultBox();if(typeof window.gmPowerBenchmarkRefreshSummary==="function")window.gmPowerBenchmarkRefreshSummary();if(button){button.disabled=false;button.textContent=n===100?`測試 100 次（${(100*CONFIG.runBattles).toLocaleString()} 場）`:`測試 1 次（${CONFIG.runBattles} 場）`;}},20);};
 window.gmMirrorSymmetryTest=function(){const button=document.getElementById("gmMirrorSymmetry");if(button){button.disabled=true;button.textContent="回歸測試中…";}setTimeout(()=>{try{const result=symmetryRegression(64);if(result)mirrorTestResult={...(mirrorTestResult||{}),symmetry:JSON.parse(JSON.stringify(result))};mirrorTestHtml=result?`<div class="notice"><b>鏡像戰・64 組對稱回歸</b><div class="muted gm-test-context">使用固定亂數序列、滿級戰鬥專精與 10 枚 Lv.10 印記，成對交換先攻方，共測試 128 場；不修改正式資料。</div><div style="margin-top:10px;font-weight:800">${result.passed?"通過：64 / 64 組完全鏡像對稱":`未通過：${result.errors.length} 個異常`}</div>${result.errors.length?`<div class="muted" style="margin-top:6px">${result.errors.slice(0,8).join("；")}</div>`:""}</div>`:`<div class="notice">鏡像戰核心尚未載入。</div>`;}catch(err){console.error("Mirror symmetry regression failed",err);mirrorTestHtml=`<div class="notice">鏡像戰對稱回歸失敗。</div>`;}resultBox();if(typeof window.gmPowerBenchmarkRefreshSummary==="function")window.gmPowerBenchmarkRefreshSummary();if(button){button.disabled=false;button.textContent="對稱回歸（64 組）";}},20);};
 window.gmResetMirrorDungeonToday=function(){const active=typeof getMirrorDungeonActiveRun==="function"?getMirrorDungeonActiveRun():null;if(active?.active)return alert("鏡像戰正在進行中，無法重置今日狀態。");if(!confirm("重置今日鏡像戰後，可重新取得今天唯一一次正式挑戰機會。\n\n歷史最高與神蹟紀錄不會變更；重新進行的正式挑戰仍會正常發放獎勵並更新紀錄。\n\n確定重置？"))return;if(typeof resetMirrorDungeonToday!=="function")return alert("鏡像戰狀態模組尚未載入。");resetMirrorDungeonToday();if(typeof render==="function")render();};
 window.getMirrorGmTestHtml=function(){return mirrorTestHtml;};
 window.gmMirrorTestResultSnapshot=function(){return mirrorTestResult?JSON.parse(JSON.stringify(mirrorTestResult)):null;};
 window.gmClearMirrorTestResult=function(){mirrorTestHtml="";mirrorTestResult=null;return true;};
 function mirrorManageBody(){const info=currentInfo(),h=info.history||{},record=h.bestDate?`${Math.max(0,Number(h.bestWins)||0)} 勝（${h.bestDate}）`:"尚無紀錄",miracles=Array.isArray(h.miracleDates)?h.miracleDates.length:0;return `<div class="muted gm-hub-note">今日狀態：${info.status==="idle"?"尚未挑戰":"今日鏡像戰已結束／進行中"}　・　歷史最高：${record}　・　神蹟 ${miracles} 次</div><div class="controls"><button class="btn danger" onclick="gmResetMirrorDungeonToday()">重置今日鏡像戰</button></div>`;}
 window.gmMirrorManagementHtml=mirrorManageBody;
 function mirrorTestBody(){const result=typeof getMirrorGmTestHtml==="function"?getMirrorGmTestHtml():"";return `<div class="muted gm-hub-note">以目前 GM 測試角色建立鏡像快照。鏡像戰不分紀元；測試不消耗正式每日機會、不發 VIP、不更新歷史與神蹟。</div><div class="gm-test-button-grid"><button id="gmMirrorTest1" class="btn blue" onclick="gmMirrorTest(1)">測試 1 次（${CONFIG.runBattles} 場）</button><button id="gmMirrorTest100" class="btn blue" onclick="gmMirrorTest(100)">測試 100 次（${(100*CONFIG.runBattles).toLocaleString()} 場）</button><button id="gmMirrorSymmetry" class="btn blue" onclick="gmMirrorSymmetryTest()">對稱回歸（64 組）</button></div><div id="gmMirrorTestResult" style="margin-top:12px">${result}</div>`;}
 window.gmMirrorTestHtml=mirrorTestBody;
 window.GM_MIRROR_SHARED_TEST_CHARACTER_VERSION=1;
 window.GM_MIRROR_SUMMARY_EXPORT_VERSION=1;
})();