(function(){
 const MIRROR_DUNGEON_FINAL_INTEGRITY_VERSION=4;
 const SYMMETRY_SMOKE_PAIRS=8;
 const errors=[],warnings=[];
 const fail=(code,message,data=null)=>errors.push({code,message,data});
 const warn=(code,message,data=null)=>warnings.push({code,message,data});
 function clone(value){return JSON.parse(JSON.stringify(value));}
 function seededRng(seed,first){let firstPending=true,x=seed>>>0;return function(){if(firstPending){firstPending=false;return first;}x=(Math.imul(x,1664525)+1013904223)>>>0;return x/4294967296;};}
 if(window.MIRROR_DUNGEON_INTEGRITY?.passed!==true)fail("MIRROR_INTEGRITY","鏡像戰基礎 integrity 未通過",window.MIRROR_DUNGEON_INTEGRITY?.errors||null);
 if(window.PROJECT_RUNTIME_REPORT?.passed!==true)fail("PROJECT_RUNTIME","專案 runtime integrity 未通過",window.PROJECT_RUNTIME_REPORT?.errors||null);
 if(typeof window.normalizeMirrorDungeonState==="function"){
  const sameTs=Date.parse("2026-09-16T04:00:00Z"),beforeMidnight=Date.parse("2026-09-16T15:59:00Z"),afterMidnight=Date.parse("2026-09-16T16:01:00Z"),nextTs=Date.parse("2026-09-17T04:00:00Z");
  const interrupted={dungeon:{mirror:{history:{bestWins:0,bestDate:null,miracleDates:[]},daily:{dateKey:"2026-09-16",status:"running",challengeDate:"2026-09-16",startedAt:1,wins:0,losses:0,completedAt:0}}}};
  const same=clone(interrupted);window.normalizeMirrorDungeonState(same,sameTs,{recoverInterrupted:true});if(same.dungeon.mirror.daily.status!=="failed")fail("INTERRUPT_SAME_DAY","同日重新載入 running 應轉為 failed",same.dungeon.mirror.daily);
  const crossed=clone(interrupted);window.normalizeMirrorDungeonState(crossed,nextTs,{recoverInterrupted:true});if(crossed.dungeon.mirror.daily.status!=="idle"||crossed.dungeon.mirror.daily.dateKey!=="2026-09-17")fail("INTERRUPT_CROSS_DAY","跨日中斷應保留新一天可挑戰機會",crossed.dungeon.mirror.daily);
  const liveCross=clone(interrupted);window.normalizeMirrorDungeonState(liveCross,afterMidnight,{recoverInterrupted:false});if(liveCross.dungeon.mirror.daily.status!=="running"||liveCross.dungeon.mirror.daily.challengeDate!=="2026-09-16")fail("LIVE_CROSS_MIDNIGHT","同一工作階段跨午夜時，進行中的挑戰應維持開始日 running",liveCross.dungeon.mirror.daily);
  const zero={dungeon:{mirror:{history:{bestWins:0,bestDate:"2026-09-16",miracleDates:[]},daily:{dateKey:"2026-09-16",status:"completed",challengeDate:"2026-09-16",startedAt:1,wins:0,losses:20,completedAt:2}}}};window.normalizeMirrorDungeonState(zero,sameTs);if(zero.dungeon.mirror.history.bestDate!=="2026-09-16"||zero.dungeon.mirror.history.bestWins!==0||zero.dungeon.mirror.daily.status!=="completed")fail("ZERO_WIN_RECORD","正式 0 勝紀錄不應被當成尚無紀錄",zero.dungeon.mirror);
  const miracles={dungeon:{mirror:{history:{bestWins:20,bestDate:"2026-09-16",miracleDates:["2026-09-16","2026-09-16"]},daily:{dateKey:"2026-09-16",status:"completed",challengeDate:"2026-09-16",startedAt:1,wins:20,losses:0,completedAt:2}}}};window.normalizeMirrorDungeonState(miracles,beforeMidnight);if(miracles.dungeon.mirror.history.miracleDates.length!==2)fail("MIRACLE_DUPLICATES","同一天多次 20 勝神蹟必須逐次保留，不得去重",miracles.dungeon.mirror.history);
  const invalidDates={dungeon:{mirror:{history:{bestWins:17,bestDate:"2026-02-30",miracleDates:["2026-99-99","2026-02-29"]},daily:{dateKey:"2026-13-01",status:"completed",challengeDate:"2026-02-30",startedAt:1,wins:17,losses:3,completedAt:2}}}};window.normalizeMirrorDungeonState(invalidDates,sameTs);if(invalidDates.dungeon.mirror.history.bestDate!==null||invalidDates.dungeon.mirror.history.bestWins!==0||invalidDates.dungeon.mirror.history.miracleDates.length!==0)fail("INVALID_HISTORY_DATE","非法日期應從歷史資料清除",invalidDates.dungeon.mirror.history);if(invalidDates.dungeon.mirror.daily.status!=="idle"||invalidDates.dungeon.mirror.daily.dateKey!=="2026-09-16")fail("INVALID_DAILY_DATE","非法 daily 日期應回復當日 idle",invalidDates.dungeon.mirror.daily);
  const repairedMiracle={dungeon:{mirror:{history:{bestWins:12,bestDate:"2026-09-10",miracleDates:["2026-09-12","2026-09-12"]},daily:{dateKey:"2026-09-16",status:"idle"}}}};window.normalizeMirrorDungeonState(repairedMiracle,sameTs);if(repairedMiracle.dungeon.mirror.history.bestWins!==20||repairedMiracle.dungeon.mirror.history.bestDate!=="2026-09-12"||repairedMiracle.dungeon.mirror.history.miracleDates.length!==2)fail("HISTORY_MIRACLE_REPAIR","神蹟紀錄應自動修復歷史最高且保留重複日期",repairedMiracle.dungeon.mirror.history);
  const repairedLegacy20={dungeon:{mirror:{history:{bestWins:20,bestDate:"2026-09-11",miracleDates:[]},daily:{dateKey:"2026-09-16",status:"idle"}}}};window.normalizeMirrorDungeonState(repairedLegacy20,sameTs);if(repairedLegacy20.dungeon.mirror.history.miracleDates.length!==1||repairedLegacy20.dungeon.mirror.history.miracleDates[0]!=="2026-09-11")fail("HISTORY_LEGACY_20_REPAIR","舊 20 勝最高紀錄應補回至少一筆神蹟日期",repairedLegacy20.dungeon.mirror.history);
  const oldCompleted={dungeon:{mirror:{history:{bestWins:17,bestDate:"2026-09-10",miracleDates:[]},daily:{dateKey:"2026-09-16",status:"completed",challengeDate:"2026-09-16",startedAt:1,wins:17,losses:3,completedAt:2}}}};window.normalizeMirrorDungeonState(oldCompleted,nextTs);if(oldCompleted.dungeon.mirror.daily.status!=="idle"||oldCompleted.dungeon.mirror.history.bestWins!==17||oldCompleted.dungeon.mirror.history.bestDate!=="2026-09-10")fail("DAILY_RESET_HISTORY","跨日重置不得清除歷史最高",oldCompleted.dungeon.mirror);
 }else fail("STATE_NORMALIZER_MISSING","normalizeMirrorDungeonState 未載入");
 if(typeof window.createMirrorCombatSnapshot==="function"&&typeof window.normalizeMirrorCombatSnapshot==="function"&&typeof window.runMirrorCombatCore==="function"){
  try{const base=window.createMirrorCombatSnapshot(),probe=clone(base),max=Math.max(0,Number(window.SPECIALIZATION_MAX_LEVEL)||60);probe.specializations={...(probe.specializations||{}),initiative:max,combo:max,penetration:max,counter:max,drain:max};if(typeof window.mirrorSpecializationBonuses==="function")probe.specializationBonuses=window.mirrorSpecializationBonuses(probe.specializations);const snap=window.normalizeMirrorCombatSnapshot(probe);let pairs=0;for(let seed=1;seed<=SYMMETRY_SMOKE_PAIRS;seed++){const a=window.runMirrorCombatCore(snap,{logs:false,rng:seededRng(seed,.25)}),b=window.runMirrorCombatCore(snap,{logs:false,rng:seededRng(seed,.75)});if(a.firstActor!=="player"||b.firstActor!=="mirror")fail("FIRST_ACTOR_PAIR",`seed ${seed} 先攻配對異常`,{a:a.firstActor,b:b.firstActor});if(a.winner===b.winner)fail("SYMMETRY_PAIR",`seed ${seed} 交換先攻後勝者未鏡像互換`,{a:a.winner,b:b.winner});if(a.turns!==b.turns)fail("SYMMETRY_TURNS",`seed ${seed} 鏡像配對回合數不一致`,{a:a.turns,b:b.turns});if(a.playerHp!==b.mirrorHp||a.mirrorHp!==b.playerHp)fail("SYMMETRY_HP",`seed ${seed} 鏡像配對最終 HP 未互換`,{a:{playerHp:a.playerHp,mirrorHp:a.mirrorHp},b:{playerHp:b.playerHp,mirrorHp:b.mirrorHp}});const endA=a.events?.[a.events.length-1],endB=b.events?.[b.events.length-1];if(endA?.type!=="battleEnd"||endB?.type!=="battleEnd")fail("BATTLE_END_EVENT",`seed ${seed} battleEnd 不是最後事件`);pairs++;}if(pairs!==SYMMETRY_SMOKE_PAIRS)fail("SYMMETRY_PAIR_COUNT",`應完成 ${SYMMETRY_SMOKE_PAIRS} 組 smoke test，實際 ${pairs}`);}catch(err){fail("SYMMETRY_EXCEPTION","Mirror Combat 對稱 smoke test 發生例外",String(err?.message||err));}
 }else fail("COMBAT_API_MISSING","Mirror Combat 最終回歸所需 API 未完整載入");
 const cfg=window.MIRROR_DUNGEON_CONFIG;
 if(cfg&&typeof window.mirrorDungeonRewardForWins==="function")for(let w=0;w<=cfg.runBattles;w++){const expected=cfg.rewardPerWinSquared*w*w,actual=window.mirrorDungeonRewardForWins(w);if(actual!==expected)fail("REWARD_TABLE",`${w} 勝獎勵應為 ${expected}，實際 ${actual}`);}
 if(cfg&&typeof window.mirrorDungeonResultComment==="function"){const comments=new Set(Array.from({length:cfg.runBattles+1},(_,w)=>window.mirrorDungeonResultComment(w)));if(comments.size!==cfg.runBattles+1)fail("COMMENT_COUNT",`0～${cfg.runBattles} 勝評語應全部不同，實際 ${comments.size}`);}
 if(typeof window.requestMirrorContinuousStop!=="undefined"||typeof window.stopMirrorCombatRun!=="undefined")fail("STOP_API","正式鏡像戰不得存在停止 API");
 if(Number(window.DUNGEON_PREP_RETURN_UX_VERSION)<2)fail("RETURN_UX","懸賞／競技準備頁正式返回導覽未載入");
 if(Number(window.DUNGEON_UI_EXTENSION_VERSION)!==1)fail("DUNGEON_UI_EXTENSION","副本 UI 擴充 owner 未載入");
 if(Number(window.GM_HUB_EXTENSION_VERSION)!==1)fail("GM_HUB_EXTENSION","GM Hub 擴充 owner 未載入");
 if(Number(window.MIRROR_DUNGEON_GUIDE_VERSION)!==2)fail("GUIDE","鏡像戰說明模組未載入");
 if(typeof window.getNewStateNormalizerCount==="function"&&Number(window.getNewStateNormalizerCount())!==4)fail("NORMALIZER_COUNT",`正式 newState normalizer 應維持 4，實際 ${window.getNewStateNormalizerCount()}`);
 const viewport=document.querySelector('meta[name="viewport"]')?.getAttribute("content")||"";if(!viewport.includes("width=device-width"))warn("VIEWPORT","行動版 viewport 設定異常");
 const report={passed:errors.length===0,clean:errors.length===0&&warnings.length===0,errors,warnings,checkedAt:Date.now(),symmetryPairs:SYMMETRY_SMOKE_PAIRS};window.MIRROR_DUNGEON_FINAL_INTEGRITY_VERSION=MIRROR_DUNGEON_FINAL_INTEGRITY_VERSION;window.MIRROR_DUNGEON_FINAL_INTEGRITY=report;if(errors.length)console.error("[Mirror Dungeon Final Integrity]",errors);else if(warnings.length)console.warn("[Mirror Dungeon Final Integrity]",warnings);else console.info("[Mirror Dungeon Final Integrity] passed");
})();