(function(){
 const VERSION=21;
 const errors=[],warnings=[];
 const fail=(code,message,data=null)=>errors.push({code,message,data});
 const warn=(code,message,data=null)=>warnings.push({code,message,data});
 const hardReports=[["GM_BATCH16_INTEGRITY",window.GM_BATCH16_INTEGRITY],["OFFLINE_SAMPLE_OWNER_INTEGRITY",window.OFFLINE_SAMPLE_OWNER_INTEGRITY],["ENHANCEMENT_WORLD3_INTEGRITY",window.ENHANCEMENT_WORLD3_INTEGRITY]];
 hardReports.forEach(([name,report])=>{if(report?.passed!==true)fail("CURRENT_SUBSYSTEM_REPORT",`${name} 未通過或未載入`,report?.errors||null);});
 const legacyDiagnostics=[["CALAMITY_STATE_INTEGRITY",window.CALAMITY_STATE_INTEGRITY],["COMBAT_MARK_INTEGRITY",window.COMBAT_MARK_INTEGRITY],["COMBAT_MARK_FX_INTEGRITY",window.COMBAT_MARK_FX_INTEGRITY],["COMBAT_SPEED_INTEGRITY",window.COMBAT_SPEED_INTEGRITY],["PLAYER_TITLE_UNIVERSE_VISUAL_INTEGRITY_REPORT",window.PLAYER_TITLE_UNIVERSE_VISUAL_INTEGRITY_REPORT],["CIVILIZATION_LEVEL_INTEGRITY_REPORT",window.CIVILIZATION_LEVEL_INTEGRITY_REPORT],["THIRD_WORLD_DATA_INTEGRITY",window.THIRD_WORLD_DATA_INTEGRITY],["SECOND_WORLD_MAINLINE_INTEGRITY",window.SECOND_WORLD_MAINLINE_INTEGRITY],["SECOND_WORLD_CALAMITY_UI_INTEGRITY",window.SECOND_WORLD_CALAMITY_UI_INTEGRITY],["SECOND_WORLD_CALAMITY_FULL_INTEGRITY_REPORT",window.SECOND_WORLD_CALAMITY_FULL_INTEGRITY_REPORT],["ENHANCEMENT_FINAL_INTEGRITY",window.ENHANCEMENT_FINAL_INTEGRITY],["BOSS_CONTINUOUS_INTEGRITY",window.BOSS_CONTINUOUS_INTEGRITY],["THIRD_WORLD_SUBSYSTEM_INTEGRITY",window.THIRD_WORLD_SUBSYSTEM_INTEGRITY]];
 legacyDiagnostics.forEach(([name,report])=>{if(report&&report.passed!==true)warn("LEGACY_DIAGNOSTIC",`${name} 仍含歷史規則失敗；保留診斷但不作正式 hard gate`,report.errors||null);});
 const canonical=window.runCanonicalCivilizationIntegrityContract;
 if(Number(window.CIVILIZATION_INTEGRITY_CONTRACT_VERSION)!==3||typeof canonical!=="function")fail("INTEGRITY_CONTRACT_MISSING","Canonical Integrity Contract V3 未載入",{version:window.CIVILIZATION_INTEGRITY_CONTRACT_VERSION,api:typeof canonical});
 else{const contract=canonical({phase:"runtime"});if(contract?.passed!==true)fail("INTEGRITY_CONTRACT","Canonical Integrity Contract 未通過",contract?.errors||null);}
 const expectedMaps=Array.isArray(WORLD_REGIONS)?WORLD_REGIONS.reduce((max,r)=>Math.max(max,(Number(r?.mapEnd)||-1)+1,0),0):0;
 if(!Array.isArray(MAPS)||MAPS.length!==expectedMaps)fail("WORLD_MAP_COUNT",`MAPS 應為 ${expectedMaps} 張，實際 ${Array.isArray(MAPS)?MAPS.length:"非陣列"}`);
 if(window.WORLD_MAP_REGISTRATION_REPORT?.passed!==true)fail("WORLD_MAP_REGISTRY","世界地圖固定註冊檢查未通過",window.WORLD_MAP_REGISTRATION_REPORT?.errors||null);
 if(window.WORLD_NAMING_REPORT?.errors?.length)fail("WORLD_NAMING","世界資料硬錯誤",window.WORLD_NAMING_REPORT.errors);
 const required=["normalizeSaveState","migrateSave","load","markSaveLoadResolved","saveWriteGuardStatus","saveCompatibilityFor","assertSaveVersionSupported","normalizeOfflineSaveState","normalizePlayerTitleState","getArenaVersionProfile","getArenaRankCurveForWorld","civilizationCombatDamageMultiplier","gameGuideCategoriesForState","currentWorldPhase","effectiveLevelCap","effectiveExpNeed","dungeonModeAvailability"];
 required.forEach(name=>{if(typeof window[name]!=="function")fail("MISSING_FUNCTION",`必要函式 ${name} 未載入`);});
 if(Number(window.SAVE_WRITE_GUARD_VERSION)!==1)fail("SAVE_WRITE_GUARD","本機存檔寫入保護 V1 未載入",window.SAVE_WRITE_GUARD_VERSION);
 if(Number(window.SAVE_FUTURE_VERSION_GUARD_VERSION)!==1)fail("SAVE_FUTURE_VERSION_GUARD","未來版本存檔保護 V1 未載入",window.SAVE_FUTURE_VERSION_GUARD_VERSION);
 if(Number(window.SAVE_LEGACY_SUPPORT_POLICY_VERSION)!==1||Number(window.SAVE_MIN_SUPPORTED_VERSION)!==1||String(window.SAVE_LEGACY_SUPPORT_MODE||"")!=="all-known")fail("SAVE_LEGACY_POLICY","舊存檔支援政策異常",{version:window.SAVE_LEGACY_SUPPORT_POLICY_VERSION,min:window.SAVE_MIN_SUPPORTED_VERSION,mode:window.SAVE_LEGACY_SUPPORT_MODE});
 if(Number(window.OFFLINE_STATE_NORMALIZATION_VERSION)<4)fail("OFFLINE_STATE_OWNER","Offline state normalization 至少應為 V4",window.OFFLINE_STATE_NORMALIZATION_VERSION);
 try{const current=Number(window.SAVE_SCHEMA_VERSION)||0,legacy=window.saveCompatibilityFor?.({saveVersion:window.SAVE_MIN_SUPPORTED_VERSION}),supported=window.saveCompatibilityFor?.({saveVersion:current}),future=window.saveCompatibilityFor?.({saveVersion:current+1});let threw=false;try{window.assertSaveVersionSupported?.({saveVersion:current+1},{label:"Runtime 測試存檔"});}catch(error){threw=error?.code==="FUTURE_SAVE_VERSION";}if(legacy?.supported!==true||legacy?.isLegacy!==true||supported?.supported!==true||future?.isFuture!==true||future?.supported!==false||!threw)fail("SAVE_COMPATIBILITY_POLICY_PROBE","存檔相容政策 probe 異常",{legacy,supported,future,threw});}catch(error){fail("SAVE_COMPATIBILITY_POLICY_PROBE","存檔相容政策 probe 執行失敗",String(error?.message||error));}
 try{const expectedSample=Math.max(1,Math.floor(Number(window.OFFLINE_BATTLE_SAMPLE_VERSION)||0)),probe={saveVersion:Number(window.SAVE_SCHEMA_VERSION)||1,offline:{battleSampleVersion:0,battleSamples:[{sampleVersion:999}],farmMap:999,farmEnemy:9,avgBattleMs:-1,sampleCount:999,lastSettledAt:-1,maxObservedWallClock:-1,timeLockUntil:-1}};const first=window.normalizeOfflineSaveState?.(probe,{sourceVersion:probe.saveVersion,currentTime:123456789}),snapshot=JSON.stringify(probe.offline),second=window.normalizeOfflineSaveState?.(probe,{sourceVersion:probe.saveVersion,currentTime:123456789});if(!first||!second||Number(probe.offline.battleSampleVersion)!==expectedSample||probe.offline.battleSamples.length!==0||probe.offline.farmMap!==null||probe.offline.farmEnemy!==null||JSON.stringify(probe.offline)!==snapshot)fail("OFFLINE_STATE_OWNER_PROBE","Offline normalization owner probe 異常",probe.offline);}catch(error){fail("OFFLINE_STATE_OWNER_PROBE","Offline normalization owner probe 執行失敗",String(error?.message||error));}
 try{const higher={level:1000,secondWorld:{entered:true},thirdWorld:{entered:true,dimensionalStrings:0}},arena=window.dungeonModeAvailability?.("arena",higher),bounty=window.dungeonModeAvailability?.("bounty",higher);if(window.currentWorldPhase?.(higher)!==3||window.effectiveLevelCap?.(higher)!==2000)fail("THIRD_WORLD_ROUTING","高維紀元 routing／等級上限異常",{phase:window.currentWorldPhase?.(higher),cap:window.effectiveLevelCap?.(higher)});if(arena?.visible!==true||arena?.enabled!==true||bounty?.visible!==false)fail("THIRD_WORLD_DUNGEON_POLICY","高維副本正式 policy 異常",{arena,bounty});const profile=window.getArenaVersionProfile?.();if(!profile||Number(profile.balanceVersion)!==7||Number(profile.rankBalanceVersion)!==4||Number(profile.assessmentRuleVersion)!==4)fail("ARENA_PROFILE","Arena canonical profile 異常",profile||null);const curve=window.getArenaRankCurveForWorld?.(2);if(Number(curve?.hp?.base)!==1.68||Number(curve?.damage?.base)!==1.52||Number(curve?.def?.base)!==1.11)fail("ARENA_UNIVERSE_CURVE","第二紀元 Arena 曲線異常",curve||null);}catch(error){fail("CURRENT_BEHAVIOR_PROBE","現行行為 probe 執行失敗",String(error?.message||error));}
 if(typeof state!=="undefined"&&state&&Number(state.saveVersion)!==Number(window.SAVE_SCHEMA_VERSION))fail("STATE_SCHEMA",`state.saveVersion ${state.saveVersion} 與正式 schema ${window.SAVE_SCHEMA_VERSION} 不一致`);
 const report={version:VERSION,contractVersion:Number(window.CIVILIZATION_INTEGRITY_CONTRACT_VERSION)||0,passed:errors.length===0,clean:errors.length===0&&warnings.length===0,errors,warnings,legacyDiagnostics:legacyDiagnostics.map(([name,report])=>({name,passed:report?.passed===true,loaded:!!report})),checkedAt:Date.now()};
 window.PROJECT_RUNTIME_INTEGRITY_VERSION=VERSION;window.PROJECT_RUNTIME_REPORT=report;
 if(errors.length)console.error("[文明戰線] Runtime integrity error",errors);else if(warnings.length)console.warn("[文明戰線] Runtime integrity passed with legacy diagnostic warnings",warnings);else console.info("[文明戰線] Runtime integrity passed");
})();
