(function(){
 const INTRO_STORY_ID="earth-prologue",MODAL_ID="civilizationStarterGearModal";let resumeQueued=false,starterGearOpen=false;
 function loadedFromExistingSave(){return window.LAST_SAVE_LOAD_REPORT?.hadRaw===true;}
 function galaxyBossStoryId(mapIdx){const index=Math.floor(Number(mapIdx));if(!Number.isInteger(index)||index<0||!Array.isArray(WORLD_REGIONS))return null;const region=WORLD_REGIONS.find(r=>index>=Number(r.mapStart)&&index<=Number(r.mapEnd));return region?`${region.id}-boss-${index-Number(region.mapStart)+1}`:null;}
 function galaxyBossMapIndexForStory(id){if(typeof id!=="string"||!Array.isArray(WORLD_REGIONS))return null;for(const region of WORLD_REGIONS){for(let i=Number(region.mapStart);i<=Number(region.mapEnd);i++)if(galaxyBossStoryId(i)===id)return i;}return null;}
 function universeBossStoryId(index){return typeof window.universeStoryIdForBossIndex==="function"?window.universeStoryIdForBossIndex(index):null;}
 function universeBossIndexForStory(id){return typeof window.universeBossIndexForStoryId==="function"?window.universeBossIndexForStoryId(id):null;}
 function availableStoryRegions(){return Array.isArray(window.CIVILIZATION_STORY_REGIONS)?window.CIVILIZATION_STORY_REGIONS:[];}
 function migrationOptions(options={}){return {introStoryId:INTRO_STORY_ID,fresh:options.fresh===true,legacy:options.legacy===true||(!options.fresh&&loadedFromExistingSave()),skipBackfill:options.skipBackfill===true,regions:availableStoryRegions(),stories:window.CIVILIZATION_STORIES||{},bossMapIndexForStory:galaxyBossMapIndexForStory};}
 function normalizeProgress(target,options={}){const migration=window.civilizationStoryMigration;if(!migration?.migrate){console.error("Story migration module is unavailable");return target;}migration.migrate(target,migrationOptions(options));return target;}
 function backfillAvailableHistory(target){return window.civilizationStoryMigration?.backfillAvailableHistory?.(target,migrationOptions())===true;}
 function normalizeFreshState(target){normalizeProgress(target,{fresh:true});setTimeout(queueResume,0);return target;}if(typeof registerNewStateNormalizer==="function")registerNewStateNormalizer(normalizeFreshState);window.normalizeStoryProgressState=normalizeProgress;
 function readProgress(){const p=state?.storyProgress;return p&&typeof p==="object"&&!Array.isArray(p)?p:null;}
 function ensureProgress(options={}){normalizeProgress(state,options);return readProgress();}
 function persist(){if(typeof save==="function")save(false);}
 function setPending(id){const p=ensureProgress();if(!p)return false;p.pendingStory=id||null;persist();return true;}
 function completeStory(id){const p=ensureProgress();if(!p)return false;const first=!p.completedStories.includes(id);if(first)p.completedStories.push(id);if(p.pendingStory===id)p.pendingStory=null;if(id===INTRO_STORY_ID){p.introCompleted=true;state.introSeen=true;}persist();if(first&&typeof window.showCivilizationCalamityUnlockNoticeForStory==="function")queueMicrotask(()=>window.showCivilizationCalamityUnlockNoticeForStory(id));if(first&&typeof window.handleSecondWorldStoryCompletion==="function")window.handleSecondWorldStoryCompletion(id);return true;}
 function queueStory(id){if(!id||!window.CIVILIZATION_STORIES?.[id])return null;normalizeProgress(state,{skipBackfill:true});const p=state.storyProgress;if(!p||p.completedStories.includes(id)||p.pendingStory&&p.pendingStory!==id)return null;if(p.pendingStory!==id){p.pendingStory=id;normalizeProgress(state);persist();}queueResume();return id;}
 function queueBossStory(mapIdx){return queueStory(galaxyBossStoryId(mapIdx));}
 function queueUniverseBossStory(bossIndex){return queueStory(universeBossStoryId(bossIndex));}
 function starterTypes(){return Array.isArray(EQUIPMENT_TYPES)?EQUIPMENT_TYPES:[];}
 function allStarterGearMissing(){const types=starterTypes();return !!types.length&&types.every(type=>!state?.equipment?.[type]);}
 function hasNoMainProgress(){if(Number(state?.level)!==1||Number(state?.exp)!==0||Number(state?.gold)!==0||Number(state?.unlockedMap)!==0)return false;if(Array.isArray(state?.inventory)&&state.inventory.length)return false;if(Array.isArray(state?.bossKilled)&&state.bossKilled.some(Boolean))return false;return true;}
 function brokenOnboardingGearState(){const p=readProgress();return !!p&&p.introCompleted===true&&p.starterGearReceived===true&&p.completedStories.length===1&&p.completedStories[0]===INTRO_STORY_ID&&hasNoMainProgress()&&allStarterGearMissing();}
 function ensureStarterEquipment(){const types=starterTypes();if(!types.length)return false;if(!state.equipment||typeof state.equipment!=="object"||Array.isArray(state.equipment))state.equipment={};const missing=types.filter(type=>!state.equipment[type]);if(!missing.length)return false;const generated=typeof starterEquipment==="function"?starterEquipment():null;missing.forEach(type=>{state.equipment[type]=generated?.[type]||makeItem(1,0,"normal",0,type);});if(typeof playerCombatStats==="function")state.hp=playerCombatStats().hp;persist();return true;}
 function repairBrokenOnboardingGear(){return brokenOnboardingGearState()?ensureStarterEquipment():false;}
 function esc(v){return String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));}
 function gearLabel(type){return typeof equipmentTypeLabel==="function"?equipmentTypeLabel(type):({weapon:"武器",helmet:"頭盔",armor:"鎧甲",shoes:"鞋子",accessory:"飾品"}[type]||type);}
 function gearText(item){if(!item)return "未取得";return typeof itemHtml==="function"?itemHtml(item,true):esc(item.name||"作戰裝備");}
 function ensureStarterGearModal(){let modal=document.getElementById(MODAL_ID);if(modal)return modal;modal=document.createElement("div");modal.id=MODAL_ID;modal.className="starter-gear-overlay";modal.setAttribute("role","dialog");modal.setAttribute("aria-modal","true");document.body.appendChild(modal);return modal;}
 function showStarterGear(){if(starterGearOpen)return true;ensureStarterEquipment();const modal=ensureStarterGearModal();modal.innerHTML=`<div class="starter-gear-card"><h2>文明戰線・作戰裝備發放</h2><div class="starter-gear-intro">正式編制已完成。文明戰線已為你配發第一套基礎作戰裝備，確認後即可進入主畫面。</div><div class="starter-gear-list">${starterTypes().map(type=>`<div class="starter-gear-row"><div class="starter-gear-type">${esc(gearLabel(type))}</div><div>${gearText(state.equipment?.[type])}</div></div>`).join("")}</div><div class="starter-gear-actions"><button class="btn primary" onclick="confirmStarterGearReceived()">領取裝備</button></div></div>`;modal.classList.add("open");starterGearOpen=true;return true;}
 window.confirmStarterGearReceived=function(){ensureStarterEquipment();const p=ensureProgress();if(!p)return;p.starterGearReceived=true;if(typeof normalizeCurrentSaveState==="function")normalizeCurrentSaveState();persist();document.getElementById(MODAL_ID)?.remove();starterGearOpen=false;if(typeof go==="function")go("home");};
 function storyOrder(id){if(id===INTRO_STORY_ID)return 0;const galaxy=galaxyBossMapIndexForStory(id);if(galaxy!=null)return galaxy+1;const universe=universeBossIndexForStory(id);return universe==null?100000:1001+universe;}
 function completedStoryRows(){const p=readProgress(),stories=window.CIVILIZATION_STORIES||{};return p?p.completedStories.filter(id=>stories[id]).map(id=>stories[id]).sort((a,b)=>storyOrder(a.id)-storyOrder(b.id)):[];}
 window.replayCompletedStory=function(id){const p=readProgress();if(!p||!p.completedStories.includes(id)||!window.CIVILIZATION_STORIES?.[id])return false;return typeof openStory==="function"?openStory(id):false;};
 function authReady(){return window.CIVILIZATION_AUTH_REQUIRED!==true||!!window.civilizationAuthSession;}function backgroundReady(){return window.BACKGROUND_PRELOAD_READY===true;}
 function openFormalStory(id){if(typeof openStory!=="function")return false;if(typeof isStoryOpen==="function"&&isStoryOpen())return true;return openStory(id,{onComplete:storyId=>{completeStory(storyId);queueResume();}});}
 function resume(){resumeQueued=false;if(typeof state==="undefined"||!state||!authReady()||!backgroundReady())return false;repairBrokenOnboardingGear();const p=ensureProgress();if(!p)return false;if(p.pendingStory){if(openFormalStory(p.pendingStory))return true;console.error("Pending story is unavailable",p.pendingStory);return false;}if(!p.introCompleted){setPending(INTRO_STORY_ID);return openFormalStory(INTRO_STORY_ID);}if(!p.starterGearReceived)return showStarterGear();return false;}
 function queueResume(){if(resumeQueued)return;resumeQueued=true;queueMicrotask(resume);}
 window.civilizationStoryProgress={version:11,introStoryId:INTRO_STORY_ID,normalize:normalizeProgress,resume:queueResume,get:()=>readProgress(),setPending,completeStory,queueBossStory,queueUniverseBossStory,bossStoryId:galaxyBossStoryId,universeBossStoryId,universeBossIndexForStory,backfillAvailableHistory:()=>{const changed=backfillAvailableHistory(state);if(changed)persist();return changed;},ensureStarterEquipment,completedStories:completedStoryRows};
 window.CIVILIZATION_STORY_PROGRESS_VERSION=11;
 if(typeof state!=="undefined"&&state){normalizeProgress(state);repairBrokenOnboardingGear();persist();}
 window.addEventListener("civilization-background-ready-before-reveal",queueResume);window.addEventListener("civilization-auth-ready",queueResume);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",queueResume,{once:true});else queueResume();
})();