(function(){
 let selectedRegionId=null,storyRecordEraView="universe";const INTRO_STORY_ID="earth-prologue";
 function esc(v){return String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));}
 function progress(){return window.civilizationStoryProgress?.get?.()||{completedStories:[]};}function stories(){return window.CIVILIZATION_STORIES||{};}function completedIds(){return new Set(Array.isArray(progress().completedStories)?progress().completedStories:[]);}
 function regions(){return storyRecordEraView==="universe"?(Array.isArray(window.CIVILIZATION_UNIVERSE_STORY_REGIONS)?window.CIVILIZATION_UNIVERSE_STORY_REGIONS:[]):(Array.isArray(window.CIVILIZATION_STORY_REGIONS)?window.CIVILIZATION_STORY_REGIONS:[]);}
 function visibleRegions(){const completed=completedIds();return regions().map(region=>({region,rows:(region.stories||[]).filter(row=>completed.has(row.id)&&stories()[row.id]).map(row=>stories()[row.id])})).filter(group=>group.rows.length);}
 function ensureSelection(groups){if(!groups.length){selectedRegionId=null;return null;}if(!groups.some(g=>g.region.id===selectedRegionId))selectedRegionId=groups[groups.length-1].region.id;return groups.find(g=>g.region.id===selectedRegionId)||groups[groups.length-1];}
 function prepareEntry(){const groups=visibleRegions();selectedRegionId=groups.length?groups[groups.length-1].region.id:null;return selectedRegionId;}
 function entryHtml(story){return `<button class="story-record-entry" onclick="replayCompletedStory('${esc(story.id)}')"><b>${esc(story.title||story.id)}</b><span>${esc(story.location||"")}</span></button>`;}
 function introHtml(completed){if(storyRecordEraView==="universe")return "";const intro=stories()[INTRO_STORY_ID];return intro&&completed.has(INTRO_STORY_ID)?`<div class="card story-record-card story-record-intro"><h2 class="story-record-chapter">序章</h2><div class="story-record-list">${entryHtml(intro)}</div></div>`:"";}
 function tabsHtml(groups){return groups.length?`<div class="card story-record-card"><h2 class="story-record-chapter">戰區紀錄</h2><div class="story-record-tabs">${groups.map(g=>`<button class="story-record-tab ${g.region.id===selectedRegionId?"active":""}" onclick="selectStoryRecordRegion('${esc(g.region.id)}')">${esc(g.region.name)}</button>`).join("")}</div></div>`:"";}
 function eraTabsHtml(){if(!(typeof window.isSecondWorldEntered==="function"&&window.isSecondWorldEntered()))return "";return `<div class="era-view-tabs story-record-era-tabs" role="tablist" aria-label="戰線紀錄紀元"><button class="era-view-tab ${storyRecordEraView==="universe"?"active":""}" onclick="setStoryRecordEraView('universe')">宇宙紀元</button><button class="era-view-tab ${storyRecordEraView==="galaxy-review"?"active":""}" onclick="setStoryRecordEraView('galaxy-review')">銀河紀元・回顧</button></div>`;}
 function selectedHtml(group){if(!group)return `<div class="card"><div class="story-record-empty">目前還沒有已完成的${storyRecordEraView==="universe"?"宇宙紀元":"銀河紀元"}戰線紀錄。</div></div>`;const chapter=String(group.rows[0]?.chapter||group.region.name||"戰線紀錄");return `<div class="card story-record-card story-record-selected"><h2 class="story-record-chapter">${esc(chapter)}</h2><div class="story-record-list">${group.rows.map(entryHtml).join("")}</div></div>`;}
 window.prepareStoryRecordEntry=prepareEntry;
 window.setStoryRecordEraView=function(value){storyRecordEraView=typeof window.isSecondWorldEntered==="function"&&window.isSecondWorldEntered()&&value==="universe"?"universe":"galaxy-review";prepareEntry();if(typeof render==="function")render();return storyRecordEraView;};window.getStoryRecordEraView=()=>storyRecordEraView;
 window.selectStoryRecordRegion=function(id){const groups=visibleRegions();if(!groups.some(g=>g.region.id===id))return false;selectedRegionId=id;if(typeof render==="function")render();return true;};
 window.storyRecordPageHtml=function(){const secondWorld=typeof window.isSecondWorldEntered==="function"&&window.isSecondWorldEntered();if(!secondWorld)storyRecordEraView="galaxy-review";const completed=completedIds(),groups=visibleRegions(),selected=ensureSelection(groups),back=typeof homeBackHtml==="function"?homeBackHtml():`<div class="back-home"><button class="btn back-btn" onclick="go('home')">← 返回主頁</button></div>`;const text=storyRecordEraView==="universe"?"查看宇宙紀元已完成的正式劇情；重播不會給予獎勵或改變進度。":"回顧銀河紀元已完成的正式劇情；重播不會給予獎勵或改變進度。";return `<div class="function-page story-record-page">${back}<div class="card"><h2>戰線紀錄</h2>${eraTabsHtml()}<div class="muted">${text}</div></div>${introHtml(completed)}${tabsHtml(groups)}${selectedHtml(selected)}</div>`;};
 window.STORY_RECORD_TABS_VERSION=7;window.STORY_RECORD_WORLD_REVIEW_VERSION=2;
})();