(function(){
 const VERSION=4;
 const STYLE_OWNER_VERSION=1;
 const STAGE_NAMES=["第一戰","第二戰","第三戰"];
 const baseOpenArenaDungeon=window.openArenaDungeon;
 const baseRenderArenaDungeon=window.renderArenaDungeon;
 const baseGetArenaCoreState=window.getArenaCoreState;
 let uiState={running:false,selectedMode:null,requestedRuns:0,lastMessage:""};
 function world3(){try{return typeof window.currentWorldPhase==="function"?window.currentWorldPhase(state)===3:state?.thirdWorld?.entered===true;}catch(e){return false;}}
 function esc(value){return String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));}
 function daily(){return typeof window.getThirdWorldArenaDailyStatus==="function"?window.getThirdWorldArenaDailyStatus():typeof window.dailyDungeonStatus==="function"?window.dailyDungeonStatus("arena"):{used:0,remaining:0,limit:20};}
 function runtime(){return typeof window.getThirdWorldArenaRuntimeState==="function"?window.getThirdWorldArenaRuntimeState():{status:"idle",requestedRuns:0,startedRuns:0,finishedRuns:0,fullClears:0,failedRuns:0,totalAwardedPoints:0,round:null,lastResult:null,daily:daily()};}
 function rewardPreview(){return typeof window.getThirdWorldArenaRewardPreview==="function"?window.getThirdWorldArenaRewardPreview():{actualPoints:0,scaledPoints:0};}
 function displayPlayer(){return typeof window.playerCombatStats==="function"?window.playerCombatStats():{hp:1,atk:1,def:0,crit:0,dodge:0};}
 function attemptsHtml(){const d=daily();return `今日競技場：<strong>${d.used} / ${d.limit}</strong>・剩餘 ${d.remaining} 輪`;}
 function buttonLabel(count){return count===1?"單場":`${count}場`;}
 function modeCard(id,title,description){const preview=rewardPreview(),choices=Array.isArray(window.THIRD_WORLD_ARENA_RUN_CHOICES)?window.THIRD_WORLD_ARENA_RUN_CHOICES:[1,5,10,20];const buttons=choices.map(count=>{const s=typeof window.getThirdWorldArenaRunChoiceStatus==="function"?window.getThirdWorldArenaRunChoiceStatus(count):{enabled:daily().remaining>=count};return `<button class="btn${count===1?"":" primary"}" ${s.enabled?"":"disabled"} onclick="startThirdWorldArenaUi('${id}',${count})">${buttonLabel(count)}</button>`;}).join("");return `<section class="w3-arena-mode"><h2>${title}</h2><p>${description}</p><div class="w3-arena-reward">三戰全勝可得：${Number(preview.actualPoints||0).toLocaleString()} VIP積分<small>未全勝時，依已通過戰數結算。</small></div><div class="w3-arena-actions">${buttons}</div></section>`;}
 function selectHtml(){return `<div class="function-page dungeon-page-shell w3-arena-shell"><div class="back-home"><button class="btn back-btn" onclick="go('dungeon')">← 返回副本列表</button></div><section class="w3-arena-panel"><div class="w3-arena-title">高維競技場</div><div class="w3-arena-attempts">${attemptsHtml()}</div><div class="w3-arena-note">每輪包含三次連續戰鬥，戰鬥間不會恢復生命。</div><div class="w3-arena-modes">${modeCard("fixed","定相競技場","三戰挑戰同一名高維存在。每一輪開始時將隨機決定對手。")}${modeCard("varied","異相競技場","三戰分別挑戰三名不同的高維存在。每輪都會重新組合對手。")}</div></section></div>`;}
 function progressHtml(rt){const stage=Math.max(0,Math.min(2,Number(rt?.round?.stageIndex)||0));return `<div class="w3-arena-progress">${STAGE_NAMES.map((name,i)=>`<div class="w3-arena-step ${i<stage?"done":i===stage?"current":""}">${name}</div>`).join("")}</div>`;}
 function lineupHtml(rt){const rows=rt?.round?.lineup||[];return `<div class="w3-arena-lineup">${rows.map((row,i)=>`<div><span>${STAGE_NAMES[i]}</span><b>${esc(row.name||"")}</b><small>${esc(row.typeLabel||"高維存在")}</small></div>`).join("")}</div>`;}
 function combatHtml(){const rt=runtime(),round=rt.round,e=round?.enemy||{},stats=displayPlayer(),hp=Math.max(0,Number(state?.hp)||0),maxHp=Math.max(1,Number(stats.hp)||1),mode=typeof window.getThirdWorldArenaMode==="function"?window.getThirdWorldArenaMode(rt.mode):null,stage=Math.max(0,Math.min(2,Number(round?.stageIndex)||0)),stop=rt.requestedRuns>1?`<div class="controls arena-actions"><button id="w3ArenaStopBtn" class="btn" onclick="requestThirdWorldArenaUiStop()">${rt.stopRequested?"本輪結束後停止":"停止後續場次"}</button></div>`:"";return `<section class="combat-screen arena-combat"><div class="combat-head arena-combat-head">【高維競技場・${esc(mode?.name||"")}】${STAGE_NAMES[stage]}・第 ${rt.startedRuns} / ${rt.requestedRuns} 輪</div>${progressHtml(rt)}${lineupHtml(rt)}<div class="combat-arena"><div class="combatant player arena-player" id="combatPlayerCard"><div class="combat-damage" id="combatPlayerDamage"></div><h2>${typeof window.playerIdentityNameHtml==="function"?window.playerIdentityNameHtml({compact:true}):esc(typeof currentPlayerName==="function"?currentPlayerName():"玩家")} Lv.${state.level}</h2><div class="big-hp"><div class="status-label"><span>HP</span><span id="combatPlayerHp">${Math.round(hp)} / ${Math.round(maxHp)}</span></div><div class="bar"><span class="hp" id="combatPlayerBar" style="width:${Math.max(0,Math.min(100,hp/maxHp*100))}%"></span></div></div></div><div class="combat-vs arena-vs">VS</div><div class="combatant enemy arena-enemy" id="combatEnemyCard"><div class="combat-damage" id="combatEnemyDamage"></div><div class="arena-combat-tier">${esc(e.typeLabel||"高維存在")}</div><h2 id="combatEnemyName">${esc(e.name||"高維投影")}</h2><div class="big-hp"><div class="status-label"><span>HP</span><span id="combatEnemyHp">${Math.round(Number(e.hp)||0)} / ${Math.round(Number(e.hp)||0)}</span></div><div class="bar"><span class="hp" id="combatEnemyBar" style="width:100%"></span></div></div></div></div><div class="combat-message arena-message" id="combatMessage">準備戰鬥</div>${stop}</section>`;}
 function actualHistoryRows(last){const history=Array.isArray(last?.history)?last.history:[],totalScaled=Math.max(0,Number(last?.scaledPoints)||0),totalAwarded=Math.max(0,Number(last?.awardedPoints)||0);if(totalScaled<=0||totalAwarded<=0)return history.map(row=>({...row,actualPoints:0}));let remaining=Math.floor(totalAwarded);const winners=history.filter(row=>row?.win),lastWinner=winners[winners.length-1]||null;return history.map(row=>{if(!row?.win)return {...row,actualPoints:0};if(row===lastWinner)return {...row,actualPoints:Math.max(0,remaining)};const actual=Math.max(0,Math.floor((Number(row.scaledPoints)||0)*totalAwarded/totalScaled));remaining=Math.max(0,remaining-actual);return {...row,actualPoints:actual};});}
 function resultHtml(){const rt=runtime(),last=rt.lastResult,d=daily(),mode=typeof window.getThirdWorldArenaMode==="function"?window.getThirdWorldArenaMode(rt.mode):null,lastRows=actualHistoryRows(last).map(row=>`${STAGE_NAMES[row.stageIndex]||"戰鬥"}：${row.win?`勝利　+${Number(row.actualPoints||0).toLocaleString()} VIP積分`:"敗北"}`).join("<br>");return `<div class="function-page dungeon-page-shell w3-arena-shell"><div class="back-home"><button class="btn back-btn" onclick="go('dungeon')">← 返回副本列表</button></div><section class="w3-arena-panel"><div class="w3-arena-title">${esc(mode?.name||"高維競技場")}・挑戰結算</div><div class="w3-arena-attempts">今日競技場：<strong>${d.used} / ${d.limit}</strong>・剩餘 ${d.remaining} 輪</div><div class="w3-arena-result-grid"><div><span>完成</span><b>${rt.finishedRuns} 輪</b></div><div><span>三戰全勝</span><b>${rt.fullClears} 輪</b></div><div><span>未全勝</span><b>${rt.failedRuns} 輪</b></div><div><span>總獲得</span><b>${Number(rt.totalAwardedPoints||0).toLocaleString()} VIP</b></div></div>${lastRows?`<div class="w3-arena-last"><b>最後一輪</b><br>${lastRows}<br>本輪實得：${Number(last?.awardedPoints||0).toLocaleString()} VIP積分</div>`:""}<div class="w3-arena-result-actions"><button class="btn primary" ${d.remaining>0?"":"disabled"} onclick="openArenaDungeon()">${d.remaining>0?"重新選擇":"今日競技場次數已用完"}</button><button class="btn" onclick="go('dungeon')">返回副本列表</button></div></section></div>`;}
 function errorHtml(){const rt=runtime();return `<div class="function-page dungeon-page-shell w3-arena-shell"><div class="back-home"><button class="btn back-btn" onclick="go('dungeon')">← 返回副本列表</button></div><section class="w3-arena-panel"><div class="w3-arena-title">高維競技場</div><div class="notice" style="margin-top:14px"><b>本輪結算未完成</b><div class="muted" style="margin-top:6px">獎勵系統尚未就緒，為避免錯誤發放，本輪已停止結算。重新整理後可依剩餘場次重新選擇。</div></div><div class="w3-arena-result-actions" style="margin-top:14px"><button class="btn primary" onclick="location.reload()">重新整理</button><button class="btn" onclick="go('dungeon')">返回副本列表</button></div><div class="muted" style="margin-top:8px;text-align:center">${esc(rt.stopReason||"")}</div></section></div>`;}
 function renderW3(){const rt=runtime();const mode=typeof window.getThirdWorldArenaMode==="function"?window.getThirdWorldArenaMode(rt.mode):null;if(mode?.id==="fixed"||mode?.id==="varied")window.CivilizationAudioScenes?.setContext?.("higher",mode.id==="fixed"?"arenaFixed":"arenaAlternate");if(rt.status==="combat"&&rt.round)return combatHtml();if(rt.status==="complete"||rt.status==="stopped")return resultHtml();if(rt.status==="error")return errorHtml();return selectHtml();}
 function sleep(ms){if(typeof window.backgroundProgressSleep==="function")return window.backgroundProgressSleep(ms,"arena");return new Promise(resolve=>setTimeout(resolve,ms));}
 function gap(){try{return typeof window.combatOuterGapMs==="function"?window.combatOuterGapMs("arena"):140;}catch(e){return 140;}}
 async function playCurrentStage(){const before=runtime(),round=before.round,enemy=round?.enemy?{...round.enemy}:null;if(before.status!=="combat"||!round||!enemy||typeof window.fightThirdWorldArenaCurrentStage!=="function")return false;const fight=window.fightThirdWorldArenaCurrentStage({deferSettlement:true});if(!fight?.ok||!fight?.combat){if(fight?.reason==="settlement-pending")return false;throw new Error(`World 3 Arena core fight failed: ${fight?.reason||"unknown"}`);}const combat=fight.combat,startHp=Math.max(0,Number(combat.startHp)||0);if(typeof window.animateStructuredCombatPresentation==="function"){try{await window.animateStructuredCombatPresentation({win:combat.win,logs:combat.logs||[],events:combat.events||[],e:combat.enemy||enemy,combatEndHp:combat.combatEndHp,turns:combat.turns},{mode:"arena",clearAfter:true,clearReason:"w3-arena-stage-end",startHp});}catch(error){console.warn("World 3 Arena structured presentation failed; continuing settlement.",error);}}if(typeof window.settleThirdWorldArenaStage!=="function")throw new Error("World 3 Arena settlement owner missing.");return window.settleThirdWorldArenaStage(combat);}
 async function playSelected(){if(uiState.running||!world3())return false;uiState.running=true;const startedBackground=uiState.requestedRuns>1&&typeof window.backgroundProgressStart==="function";if(startedBackground)window.backgroundProgressStart("arena",{mode:"third-world",runs:uiState.requestedRuns});try{while(world3()){let rt=runtime();if(rt.status==="ready"||rt.status==="between"){const begin=typeof window.beginThirdWorldArenaRound==="function"?window.beginThirdWorldArenaRound():{ok:false};if(!begin.ok)break;rt=runtime();if(typeof render==="function")render();await sleep(Math.min(80,gap()));}rt=runtime();if(rt.status!=="combat"||!rt.round)break;while(rt.status==="combat"&&rt.round){if(typeof battleBusy!=="undefined"&&battleBusy){await sleep(30);rt=runtime();continue;}if(typeof battleBusy!=="undefined")battleBusy=true;try{await playCurrentStage();}finally{if(typeof battleBusy!=="undefined")battleBusy=false;}rt=runtime();if(typeof render==="function")render();if(rt.status==="combat")await sleep(gap());}rt=runtime();if(rt.status==="between"){await sleep(gap());continue;}if(rt.status==="complete"||rt.status==="stopped"||rt.status==="error")break;}}catch(error){console.error("World 3 Arena UI run failed",error);uiState.lastMessage="競技場挑戰發生錯誤，請重新整理後再試。";if(typeof alert==="function")alert(uiState.lastMessage);}finally{uiState.running=false;if(startedBackground&&typeof window.backgroundProgressStop==="function")window.backgroundProgressStop("arena");if(typeof render==="function")render();}return true;}
 window.openArenaDungeon=function(...args){if(!world3())return typeof baseOpenArenaDungeon==="function"?baseOpenArenaDungeon.apply(this,args):false;if(typeof window.resetThirdWorldArenaRuntime==="function")window.resetThirdWorldArenaRuntime();uiState={running:false,selectedMode:null,requestedRuns:0,lastMessage:""};view="dungeon-arena";if(typeof render==="function")render();return true;};
 window.renderArenaDungeon=function(){if(world3())return renderW3();return typeof baseRenderArenaDungeon==="function"?baseRenderArenaDungeon():"";};
 window.getArenaCoreState=function(){if(world3()){const rt=runtime();return {phase:rt.status==="combat"?"combat":rt.status==="complete"||rt.status==="stopped"||rt.status==="error"?"result":"select",world:3,thirdWorld:true,runtime:rt,daily:daily()};}return typeof baseGetArenaCoreState==="function"?baseGetArenaCoreState():null;};
 window.startThirdWorldArenaUi=function(mode,count){if(!world3())return false;const start=typeof window.startThirdWorldArenaSession==="function"?window.startThirdWorldArenaSession(mode,count):{ok:false,reason:"core-missing"};if(!start.ok){if(typeof alert==="function")alert(start.reason==="insufficient-daily"?"今日剩餘競技場次數不足。":"無法開始高維競技場挑戰。");return false;}window.CivilizationAudioScenes?.notify?.("combat-start",{era:"higher",mode:"arena-fixed"});uiState.selectedMode=String(mode||"");uiState.requestedRuns=Math.max(1,Number(count)||1);view="dungeon-arena";if(typeof render==="function")render();setTimeout(playSelected,0);return true;};
 window.requestThirdWorldArenaUiStop=function(){const out=typeof window.requestThirdWorldArenaStop==="function"?window.requestThirdWorldArenaStop():{ok:false};if(typeof render==="function")render();return out;};
 window.THIRD_WORLD_ARENA_UI_VERSION=VERSION;
 window.THIRD_WORLD_ARENA_STYLE_OWNER_VERSION=STYLE_OWNER_VERSION;
 window.THIRD_WORLD_ARENA_PLAYER_FLOW_VERSION=3;
 window.THIRD_WORLD_ARENA_BATCH_BUTTON_VERSION=1;
 window.THIRD_WORLD_ARENA_RELOAD_SAFE_PRESENTATION_VERSION=1;
 window.THIRD_WORLD_ARENA_STRUCTURED_PRESENTATION_VERSION=3;
 window.THIRD_WORLD_ARENA_FORMAL_PLAYER_FIX_VERSION=1;
 window.THIRD_WORLD_ARENA_REWARD_PRESENTATION_VERSION=2;
 window.THIRD_WORLD_ARENA_UI_CORE_DELEGATION_VERSION=1;
})();
