(function(){
 const VERSION=7;
 const EXPECTED=Object.freeze({THIRD_WORLD_DATA_VERSION:5,THIRD_WORLD_BOSS_DATA_VERSION:1,THIRD_WORLD_BOSS_STAGE_VERSION:1,THIRD_WORLD_BOSS_ABILITY_DESCRIPTOR_VERSION:1,THIRD_WORLD_BOSS_PROGRESS_SNAPSHOT_VERSION:1,THIRD_WORLD_BOSS_AGGREGATE_SNAPSHOT_VERSION:1,THIRD_WORLD_FIVE_POINT_FRONT_VERSION:1,THIRD_WORLD_CHALLENGE_GATE_VERSION:1,THIRD_WORLD_TITLE_RULE_VERSION:2,THIRD_WORLD_DATA_INTEGRITY_VERSION:3,THIRD_WORLD_BOSS_PERSISTENCE_ORDER_VERSION:1,THIRD_WORLD_TITLE_HP_AUTHORITY_VERSION:1,THIRD_WORLD_DATA_OWNER_REQUIREMENT_VERSION:1,THIRD_WORLD_FIVE_POINT_AUTHORITY_VERSION:1,THIRD_WORLD_TITLE_API_SEMANTICS_VERSION:1,THIRD_WORLD_SNAPSHOT_USAGE_POLICY_VERSION:1,SAVE_THIRD_WORLD_BOSS_MIGRATION_REGRESSION_VERSION:1,THIRD_WORLD_COMBAT_VERSION:5,THIRD_WORLD_COMBAT_RESULT_CONTRACT_VERSION:2,THIRD_WORLD_COMBAT_SETTLEMENT_BASIS_VERSION:2,THIRD_WORLD_SETTLEMENT_AUTHORITY_VERSION:1,THIRD_WORLD_RESULT_DIAGNOSTIC_VERSION:1,THIRD_WORLD_FORMAL_HP_OVERRIDE_GUARD_VERSION:1,THIRD_WORLD_MARK_MAX_LEVEL_SOURCE_VERSION:1,THIRD_WORLD_COMBAT_INTEGRITY_VERSION:4,COMBAT_ACTION_SAFETY_VERSION:1,MARK_MAX_LEVEL_OWNER_VERSION:1,SPECIALIZATION_COMBAT_RULE_SOURCE_VERSION:1,THIRD_WORLD_COMBAT_SAVE_GUARD_VERSION:1,THIRD_WORLD_COMBAT_SAVE_SCHEMA_POLICY_VERSION:1,THIRD_WORLD_COMBAT_FINALIZE_VERSION:1,THIRD_WORLD_COMBAT_PUBLIC_API_VERSION:1,THIRD_WORLD_COMBAT_PRIVATE_HELPER_RETIRE_VERSION:1,THIRD_WORLD_COMBAT_INTEGRITY_SUMMARY_VERSION:1,SHARED_SETTLEMENT_TRANSACTION_VERSION:1,THIRD_WORLD_PROGRESS_VERSION:1,THIRD_WORLD_SETTLEMENT_VERSION:1,THIRD_WORLD_SETTLEMENT_REPLAY_GUARD_VERSION:1,SECOND_WORLD_SHARED_SETTLEMENT_TRANSACTION_VERSION:1});
 const REQUIRED_APIS=Object.freeze(["thirdWorldBossIndex","thirdWorldBoss","thirdWorldBossStage","thirdWorldBossStats","thirdWorldBossAbilities","thirdWorldBossProgressSnapshot","thirdWorldBossAggregateSnapshot","thirdWorldChallengeStatus","thirdWorldChallengeAllowed","canChallengeThirdWorldBoss","thirdWorldTotalRemainingPercent","thirdWorldOverallRemainingPercent","thirdWorldTitleTierForRemainingHp","thirdWorldTitleTierForRemainingPercentSum","thirdWorldTitleTier","thirdWorldTitleDefinition","thirdWorldCurrentTitleDefinition","validateThirdWorldData","runThirdWorldBossMigrationRegression","createThirdWorldBossCombatSnapshot","thirdWorldSettlementBasisFromResult","canRunThirdWorldBossCombat","runThirdWorldBossCombat","settleThirdWorldCombatResult","runSettlementTransaction","markMaxLevel","specializationCombatRuleSnapshot"]);
 const baseRun=window.runCivilizationIntegrityContract;
 if(typeof baseRun!=="function")throw new Error("Third-world integrity contract extension requires canonical integrity contract owner.");
 function run(options={}){
  const base=baseRun(options)||{},errors=Array.isArray(base.errors)?base.errors.slice():[];
  Object.entries(EXPECTED).forEach(([name,expected])=>{const actual=Number(window[name]);if(actual!==expected)errors.push({code:"THIRD_WORLD_VERSION_MISMATCH",name,expected,actual:Number.isFinite(actual)?actual:null});});
  REQUIRED_APIS.forEach(name=>{if(typeof window[name]!=="function")errors.push({code:"THIRD_WORLD_API_MISSING",name});});
  if(Number(window.SAVE_SCHEMA_VERSION)!==16)errors.push({code:"THIRD_WORLD_COMBAT_SCHEMA_DRIFT",expected:16,actual:Number(window.SAVE_SCHEMA_VERSION)||0});
  if(window.THIRD_WORLD_COMBAT_SAVE_SCHEMA_BUMP_REQUIRED!==false)errors.push({code:"THIRD_WORLD_COMBAT_SCHEMA_BUMP_POLICY",value:window.THIRD_WORLD_COMBAT_SAVE_SCHEMA_BUMP_REQUIRED});
  if(window.THIRD_WORLD_DATA_INTEGRITY?.passed!==true)errors.push({code:"THIRD_WORLD_DATA_INTEGRITY",report:window.THIRD_WORLD_DATA_INTEGRITY||null});
  if(window.SAVE_THIRD_WORLD_BOSS_MIGRATION_REGRESSION_REPORT?.passed!==true)errors.push({code:"THIRD_WORLD_BOSS_MIGRATION_REGRESSION",report:window.SAVE_THIRD_WORLD_BOSS_MIGRATION_REGRESSION_REPORT||null});
  if(window.THIRD_WORLD_COMBAT_INTEGRITY_SUMMARY?.passed!==true)errors.push({code:"THIRD_WORLD_COMBAT_INTEGRITY_SUMMARY",report:window.THIRD_WORLD_COMBAT_INTEGRITY_SUMMARY||null});
  if(window.THIRD_WORLD_COMBAT_SAVE_GUARD_REPORT?.passed!==true)errors.push({code:"THIRD_WORLD_COMBAT_SAVE_GUARD",report:window.THIRD_WORLD_COMBAT_SAVE_GUARD_REPORT||null});
  if(window.SETTLEMENT_TRANSACTION_INTEGRITY?.passed!==true)errors.push({code:"SHARED_SETTLEMENT_TRANSACTION",report:window.SETTLEMENT_TRANSACTION_INTEGRITY||null});
  if(window.THIRD_WORLD_PROGRESS_INTEGRITY?.passed!==true)errors.push({code:"THIRD_WORLD_PROGRESS_INTEGRITY",report:window.THIRD_WORLD_PROGRESS_INTEGRITY||null});
  if(window.SECOND_WORLD_REWARD_INTEGRITY?.passed!==true)errors.push({code:"SECOND_WORLD_REWARD_INTEGRITY",report:window.SECOND_WORLD_REWARD_INTEGRITY||null});
  if(Number(window.SECOND_WORLD_SHARED_SETTLEMENT_TRANSACTION_VERSION)!==1)errors.push({code:"SECOND_WORLD_SHARED_SETTLEMENT_TRANSACTION",actual:window.SECOND_WORLD_SHARED_SETTLEMENT_TRANSACTION_VERSION});
  const publicApis=Array.from(window.THIRD_WORLD_COMBAT_PUBLIC_APIS||[]),requiredPublic=["createThirdWorldBossCombatSnapshot","thirdWorldSettlementBasisFromResult","canRunThirdWorldBossCombat","runThirdWorldBossCombat"];
  if(JSON.stringify(publicApis)!==JSON.stringify(requiredPublic))errors.push({code:"THIRD_WORLD_COMBAT_PUBLIC_API_POLICY",publicApis});
  Array.from(window.THIRD_WORLD_COMBAT_RETIRED_APIS||[]).forEach(name=>{if(typeof window[name]!=="undefined")errors.push({code:"THIRD_WORLD_COMBAT_PRIVATE_API_LEAK",name});});
  if(window.MARK_CORE_INTEGRITY?.passed!==true)errors.push({code:"MARK_CORE_INTEGRITY",report:window.MARK_CORE_INTEGRITY||null});
  if(Number(window.markMaxLevel?.())!==Number(window.MARK_MAX_LEVEL))errors.push({code:"THIRD_WORLD_MARK_MAX_OWNER",markMaxLevel:typeof window.markMaxLevel==="function"?window.markMaxLevel():null,constant:window.MARK_MAX_LEVEL});
  if(window.specializationCombatRuleSnapshot?.()!==window.COMBAT_STANDARD_ABILITY_RULES)errors.push({code:"THIRD_WORLD_SPECIALIZATION_COMBAT_RULE_OWNER"});
  const actionSafety=window.COMBAT_ACTION_SAFETY_RULES;
  if(!(Number(actionSafety?.maxActionsPerRun)>0)||!(Number(actionSafety?.maxActionsPerChain)>0)||Number(actionSafety?.maxActionsPerChain)>Number(actionSafety?.maxActionsPerRun))errors.push({code:"THIRD_WORLD_COMBAT_ACTION_SAFETY",rules:actionSafety||null});
  const settlementAuthority=window.THIRD_WORLD_SETTLEMENT_AUTHORITY;
  if(settlementAuthority?.field!=="settlementBasis"||settlementAuthority?.version!==1||settlementAuthority?.topLevelSettlementFields!=="convenience-only"||settlementAuthority?.combat!=="diagnostic-only"||settlementAuthority?.snapshot!=="diagnostic-only")errors.push({code:"THIRD_WORLD_SETTLEMENT_AUTHORITY",authority:settlementAuthority||null});
  const authority=window.THIRD_WORLD_CHALLENGE_AUTHORITY,policy=window.THIRD_WORLD_SNAPSHOT_USAGE_POLICY;
  if(authority?.decisionField!=="allowed"||authority?.gapField!=="gapHp"||authority?.thresholdField!=="fivePointHpGap"||authority?.displayOnlyFields?.includes("gapPoints")!==true)errors.push({code:"THIRD_WORLD_FIVE_POINT_AUTHORITY",authority:authority||null});
  if(policy?.resolveAtBattleStart!==true||policy?.reuseDuringCombatRun!==true||policy?.refreshAfterSettlement!==true||policy?.globalCache!==false||policy?.combatTickRecompute!==false)errors.push({code:"THIRD_WORLD_SNAPSHOT_USAGE_POLICY",policy:policy||null});
  return {...base,passed:errors.length===0,errors};
 }
 window.CIVILIZATION_THIRD_WORLD_DATA_CONTRACT_EXTENSION_VERSION=VERSION;
 window.CIVILIZATION_THIRD_WORLD_DATA_EXPECTED_VERSIONS=EXPECTED;
 window.CIVILIZATION_THIRD_WORLD_DATA_REQUIRED_APIS=REQUIRED_APIS;
 window.CIVILIZATION_INTEGRITY_EXPECTED_VERSIONS=Object.freeze({...window.CIVILIZATION_INTEGRITY_EXPECTED_VERSIONS,...EXPECTED});
 window.runCivilizationIntegrityContract=run;
})();