(function(){
 const VERSION=15;
 const EXPECTED=Object.freeze({
  THIRD_WORLD_DATA_VERSION:5,THIRD_WORLD_BOSS_DATA_VERSION:1,THIRD_WORLD_BOSS_STAGE_VERSION:1,THIRD_WORLD_BOSS_ABILITY_DESCRIPTOR_VERSION:1,THIRD_WORLD_BOSS_PROGRESS_SNAPSHOT_VERSION:1,THIRD_WORLD_BOSS_AGGREGATE_SNAPSHOT_VERSION:1,THIRD_WORLD_FIVE_POINT_FRONT_VERSION:1,THIRD_WORLD_CHALLENGE_GATE_VERSION:1,THIRD_WORLD_TITLE_RULE_VERSION:2,THIRD_WORLD_DATA_INTEGRITY_VERSION:3,THIRD_WORLD_BOSS_PERSISTENCE_ORDER_VERSION:1,THIRD_WORLD_TITLE_HP_AUTHORITY_VERSION:1,THIRD_WORLD_DATA_OWNER_REQUIREMENT_VERSION:1,THIRD_WORLD_FIVE_POINT_AUTHORITY_VERSION:1,THIRD_WORLD_TITLE_API_SEMANTICS_VERSION:1,THIRD_WORLD_SNAPSHOT_USAGE_POLICY_VERSION:1,
  SAVE_THIRD_WORLD_BOSS_MIGRATION_REGRESSION_VERSION:2,THIRD_WORLD_PRE_SCHEMA16_POLICY_REGRESSION_VERSION:1,THIRD_WORLD_TRANSIENT_DROP_REGRESSION_VERSION:1,
  THIRD_WORLD_COMBAT_VERSION:5,THIRD_WORLD_COMBAT_RESULT_CONTRACT_VERSION:2,THIRD_WORLD_COMBAT_SETTLEMENT_BASIS_VERSION:2,THIRD_WORLD_SETTLEMENT_AUTHORITY_VERSION:1,THIRD_WORLD_RESULT_DIAGNOSTIC_VERSION:1,THIRD_WORLD_FORMAL_HP_OVERRIDE_GUARD_VERSION:1,THIRD_WORLD_MARK_MAX_LEVEL_SOURCE_VERSION:1,THIRD_WORLD_COMBAT_INTEGRITY_VERSION:4,COMBAT_ACTION_SAFETY_VERSION:1,MARK_MAX_LEVEL_OWNER_VERSION:1,SPECIALIZATION_COMBAT_RULE_SOURCE_VERSION:1,THIRD_WORLD_COMBAT_SAVE_GUARD_VERSION:1,THIRD_WORLD_COMBAT_SAVE_SCHEMA_POLICY_VERSION:1,THIRD_WORLD_COMBAT_FINALIZE_VERSION:1,THIRD_WORLD_COMBAT_PUBLIC_API_VERSION:1,THIRD_WORLD_COMBAT_PRIVATE_HELPER_RETIRE_VERSION:1,THIRD_WORLD_COMBAT_INTEGRITY_SUMMARY_VERSION:1,
  SHARED_SETTLEMENT_TRANSACTION_VERSION:2,SHARED_SETTLEMENT_ROLLBACK_IDENTITY_VERSION:1,SHARED_SETTLEMENT_NESTED_REFERENCE_VERSION:1,SHARED_EQUIPMENT_REWARD_FACTORY_VERSION:3,SHARED_EQUIPMENT_RNG_PIPELINE_VERSION:1,SHARED_EQUIPMENT_METADATA_OWNER_VERSION:1,VIP_LOOT_CORE_VERSION:2,LEVEL_PROGRESSION_VERSION:2,LEVEL_TARGET_EXP_OWNER_VERSION:1,
  THIRD_WORLD_EQUIPMENT_REWARD_VERSION:3,THIRD_WORLD_EQUIPMENT_QUALITY_POLICY_VERSION:1,THIRD_WORLD_EQUIPMENT_DETERMINISTIC_VERSION:1,THIRD_WORLD_EQUIPMENT_METADATA_OWNER_VERSION:1,
  THIRD_WORLD_PROGRESS_VERSION:4,THIRD_WORLD_SETTLEMENT_VERSION:4,THIRD_WORLD_SETTLEMENT_REPLAY_GUARD_VERSION:1,THIRD_WORLD_SETTLEMENT_ECONOMY_VERSION:1,THIRD_WORLD_SETTLEMENT_EQUIPMENT_VERSION:1,THIRD_WORLD_AGGREGATE_PROGRESSION_VERSION:1,THIRD_WORLD_TITLE_SETTLEMENT_VERSION:1,THIRD_WORLD_STORY_STAGE_SETTLEMENT_VERSION:1,THIRD_WORLD_BOSS_DEFEAT_SETTLEMENT_VERSION:1,THIRD_WORLD_STAGE_CROSSING_SETTLEMENT_VERSION:1,THIRD_WORLD_POST_SETTLEMENT_FIVE_POINT_VERSION:1,THIRD_WORLD_CONTINUATION_DECISION_VERSION:1,
  THIRD_WORLD_TITLE_BACKFILL_VERSION:1,PLAYER_TITLE_THIRD_WORLD_CATALOG_EXTENSION_VERSION:1,PLAYER_TITLE_THIRD_WORLD_RENDERER_VERSION:1,PLAYER_TITLE_THIRD_WORLD_NOTICE_VERSION:1,PLAYER_TITLE_THIRD_WORLD_BACKFILL_REGRESSION_VERSION:1,PLAYER_TITLE_INTEGRITY_VERSION:11,
  THIRD_WORLD_RUN_VERSION:2,THIRD_WORLD_SUPPRESSION_VERSION:1,THIRD_WORLD_CONTINUOUS_RUNTIME_VERSION:2,THIRD_WORLD_RUN_EVENT_PAUSE_VERSION:1,THIRD_WORLD_RUN_PAGEHIDE_RESET_VERSION:2,THIRD_WORLD_RUN_FAST_CATCH_UP_VERSION:1,THIRD_WORLD_RUN_BOUNDED_HISTORY_VERSION:1,THIRD_WORLD_RUN_ACTIVE_FLOW_GUARD_VERSION:1,THIRD_WORLD_RUN_SHARED_PAGEHIDE_OWNER_VERSION:1,THIRD_WORLD_RUN_RESULT_SUMMARY_VERSION:1,THIRD_WORLD_RUN_INTEGRITY_VERSION:2,
  SECOND_WORLD_SHARED_SETTLEMENT_TRANSACTION_VERSION:1,
  THIRD_WORLD_SUBSYSTEM_INTEGRITY_VERSION:1,THIRD_WORLD_DATA_SUBSYSTEM_INTEGRITY_VERSION:1,THIRD_WORLD_COMBAT_SUBSYSTEM_INTEGRITY_VERSION:1,THIRD_WORLD_PROGRESSION_SUBSYSTEM_INTEGRITY_VERSION:1,THIRD_WORLD_RUN_SUBSYSTEM_INTEGRITY_VERSION:1
 });
 const REQUIRED_APIS=Object.freeze(["thirdWorldBossIndex","thirdWorldBoss","thirdWorldBossStage","thirdWorldBossStats","thirdWorldBossAbilities","thirdWorldBossProgressSnapshot","thirdWorldBossAggregateSnapshot","thirdWorldChallengeStatus","thirdWorldChallengeAllowed","canChallengeThirdWorldBoss","thirdWorldTotalRemainingPercent","thirdWorldOverallRemainingPercent","thirdWorldTitleTierForRemainingHp","thirdWorldTitleTierForRemainingPercentSum","thirdWorldTitleTier","thirdWorldTitleDefinition","thirdWorldCurrentTitleDefinition","validateThirdWorldData","runThirdWorldBossMigrationRegression","createThirdWorldBossCombatSnapshot","thirdWorldSettlementBasisFromResult","canRunThirdWorldBossCombat","runThirdWorldBossCombat","thirdWorldEquipmentBaseQualityRoll","makeThirdWorldEquipmentForBoss","makeThirdWorldBossEquipmentDrops","settleThirdWorldCombatResult","runSettlementTransaction","makeEquipmentRewardItem","sharedEquipmentTypes","sharedEquipmentTypeLabel","gainEffectiveExpForState","markMaxLevel","specializationCombatRuleSnapshot","getPlayerTitleDefinitionForThirdWorldTier","grantPlayerTitlesForThirdWorldTier","thirdWorldSuppressionPerDeathPoints","thirdWorldRunHpCapSnapshot","thirdWorldRunConflictStatus","thirdWorldContinuousRunSnapshot","startThirdWorldContinuousRun","stopThirdWorldContinuousRun","acknowledgeThirdWorldContinuousRunEvents","runThirdWorldContinuousBattle","runThirdWorldContinuousLoop"]);
 const baseRun=window.runCivilizationIntegrityContract;
 if(typeof baseRun!=="function")throw new Error("Third-world integrity contract extension requires canonical integrity contract owner.");
 function run(options={}){
  const base=baseRun(options)||{},errors=Array.isArray(base.errors)?base.errors.slice():[];
  Object.entries(EXPECTED).forEach(([name,expected])=>{const actual=Number(window[name]);if(actual!==expected)errors.push({code:"THIRD_WORLD_VERSION_MISMATCH",name,expected,actual:Number.isFinite(actual)?actual:null});});
  REQUIRED_APIS.forEach(name=>{if(typeof window[name]!=="function")errors.push({code:"THIRD_WORLD_API_MISSING",name});});
  const subsystem=window.THIRD_WORLD_SUBSYSTEM_INTEGRITY;
  if(subsystem?.passed!==true)errors.push({code:"THIRD_WORLD_SUBSYSTEM_INTEGRITY",report:subsystem||null});
  const reports=subsystem?.reports||{};
  ["data","combat","progression","run"].forEach(name=>{if(reports?.[name]?.passed!==true)errors.push({code:"THIRD_WORLD_SUBSYSTEM_REPORT",name,report:reports?.[name]||null});});
  return {...base,passed:errors.length===0,errors};
 }
 window.CIVILIZATION_THIRD_WORLD_DATA_CONTRACT_EXTENSION_VERSION=VERSION;
 window.CIVILIZATION_THIRD_WORLD_DATA_EXPECTED_VERSIONS=EXPECTED;
 window.CIVILIZATION_THIRD_WORLD_DATA_REQUIRED_APIS=REQUIRED_APIS;
 window.CIVILIZATION_INTEGRITY_EXPECTED_VERSIONS=Object.freeze({...window.CIVILIZATION_INTEGRITY_EXPECTED_VERSIONS,...EXPECTED});
 window.runCivilizationIntegrityContract=run;
})();
