const {chromium}=require("playwright");
const assert=require("assert");
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage();
 const pageErrors=[];
 page.on("pageerror",error=>pageErrors.push(String(error?.stack||error?.message||error)));
 const url=process.env.RUNTIME_SMOKE_URL||"http://127.0.0.1:4173/index.html";
 try{
  await page.goto(url,{waitUntil:"domcontentloaded",timeout:30000});
  await page.waitForFunction(()=>window.CIVILIZATION_FINAL_INTEGRITY_REPORT&&window.PROJECT_RUNTIME_REPORT,{timeout:30000});
  const snapshot=await page.evaluate(()=>{
   const higher={level:1000,secondWorld:{entered:true,darkMatter:0,darkEnergy:0},thirdWorld:{entered:true,dimensionalStrings:0}};
   const universe={level:600,secondWorld:{entered:true,civilizationLevel:10,darkMatter:0,darkEnergy:0},thirdWorld:{entered:false}};
   const arena=typeof window.dungeonModeAvailability==="function"?window.dungeonModeAvailability("arena",higher):null;
   const bounty=typeof window.dungeonModeAvailability==="function"?window.dungeonModeAvailability("bounty",higher):null;
   const contract=typeof window.runCanonicalCivilizationIntegrityContract==="function"?window.runCanonicalCivilizationIntegrityContract({phase:"browser-smoke"}):null;
   const safetyBefore=typeof window.localSaveSafetySnapshot==="function"?window.localSaveSafetySnapshot():null;
   const capacity=typeof window.localSaveCapacitySnapshot==="function"?window.localSaveCapacitySnapshot():null;
   const migrationRegression=typeof window.runSaveMigrationStaircaseRegression==="function"?window.runSaveMigrationStaircaseRegression():null;
   const migrationPlanV1=typeof window.saveMigrationPlanForVersion==="function"?window.saveMigrationPlanForVersion(1):null;
   const migrationPlanV16=typeof window.saveMigrationPlanForVersion==="function"?window.saveMigrationPlanForVersion(16):null;
   const offlinePolicy=typeof window.offlineBattleSamplePolicySnapshot==="function"?window.offlineBattleSamplePolicySnapshot():null;
   const offlineMultiplier={same:window.offlineBattleSampleMultiplier?.(100,100),gap6:window.offlineBattleSampleMultiplier?.(100,94),gap10:window.offlineBattleSampleMultiplier?.(100,90),gap15:window.offlineBattleSampleMultiplier?.(100,85),gap16:window.offlineBattleSampleMultiplier?.(100,84)};
   const backup=typeof window.ensureLocalSaveSafetyBackup==="function"?window.ensureLocalSaveSafetyBackup("browser-smoke"):null;
   const loadPolicies={gm:window.scriptLoadPolicySnapshot?.("gmhub.js"),story:window.scriptLoadPolicySnapshot?.("storyprogress.js"),integrity:window.scriptLoadPolicySnapshot?.("runtimeintegrity.js"),core:window.scriptLoadPolicySnapshot?.("combatcore.js")};
   const saveHooks={runtimeOwner:window.SAVE_HOOK_RUNTIME_OWNER||null,wrapperOwner:window.save?.__saveHookOwner||null,coreVersion:window.SAVE_HOOK_CORE_VERSION||null,before:window.getBeforeSaveHookIds?.()||[],after:window.getAfterSaveHookIds?.()||[],settlement:window.getSaveSettlementHookIds?.()||[],saveAvailable:typeof window.save==="function",safetyHookId:window.SAVE_SAFETY_HOOK_ID||null};
   const transitionGuards=window.WORLD_TRANSITION_GUARD_INSTALL_REPORT||null;
   const legacyGlobals=window.legacyGlobalAliasSnapshot?.()||null;
   const adapterProbe=(()=>{
    if(typeof window.runWorldCombatCore!=="function"||typeof window.runCombatCore!=="function")return null;
    const player={hp:1000,atk:100,def:20,crit:0,dodge:0};
    const enemy={name:"Adapter Probe",hp:1000,atk:80,def:10,crit:0,dodge:0};
    const sequence=[.91,.91,.91,.91,.91,.91,.91,.91,.91,.91,.91,.91,.91,.91,.91,.91];
    const makeRng=()=>{let i=0;return ()=>sequence[i++%sequence.length];};
    const multiplier=window.worldCombatDamageMultiplier?.(2,universe,10);
    const direct=window.runCombatCore(player,enemy,1000,{rng:makeRng(),logs:false,maxTurns:2,playerFinalDamageMultiplier:multiplier});
    const adapted=window.runWorldCombatCore(player,enemy,1000,{world:2,state:universe,civilizationLevel:10,rng:makeRng(),logs:false,maxTurns:2});
    return {multiplier,direct:{hp:direct.hp,enemyHp:direct.enemyHp,turns:direct.turns,win:direct.win},adaptedMultiplier:adapted.playerFinalDamageMultiplier,adapted:{hp:adapted.combat.hp,enemyHp:adapted.combat.enemyHp,turns:adapted.combat.turns,win:adapted.combat.win}};
   })();
   return {runtime:window.PROJECT_RUNTIME_REPORT||null,final:window.CIVILIZATION_FINAL_INTEGRITY_REPORT||null,contract,gmBatch16:window.GM_BATCH16_INTEGRITY||null,offlineOwner:window.OFFLINE_SAMPLE_OWNER_INTEGRITY||null,versions:{contract:window.CIVILIZATION_INTEGRITY_CONTRACT_VERSION,runtime:window.PROJECT_RUNTIME_INTEGRITY_VERSION,final:window.CIVILIZATION_FINAL_INTEGRITY_VERSION,offline:window.OFFLINE_STATE_NORMALIZATION_VERSION,sample:window.OFFLINE_BATTLE_SAMPLE_VERSION,offlineOwner:window.OFFLINE_SAMPLE_OWNER_VERSION,offlinePolicy:window.OFFLINE_SAMPLE_POLICY_VERSION,mainSample:window.MAIN_REAL_BATTLE_SAMPLE_VERSION,mainConvergence:window.MAIN_OFFLINE_SAMPLE_OWNER_CONVERGENCE_VERSION,w3Dungeon:window.THIRD_WORLD_DUNGEON_UI_VERSION,saveSafety:window.SAVE_SAFETY_VERSION,saveCapacity:window.SAVE_CAPACITY_DIAGNOSTIC_VERSION,migrationStaircase:window.SAVE_MIGRATION_STAIRCASE_VERSION,saveHook:window.SAVE_HOOK_CORE_VERSION,scriptLoad:window.SCRIPT_LOAD_POLICY_VERSION,worldTransitionSafety:window.WORLD_TRANSITION_SUBSYSTEM_SAFETY_VERSION,worldTransitionInstall:window.WORLD_TRANSITION_GUARD_INSTALL_VERSION,combatAdapter:window.COMBAT_WORLD_ADAPTER_VERSION,dungeonAdapter:window.DUNGEON_WORLD_COMBAT_ADAPTER_VERSION,secondWorldAdapter:window.SECOND_WORLD_WORLD_COMBAT_ADAPTER_VERSION,legacyCompatibility:window.LEGACY_COMPATIBILITY_OWNER_VERSION,legacyGlobalPolicy:window.LEGACY_GLOBAL_ALIAS_POLICY_VERSION,w3SaveGuard:window.THIRD_WORLD_COMBAT_SAVE_GUARD_VERSION,w3SaveHook:window.THIRD_WORLD_COMBAT_SAVE_HOOK_CONVERGENCE_VERSION},arena,bounty,stateSchema:typeof state!=="undefined"?state?.saveVersion:null,schema:window.SAVE_SCHEMA_VERSION,safetyBefore,capacity,migrationRegression,migrationPlanV1,migrationPlanV16,offlinePolicy,offlineMultiplier,backup,loadPolicies,saveHooks,transitionGuards,legacyGlobals,adapterProbe};
  });
  assert.equal(snapshot.versions.contract,3,"Contract V3 未載入");
  assert.equal(snapshot.versions.runtime,21,"Runtime Integrity V21 未載入");
  assert.equal(snapshot.versions.final,21,"Final Integrity V21 未載入");
  assert.ok(snapshot.versions.saveSafety>=2,"Save Safety 低於 V2");
  assert.equal(snapshot.versions.saveCapacity,1,"Save Capacity Diagnostic V1 未載入");
  assert.equal(snapshot.versions.migrationStaircase,1,"Save Migration Staircase V1 未載入");
  assert.equal(snapshot.versions.saveHook,2,"Save Hook Core V2 未載入");
  assert.equal(snapshot.versions.scriptLoad,3,"Script Load Policy V3 未載入");
  assert.ok(snapshot.versions.worldTransitionSafety>=5,"World Transition Safety 低於 V5");
  assert.equal(snapshot.versions.worldTransitionInstall,2,"World Transition Guard single-install V2 未載入");
  assert.equal(snapshot.versions.combatAdapter,1,"World Combat Adapter V1 未載入");
  assert.equal(snapshot.versions.dungeonAdapter,1,"Dungeon 未切到 World Combat Adapter");
  assert.equal(snapshot.versions.secondWorldAdapter,1,"第二紀元主線未切到 World Combat Adapter");
  assert.ok(snapshot.versions.legacyCompatibility>=3,"Legacy Compatibility owner 低於 V3");
  assert.equal(snapshot.versions.legacyGlobalPolicy,1,"Legacy Global Alias Policy V1 未載入");
  assert.ok(snapshot.versions.w3SaveGuard>=2,"W3 Combat Save Guard 低於 V2");
  assert.equal(snapshot.versions.w3SaveHook,1,"W3 Combat Save Guard 尚未收斂到 before-save hook");
  assert.ok(snapshot.versions.offline>=4,"Offline normalization 低於 V4");
  assert.ok(snapshot.versions.sample>=4,"Offline sample 低於 V4");
  assert.ok(snapshot.versions.offlineOwner>=2,"Offline Sample Owner 低於 V2");
  assert.equal(snapshot.versions.offlinePolicy,1,"Offline Sample Policy V1 未載入");
  assert.equal(snapshot.versions.mainSample,4,"Main real battle sample consumer 未升級到 V4");
  assert.equal(snapshot.versions.mainConvergence,1,"Main Offline sample convergence V1 未載入");
  assert.ok(snapshot.versions.w3Dungeon>=6,"W3 dungeon UI 低於 V6");
  assert.equal(snapshot.runtime?.passed,true,"PROJECT_RUNTIME_REPORT 未通過："+JSON.stringify(snapshot.runtime?.errors||null));
  assert.equal(snapshot.contract?.passed,true,"Canonical contract 未通過："+JSON.stringify(snapshot.contract?.errors||null));
  assert.equal(snapshot.final?.passed,true,"Final Integrity 未通過："+JSON.stringify(snapshot.final?.errors||null));
  assert.equal(snapshot.gmBatch16?.passed,true,"GM Batch16 integrity 未通過："+JSON.stringify(snapshot.gmBatch16?.errors||null));
  assert.equal(snapshot.offlineOwner?.passed,true,"Offline sample owner integrity 未通過："+JSON.stringify(snapshot.offlineOwner?.errors||null));
  assert.equal(snapshot.offlinePolicy?.samplesPerSpeed,8,"Offline sample canonical retention 應為每倍速 8 筆");
  assert.deepEqual(snapshot.offlinePolicy?.combatSpeeds,[1,1.5,2],"Offline sample canonical speed pool 不一致");
  assert.deepEqual(snapshot.offlineMultiplier,{same:1,gap6:1.3,gap10:1.6,gap15:2,gap16:null},"Offline sample multiplier canonical policy 不一致");
  assert.equal(snapshot.arena?.visible,true,"W3 高維競技場應可見");assert.equal(snapshot.arena?.enabled,true,"W3 高維競技場應可進入");assert.equal(snapshot.bounty?.visible,false,"W3 懸賞戰應隱藏");
  assert.equal(snapshot.stateSchema,snapshot.schema,"啟動後 state schema 與正式 schema 不一致");
  assert.ok(Number(snapshot.safetyBefore?.version)>=2,"Save Safety snapshot 版本錯誤");
  assert.ok(Number(snapshot.safetyBefore?.projectedSaveBytes)>=0,"Save Safety 應回報 projected save bytes");
  assert.ok(["normal","warning","critical"].includes(snapshot.capacity?.capacityLevel),"Save Capacity 應回報合法容量級別");
  assert.equal(snapshot.migrationRegression?.passed,true,"Migration staircase regression 未通過："+JSON.stringify(snapshot.migrationRegression?.errors||null));
  assert.ok(snapshot.migrationPlanV1?.some(x=>x.id==="legacy-exp-progress"),"V1 migration plan 應包含 legacy EXP stage");
  assert.ok(snapshot.migrationPlanV1?.some(x=>x.id==="pre-schema16-compatibility"),"V1 migration plan 應包含 pre-Schema16 stage");
  assert.ok(!snapshot.migrationPlanV16?.some(x=>x.id==="legacy-exp-progress"||x.id==="pre-schema16-compatibility"),"V16 migration plan 不應再跑 legacy conditional stages");
  assert.equal(snapshot.backup?.failed,false,"安全備份建立失敗："+JSON.stringify(snapshot.backup));
  assert.equal(snapshot.backup?.verified,true,"安全備份未完成 read-back 驗證："+JSON.stringify(snapshot.backup));
  assert.equal(snapshot.saveHooks.runtimeOwner,"compatibilityowners","Save Hook runtime owner 應為 compatibilityowners");
  assert.equal(snapshot.saveHooks.coreVersion,2,"Save Hook Core 應為 V2");
  assert.equal(snapshot.saveHooks.saveAvailable,true,"save() runtime function 必須存在");
  assert.equal(snapshot.saveHooks.safetyHookId,"save-capacity-diagnostic","Save Safety hook ID 不一致");
  assert.ok(snapshot.saveHooks.before.includes(snapshot.saveHooks.safetyHookId),"Save Safety 應使用 before-save hook");
  assert.ok(snapshot.saveHooks.before.includes("third-world-combat-transient-cleanup"),"W3 transient save guard 應使用 before-save hook");
  assert.ok(snapshot.saveHooks.settlement.includes(snapshot.saveHooks.safetyHookId),"Save Safety 應使用 settlement hook");
  assert.ok(snapshot.saveHooks.after.includes("cloud-local-meta"),"Cloud Save metadata after-save hook 應保留");
  assert.deepEqual(snapshot.loadPolicies.gm,{version:3,group:"gm",startupCritical:false,deferRecommended:true,fetchPriority:"low"},"GM load policy 不符");
  assert.deepEqual(snapshot.loadPolicies.story,{version:3,group:"story",startupCritical:false,deferRecommended:true,fetchPriority:"low"},"Story load policy 不符");
  assert.deepEqual(snapshot.loadPolicies.integrity,{version:3,group:"integrity",startupCritical:false,deferRecommended:true,fetchPriority:"low"},"Integrity load policy 不符");
  assert.equal(snapshot.loadPolicies.core?.startupCritical,true,"Combat core 應維持 startup critical");
  assert.equal(snapshot.transitionGuards?.bountyGateInstalled,true,"Bounty world-phase gate 應一次安裝成功");
  assert.equal(snapshot.transitionGuards?.offlineGuardsInstalled,true,"Offline world-phase guards 應一次安裝成功");
  assert.equal(snapshot.legacyGlobals?.policy,"read-compatible-no-duplicate-write","Legacy global policy 應為只讀相容、不重複寫入");
  assert.equal(snapshot.legacyGlobals?.maxLevel?.legacy,500,"Legacy MAX_LEVEL 應維持 500");
  assert.equal(snapshot.legacyGlobals?.maxLevel?.windowAlias,500,"window.MAX_LEVEL alias 應由 engine 維持 500");
  assert.equal(snapshot.legacyGlobals?.saveVersion?.legacy,13,"Legacy SAVE_VERSION 應維持 13 僅供相容讀取");
  assert.equal(snapshot.legacyGlobals?.saveVersion?.canonical,16,"Canonical save schema 應維持 16");
  assert.equal(snapshot.adapterProbe?.multiplier,1.5,"W2 文明 Lv10 最終傷害倍率應維持 1.5");
  assert.equal(snapshot.adapterProbe?.adaptedMultiplier,snapshot.adapterProbe?.multiplier,"World Adapter 使用的倍率應與 canonical civilization owner 一致");
  assert.deepEqual(snapshot.adapterProbe?.adapted,snapshot.adapterProbe?.direct,"相同 RNG 與參數下 World Adapter 不得改變 runCombatCore 結果");
  assert.deepEqual(pageErrors,[],"瀏覽器 pageerror：\n"+pageErrors.join("\n\n"));
  console.log("Browser runtime smoke passed:",JSON.stringify({versions:snapshot.versions,offlinePolicy:snapshot.offlinePolicy,arena:snapshot.arena,bounty:snapshot.bounty,saveCapacity:{projectedSaveBytes:snapshot.capacity?.projectedSaveBytes,capacityLevel:snapshot.capacity?.capacityLevel,inventoryCount:snapshot.capacity?.inventoryCount,lostGearCount:snapshot.capacity?.lostGearCount},migrationStagesV1:snapshot.migrationPlanV1?.map(x=>x.id),loadPolicies:snapshot.loadPolicies,saveHooks:snapshot.saveHooks,transitionGuards:snapshot.transitionGuards,legacyGlobals:snapshot.legacyGlobals,adapterProbe:snapshot.adapterProbe,runtimeWarnings:snapshot.runtime?.warnings?.length||0,finalWarnings:snapshot.final?.warnings?.length||0}));
 }finally{await browser.close();}
})().catch(error=>{console.error(error?.stack||error);process.exit(1);});
